### ISSUE TITLE
whats wrong

### ISSUE THREAD

**Issue by jiger60** [microsoft/vscode-docker#2195] opened 2020-07-25 12:39 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 1.4.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
DockerNetCoreDebugConfigurationProvider.resolveDockerDebugConfiguration extension.bundle.js:578:847643
extension.bundle.js:578:847550extension.bundle.js:578:847550
Object.<anonymous> extension.bundle.js:3:495519
extension.bundle.js:3:494710extension.bundle.js:3:494710
o extension.bundle.js:3:494396
Object.callWithTelemetryAndErrorHandling extension.bundle.js:3:495427
DockerNetCoreDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:578:847481
extensionHostProcess.js:855:493extensionHostProcess.js:855:493
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by karolz-ms** [comment] 2020-07-27 15:50
@jiger60 can you add repro steps? Do you have a folder open in VS Code and what is the location of the .NET project you are trying to debug?

**Comment by bwateratmsft** [comment] 2020-07-27 21:54
Dupe of #1451

**Closed by bwateratmsft** 2020-07-27 21:54 UTC
Labels: needs more info
