### ISSUE TITLE
Container names in sha values

### ISSUE THREAD

**Issue by stoimenov95** [microsoft/vscode-docker#3040] opened 2021-07-05 14:06 UTC
Issue Type: <b>Bug</b>

Docker extension shows sha256 values instead of the containers' names.

Extension version: 1.13.0
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 9, 5|
|Memory (System)|16.00GB (0.97GB free)|
|Process Argv|--crash-reporter-id 4b078fe9-bfd3-4813-a50c-3d2095d2af6e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
aatestflightcf:30331712
bridge0702cf:30333156

```

</details>

**Comment by karolz-ms** [comment] 2021-07-06 16:58
Thanks for reporting. This is a regression caused by Docker Desktop 3.5/3.5.1. Nightly builds of Docker 3.6 do not exhibit this issue, so I assume it will be fixed in 3.6.

**Closed by karolz-ms** 2021-07-06 16:58 UTC
Labels: external

**Comment by stoimenov95** [comment] 2021-07-06 17:22
Thanks a lot, @karolz-ms. Can't wait for the 3.6 version.

**Comment by davidspiess** [comment] 2021-08-17 08:46
@karolz-ms the 3.6 version is released but it still shows the sha256 values.

**Comment by bwateratmsft** [comment] 2021-08-17 14:58
Looks like this issue is https://github.com/docker/compose-cli/issues/1983. They fixed it, then reverted the fix.
