### ISSUE TITLE
(n.stack || "").split is not a function

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [microsoft/vscode-docker#2833] opened 2021-04-01 22:19 UTC
Does this occur consistently? 
Repro steps:

1. Use VSCode extension to push an image
2.

Action: vscode-docker.images.push
Error type: TypeError
Error Message: (n.stack || "").split is not a function

Version: 1.11.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.0
Language: en

<details>
<summary>Call Stack</summary>

```
getCallstack extension.bundle.js:16:365761
Object.parseError extension.bundle.js:16:366112
new RegistryConnectErrorTreeItem extension.bundle.js:305:64657
DockerHubAccountTreeItem.loadMoreChildrenImpl extension.bundle.js:859:271956
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by bwateratmsft** [comment] 2021-04-02 14:50
It looks like this is fixed by https://github.com/microsoft/vscode-azuretools/pull/860, which will show up in our next version (1.13.0).

**Closed by bwateratmsft** 2021-04-02 14:50 UTC
Labels: investigate

**Comment by bwateratmsft** [comment] 2021-04-05 15:49
Changing this to be a duplicate of #2839.
