### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by SwapnilMWaman** [microsoft/vscode-docker#1986] opened 2020-05-18 05:15 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.installDocker
Error type: ECONNRESET
Error Message: read ECONNRESET

Version: 1.1.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
TLSWrap.onStreamRead stream_base_commons.js:183:27
```

</details>

**Comment by bwateratmsft** [comment] 2020-05-18 13:19
Duplicate of #1913

**Closed by bwateratmsft** 2020-05-18 13:19 UTC
