### ISSUE TITLE
Syntax colorization stops working after RUN command in visual studio code with docker 0.0.27 plugin

### ISSUE THREAD

**Issue by ctgarvey** [microsoft/vscode-docker#292] opened 2018-07-03 15:41 UTC
Ive reloaded the docker 0.0.27 plugin in visual studio code 1.24.1 (running on windows 10 1803 / 17134)
but its still not bringing the very useful linting  /colouring back to life. problem seems to be somewhere in here:
![image](https://user-images.githubusercontent.com/3577185/42230013-d0661052-7edf-11e8-96a4-c4357f48c005.png)

RUN stop-service MSSQL`$SQLEXPRESS ; `
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.SQLEXPRESS\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpdynamicports -value '' ; `
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.SQLEXPRESS\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpport -value 1433 ; `
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.SQLEXPRESS\mssqlserver\' -name LoginMode -value 2;

CMD .\start -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA -attach_dbs \"$env:attach_dbs\" -Verbose 

EXPOSE  1433 1434  3389  5985 5986
EXPOSE  1433/udp 1434/udp 5985/udp 5986/udp

**Comment by rcjsuen** [comment] 2018-07-03 16:38
@ctgarvey The syntax highlighting feature and the linting feature are two unrelated features and they do not depend on each other to work.

Are you seeing an invalid linting error that shouldn't be there because `docker build` will build the image? Or are you just seeing a problem with the colouring?

**Comment by ctgarvey** [comment] 2018-07-05 09:05
hi there, my bad . I am just seeing a problem with the colouring. Image builds fine.

**Comment by rcjsuen** [comment] 2018-07-05 09:39
Hi, @ctgarvey. Thank you for checking. From what I can see, your issue is another variation of #75.

**Comment by StephenWeatherford** [comment] 2018-07-13 21:22
@rcjsuen Do you want me to assign issues like this to you?  Thanks.

**Comment by rcjsuen** [comment] 2018-07-13 22:04
@StephenWeatherford I don’t think this is a linting issue. It looks like a colouring issue. Syntax highlight is not provided by the language server.

If you feel there is a linting issue here, please let me know but I do not currently feel there is anything for me to do here.

**Comment by StephenWeatherford** [comment] 2018-07-25 23:04
Related to https://github.com/Microsoft/vscode-docker/issues/245?

**Comment by StephenWeatherford** [comment] 2018-08-15 22:55
We need to enter an issue against Moby, then move to next milestone.

**Comment by PrashanthCorp** [comment] 2018-08-15 22:55
This needs to be fixed in vscode, at  the tmLanguage.json for docker. See [this comment](https://github.com/Microsoft/vscode-docker/issues/75#issuecomment-402463275)

**Comment by rcjsuen** [comment] 2019-10-18 21:06
Can someone please change the title of this issue so that it reflects that the problem is a syntax highlighting issue and not a linting issue? Thanks!

**Comment by StephenWeatherford** [comment] 2019-10-18 23:16
I've now got some experience with colorization, feel free to ask questions.  Might or might not be easy to fix.

**Comment by bwateratmsft** [comment] 2019-10-21 14:03
Based on @PrashanthCorp 's [comment](https://github.com/microsoft/vscode-docker/issues/292#issuecomment-409685704) it seems like this is a dupe of #75?

**Closed by bwateratmsft** 2019-10-21 14:03 UTC
Labels: P2, blocked, tracking
