### ISSUE TITLE
54

### ISSUE THREAD

**Issue by jnather** [microsoft/vscode-docker#1238] opened 2019-09-02 01:12 UTC
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint JC (1b7dd4679956cac6e585079e167294943d7b0861ec76fea63482ea2da90ec805): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500 

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404extension.bundle.js:157:579404
extension.bundle.js:157:579367extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment] 2019-09-03 13:40
Looks like dupe of #1241

**Closed by bwateratmsft** 2019-09-03 13:40 UTC
