### ISSUE TITLE
enable vscode-docker

### ISSUE THREAD

**Issue by guilhermerenew** [microsoft/vscode-docker#1324] opened 2019-10-07 15:14 UTC
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: string
Error Message: WARNING! Your password will be stored unencrypted in /home/pro_goliveira/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Version: 0.8.1
OS: linux
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

**Comment by bwateratmsft** [comment] 2019-10-07 15:20
Duplicate of #1296. @guilhermerenew , I would try configuring a credential helper as suggested by the error message.

**Closed** 2019-10-07 15:20 UTC
Labels: duplicate
