### ISSUE TITLE
There is no response when executing "Build Image..." command with Dockerfile in subfolder

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2393] opened 2020-10-13 09:18 UTC
**OS:** Windows 10
**Build Version:** 20201012.4

**Repro Steps:**
1. Create a new express app and put it into one folder "Test", the project folder as a subfolder
2. Open the folder "Test" in VS Code.
3. F1 -> Docker: Add Docker Files to Workspace... -> Node.js -> Select "expressappfolder\package.json" -> 3000 -> Include the Docker Compose files or not.
4. Right click Dockerfile and select "Build Image...".

**Expect:**
Succeed to build image.

**Actual:**
There is no response after selecting "Build Image..." for Dockerfile.

**More Info:**
1. Succeed to build image after deleting .vscode folder from "Test" folder.
2. This issue does not reproduce if open the project folder directly.

**Comment by bwateratmsft** [comment] 2020-10-13 13:45
I was not able to reproduce:
![image](https://user-images.githubusercontent.com/36966225/95868877-bd49eb80-0d38-11eb-958a-7555e1270f2b.png)

Can you try again and see if it still happens?

**Comment by bwateratmsft** [comment] 2020-10-13 15:00
I am able to reproduce on the latest Insiders build. I'm investigating now.

**Comment by bwateratmsft** [comment] 2020-10-13 15:06
@alexr00 it looks like something is happening within the task system in the latest Insiders build. This does not reproduce in 1.50.0. Our code successfully finds the task to execute, then calls `vscode.tasks.executeTask(task)`. Nothing seems to happen, but I see this in the Debug Console of the outer VSCode window (which is debugging our extension):

![image](https://user-images.githubusercontent.com/36966225/95879142-018eb900-0d44-11eb-9e8f-b7d1c8fbc353.png)

**Comment by bwateratmsft** [comment] 2020-10-13 15:13
@shivangg FYI, I saw that you recently added the feature which seems to be throwing the exception.

**Comment by bwateratmsft** [comment] 2020-10-13 15:39
I've found that if I change the setting `npm.packageManager` to `npm`, the issue no longer occurs; this must be a regression. I opened https://github.com/microsoft/vscode/issues/108610 for it.

**Comment by bwateratmsft** [comment] 2020-10-14 12:51
This is now fixed in today's Insider's build:
![image](https://user-images.githubusercontent.com/36966225/95991183-77555c00-0dfa-11eb-8c73-7d29ef88373a.png)

**Closed by bwateratmsft** 2020-10-14 12:51 UTC
Labels: AT-CTI, external, tracking
