### ISSUE TITLE
[Suggestion]Add "All images" option to delete all images 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#979] opened 2019-06-11 09:47 UTC
**OS**: All
**Build Version**:  [20190609.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6682)

**Repro Steps:**
1. Make sure all images are grouped by repository.
2. F1 --> Type and select "Docker Images: Remove...".
3. Check whether the all images can be deleted or not.

**Actual:**
There is no "All images" option.
![image](https://user-images.githubusercontent.com/34729092/59261939-e0f6b080-8c70-11e9-9bd6-01ffb28b887c.png)

**Suggestion:**
Add the "All images" option, or could we add the option to select all repositories?

**Comment by EricJizbaMSFT** [comment] 2019-06-11 16:03
Just so we're clear - you can already select all images _within a group_ by checking the top checkbox in your screenshot.

It sounds like you're asking us to give an option to delete all images regardless of grouping? I see the value in that, but it's already possible if the user changes their grouping to "None" before selecting the "Remove..." command.

> could we add the option to select all repositories?

Yeah we could definitely add an option to select multiple repositories. That would not be a simple task, though and like I mentioned there's already a workaround to delete all images. I'll leave this issue open for now and we can discuss in triage

**Comment by v-dantch** [comment] 2019-06-12 02:20
Yes, the original intension is that there is an option to delete all images regardless of grouping. 
And for now we will delete all images by changing their grouping to "None".

**Comment by bwateratmsft** [comment] 2020-02-25 20:25
We've added multi-select via #331 so I'll mark this one as a dupe of that.

**Closed by bwateratmsft** 2020-02-25 20:25 UTC
Labels: AT-CTI, enhancement
