### ISSUE TITLE
cannot access Docker Hub

### ISSUE THREAD

**Issue by embix** [microsoft/vscode-docker#965] opened 2019-06-04 07:14 UTC
Repro steps:

1. Go to Docker tab -> Registries -> Docker Hub ("Please log out of Docker Hub and then log in again.")
2. log out of docker
3. use `docker login` in powershell (successful)
4. refresh Docker tag -> Registries -> Docker Hub - still the same error

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.2
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.35.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser extension.bundle.js:1:644951
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-06-04 15:54
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/935 @embix you actually have to log out and log in through VS Code, not the docker cli. See the screenshot in that issue on how to log out. You should then see a node in the tree to log in. We hope to improve this soon

**Closed by EricJizbaMSFT** 2019-06-04 15:54 UTC

**Comment by embix** [comment] 2019-06-05 05:28
@EricJizbaMSFT I see. Thanks, it actually works.
