### ISSUE TITLE
 vscode-docker.images.prune

### ISSUE THREAD

**Issue by beatriz-evocorp** [microsoft/vscode-docker#1412] opened 2019-11-11 11:32 UTC
Repro steps:

1.
2.

Action: vscode-docker.images.prune
Error type: 409
Error Message: (HTTP code 409) unexpected - a prune operation is already running 

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098extension.bundle.js:157:703098
extension.bundle.js:157:703061extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by bwateratmsft** [comment] 2019-11-11 15:35
Dupe of #1395, will be mitigated by #1323.

**Closed by bwateratmsft** 2019-11-11 15:35 UTC
