### ISSUE TITLE
Failed to connect (Docker Desktop 4.12.0)

### ISSUE THREAD

**Issue by tonic-brian** [microsoft/vscode-docker#3627] opened 2022-09-29 19:17 UTC
Type: <b>Bug</b>

No longer able to connect to Docker Desktop with default settings (noticed in Docker Desktop 4.12.0)

Open Docker Extension UI --> 'Failed to connect. Is Docker running?'

Docker is running.

Extension version: 1.22.1
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by bwateratmsft** [comment] 2022-09-29 19:27
Is there any more information in the Output window for Docker, or the explorer view? Does it persist if you restart Docker Desktop and VSCode?

**Comment by tonic-brian** [comment] 2022-09-29 19:41
- Restarted 'Docker Desktop Service' 
- Restarted VSCode
- Uninstalled / Reinstalled 'Docker Extension'

Same results as before.  

The errors from the explorer are:

```
Failed to connect. Is Docker running?`
  Error: Process docker context Is --format="{{json .}}" exited with code  1
  Error: invalid character '\x00' looking for beginning of value
```

**Comment by bwateratmsft** [comment] 2022-09-29 19:44
Aha. Duplicate of #3249. There is an issue in Docker Desktop that leaves a file full of null characters on upgrade. The easiest solution is [here](https://github.com/microsoft/vscode-docker/issues/3249#issuecomment-937772119):

> The problem was a corrupt meta.json file, (full of null´s inside the file).
> 
> Quit Desktop Docker
> Delete %userprofile%\.docker
> Open Docker Destop

**Comment by tonic-brian** [comment] 2022-09-29 19:44
Thank you!

**Closed by bwateratmsft** 2022-09-29 19:44 UTC
Labels: info-needed
