### ISSUE TITLE
There are duplicate errors in the "Task" output panel when executing compose related action

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3653] opened 2022-10-18 11:13 UTC
**OS:** All
**Docker Extension Build Version:** 20221017.2
**Regression:** Not a Regression

**Repro Steps:**
1. Create and open a .NET MVC project in VS Code.
2. Add Docker files to this project (Linux Container) which include docker-compose files.
3. Right click docker-compose file and execute "Compose Up" action.
4. Navigate to "Task" output panel.
5. Check whether there is no error in the "Task" output panel.

**Expect:**
There is no error in the "Task" output panel.

**Actual:**
There are duplicate errors in the "Task" output panel.
![image](https://user-images.githubusercontent.com/45614674/196413439-a6eaf131-b79d-4630-a078-342b02585eb2.png)

**More Info:**
1. This issue also reproduces when executing "Compose Down" or "Compose Restart" actions.
2. This issue also reproduces on the previous released Docker extension.

**Comment by bwateratmsft** [comment] 2022-10-18 15:10
I am able to reproduce. It does not seem to affect the ability of the command to work, though.

**Comment by bwateratmsft** [comment] 2022-12-14 19:31
This is certainly external. We should open an issue in the VSCode repo.

**Comment by bwateratmsft** [comment] 2023-01-04 20:25
Looks like one exists: https://github.com/microsoft/vscode/issues/157756

**Comment by bwateratmsft** [comment] 2023-01-04 20:26
I'll close this one as external since we won't need to do anything to obtain the fix.

**Closed by bwateratmsft** 2023-01-04 20:26 UTC
Labels: AT-CTI, external, investigate
