### ISSUE TITLE
It takes more than 2 mins to open the web page when debugging Django project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#2563] opened 2020-12-11 10:44 UTC
**OS:** Windows 10
**Build Version:** 20201210.10

**Repro Steps:**
1. Open the django project in VS Code. 
2. F1 --> Click "Add Docker Files to Workspace..." --> Python: Django --> manage.py --> 8000.
3. Debug it.
4. Check whether the web page opens immediately or not.

**Expect:**
The web page opens immediately.

**Actual:**
It takes more than 2 mins to open the web page.

**Comment by karolz-ms** [comment] 2020-12-11 18:19
@v-xinda thank you, but we will need more detailed information about how you created the application, and how you configured Visual Studio Code for debugging (e.g. provide debug configuration that you were using).

Does the bug reproduce when you are running through the [Python containers tutorial](https://code.visualstudio.com/docs/containers/quickstart-python)? We need that level of detail.

Does the bug (long delay) happen when you try debugging for the second time?

Are you able to determine what is Visual Studio Code doing during the long delay? For example, can you check the output of the Docker extension and verify what it is doing? Is it downloading Python/Django container images and building the app container by any chance? That would explain a delay after a Python container app is run for the first time--subsequent runs should be much faster.

**Comment by v-ruizh** [comment] 2020-12-14 12:16
@karolz-ms We used "Docker: Python-Django" configuration to debug the project. 

This issue also reproduces when we are running the project which created through the [Python containers tutorial](https://code.visualstudio.com/docs/containers/quickstart-python). But it is unstable, it's easy to reproduce this issue after debugging more than twice. It can be reproduced 4 times when debugging 8 times.

The output logs of "Debug Console" shows as below when loading the web page.
Performing system checks...

```
System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
December 14, 2020 - 12:08:35
Django version 3.1.1, using settings 'helloworld.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
```
The Django container is running when loading the web page. Not sure the reason for the long delay.

You can try to debug the project multiple times if you can't reproduce it. We can provide our repro machine to you if you need.

**Comment by karolz-ms** [comment] 2020-12-14 19:39
@v-ruizh @v-xinda thanks for the clarification

I tried the scenario 20 times on my machine and experienced the delay only once. I was using the [Python containers tutorial](https://code.visualstudio.com/docs/containers/quickstart-python) with the breakpoint set in the startup code. The breakpoint was hit promptly every time, including the time when the delay happened--the delay happened **after continuing program execution**. The browser was correctly opened after the execution resumed (not before the breakpoint was hit, and not when execution was stopped on the breakpoint). I have not found anything in the Debug Console or Task output that would indicate a problem.

Based on the above it seems the Docker extension is doing everything correctly, and the issue is some sort of timing issue between the Python/Django container and the browser. I did a quick search through the issues related to general Python support in VS Code and through Django issues but I have not found anything relevant. ¯\_(ツ)_/¯

**Comment by karolz-ms** [comment] 2020-12-14 19:46
Seems we keep hitting these hard-to-reproduce, timing issues with Django regularly, it is quite frustrating: https://github.com/microsoft/vscode-docker/issues/2191 https://github.com/microsoft/vscode-docker/issues/2239 https://github.com/microsoft/vscode-docker/issues/2489

**Comment by dbreshears** [comment] 2020-12-15 19:02
This is external to Django/Python so closing

**Closed by dbreshears** 2020-12-15 19:02 UTC
Labels: AT-CTI, P3, external
