### ISSUE TITLE
isssue

### ISSUE THREAD

**Issue by Clemso7** [microsoft/vscode-docker#2999] opened 2021-06-12 03:20 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.buildImage
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.13.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.57.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1394608
extension.bundle.js:2:1382442extension.bundle.js:2:1382442
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by karolz-ms** [comment] 2021-06-14 16:51
Duplicate of #2347

**Closed by karolz-ms** 2021-06-14 16:51 UTC
