### ISSUE TITLE
Fail to deploy image to Azure App Service with Premium (P1v2) pricing tier

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3432] opened 2022-02-17 08:10 UTC
**OS:** M1
**Build Version:** 20220214.1

**Repro Steps:**

1. Open the myExpressApp project and add Docker files for this project in VS Code.
2. Right click Dockerfile -> Build Image.
3. Right click this image in the image view -> Push -> Azure -> Select a registry.
4. Right click the image in the registry view -> Deploy Image to Azure App Service with Premium (P1v2) pricing tier.
5. Check whether succeeds to deploy image to Azure App Service without any error.

**Expect:**
Succeed to deploy image to Azure App Service without any error.

**Actual:**
Fail to deploy image to Azure App Service with an error.
<img width="454" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/62053665/154431446-e085da56-47ed-4c4b-841e-318f8a1e39f6.png">

**More Info:**

1. This issue does not reproduce on Windows and Linux.
2. This issue also reproduces for other images.

**Comment by bwateratmsft** [comment] 2022-02-17 14:24
Basically the same as #1281. There is a maximum of 2 webhooks for basic tier ACRs and 10 for standard. We can't change the caps of course, but maybe can alter the messaging.

I'll resolve this as a dupe of #1281.

**Closed by bwateratmsft** 2022-02-17 14:24 UTC
Labels: AT-CTI
