### ISSUE TITLE
asking for docker logout

### ISSUE THREAD

**Issue by chetansurwade** [microsoft/vscode-docker#973] opened 2019-06-08 04:18 UTC
Repro steps:

1.
2.

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.2
OS: linux
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser extension.bundle.js:1:644951
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-06-10 16:18
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/935

We made improvements in this area on master - you're welcome to try it out with these instructions: https://aka.ms/azCodeInsiders

**Closed by EricJizbaMSFT** 2019-06-10 16:18 UTC
