### ISSUE TITLE
.vscode

### ISSUE THREAD

**Issue by Natanaelc7** [microsoft/vscode-docker#1960] opened 2020-05-09 03:11 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.installDocker
Error type: 1
Error Message: Process '"C:\Users\Naelson\AppData\Local\Temp\docker_158899...' exited with code 1
Error: Esta vers�o de C:\Users\Naelson\AppData\Local\Temp\docker_1588992443378_2736_1.exe n�o � compat�vel com a vers�o do Windows sendo executada. Verifique, nas informa��es do sistema do seu computador, se voc� precisa de uma vers�o x86 (32 bits) ou x64 (64 bits) do programa e contacte o fornecedor do software.

Version: 1.1.0
OS: win32
OS Release: 6.1.7601
Product: Visual Studio Code
Product Version: 1.45.0
Language: pt-br

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:477087
ChildProcess.emit events.js:203:13
ChildProcess.EventEmitter.emit domain.js:476:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment] 2020-05-11 13:50
Dupe of #1926.

**Closed by bwateratmsft** 2020-05-11 13:50 UTC
