### ISSUE TITLE
Fail to remove the Docker images with 2 duplicate confirmation dialogs

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2218] opened 2020-08-03 08:42 UTC
**OS:** Windows 10
**Build Version:** 20200731.1
**VS Code Insider:** 1.48.0-insider

**Repro Steps:**
1. Navigate to "Images view" --> Right click one image and select "Remove..." action.
2. Check the result.

**Expect:**
There is only one confirmation dialog and succeed to remove this image.
![image](https://user-images.githubusercontent.com/45614674/89163148-bd46a600-d5a7-11ea-9c4a-4c7db5425a92.png)

**Actual:**
There are 2 duplicate confirmation dialogs and fail to remove this image.
![image](https://user-images.githubusercontent.com/45614674/89163185-ca639500-d5a7-11ea-9f83-7c278afc786f.png)

**More Info:**
1. This issue does not reproduce if remove the image by command palette.
2. This issue also reproduces when removing containers from "Container view".
3. This issue does not reproduce in VS Code 1.47.3.

**Comment by karolz-ms** [comment] 2020-08-03 16:26
Likely a duplicate of https://github.com/microsoft/vscode/issues/103820

**Comment by karolz-ms** [comment] 2020-08-03 16:32
Something is seriously wrong with VS Code Insider 1.48.0; even commands like "File | Save As..." are executed twice... 🤔

**Closed by karolz-ms** 2020-08-03 16:32 UTC
Labels: AT-CTI, external
