### ISSUE TITLE
An error dialog pops up after running 'Copy Image Digest' for one running task run

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#1174] opened 2019-08-01 10:03 UTC
**OS**: All
**Build Version**: [20190731.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8312)

**Steps to reproduce:**
1. Command palette -> Docker Images: Run Azure CLI
2. Run these commands in the new terminal to set environment variables:
- ACR_NAME=`registry-name`
- GIT_USER=`github-username`
- GIT_PAT=`personal-access-token`
- az login
- az account set -s `your-subscription-name`
- az acr task create --registry $ACR_NAME --name taskhelloworld --image helloworld:{{.Run.ID}} --context https://github.com/$GIT_USER/acr-build-helloworld-node.git --branch master --file Dockerfile --git-access-token $GIT_PAT
3. Expand the build task named 'taskhelloworld' from the REGISTRIES window
4. Try to execute 'Run Task'.
5. Right click the running task run then click 'Copy Image Digest'.

**Expect Experience:**

There is no error and the image digest can be copied successfully.

**Actual Experience:**

An error dialog pops up.
![image](https://user-images.githubusercontent.com/34729022/62284494-494e5b00-b486-11e9-9045-2d0cddfa26d9.png)

**Comment by v-mengwe** [comment] 2020-07-15 07:38
Verified on the latest build 20200714.2, this issue still reproduces for now. I will continue to track this issue.

**Comment by bwateratmsft** [comment] 2020-07-15 14:24
This occurs because the task is still running, so an output image hasn't been obtained yet. We can add code to hide the "Copy image digest" command for incomplete task runs, similar to how we hide other commands depending container/image/etc. state.

**Comment by bwateratmsft** [comment] 2023-11-07 16:18
Closing as we've removed support for ACR tasks.

**Closed by bwateratmsft** 2023-11-07 16:18 UTC
Labels: AT-CTI, Azure/ACR
