### ISSUE TITLE
Issue connecting to private registry - Request with GET/HEAD method cannot have body.

### ISSUE THREAD

**Issue by chriseaton** [microsoft/vscode-docker#3646] opened 2022-10-14 18:01 UTC
Does this occur consistently? Yes
Repro steps:
1. Connect registry.
2. Choose Generic Docker Registry
3. Enter URI, user, and password.
4. Go to sidebar->Registries, expand registry, note the error "Request with GET/HEAD method cannot have body". Nothing else is displayed.

Action: AzureTreeDataProvider.getChildren
Error type: TypeError
Error Message: Request with GET/HEAD method cannot have body

Version: 1.22.1
OS: linux
OS Release: 4.18.0-372.26.1.el8_6.x86_64
Product: Visual Studio Code
Product Version: 1.72.0
Language: en

<details>
<summary>Call Stack</summary>

```
new Request extension.bundle.js:2:5742967
extension.bundle.js:2:5168778
extension.bundle.js:2:5168364
x extension.bundle.js:2:5168050
httpRequest extension.bundle.js:2:5168664
BasicOAuthProvider.<anonymous> extension.bundle.js:2:5098227
rejected extension.bundle.js:2:5097417
```

</details>

**Comment by bwateratmsft** [comment] 2022-10-14 19:06
Can you provide any more information about your registry? This sounds the same as #3449 / #3325; certain third-party registries have different expectations/requirements and it is impossible to support them all with a single generic provider.

**Comment by bwateratmsft** [comment] 2022-10-17 14:06
Likely a duplicate of #3449.

**Closed** 2022-11-01 05:46 UTC
Labels: info-needed
