### ISSUE TITLE
Docker extension does not find docker installed: Failed to connect. Is Docker installed? 

### ISSUE THREAD

**Issue by lopezvoliver** [microsoft/vscode-docker#3739] opened 2022-12-01 08:02 UTC
Docker extension does not find docker installed. 

Does this occur consistently? Yes
Repro steps:
1. I installed docker desktop (Docker version 20.10.21, build baeda1f) 
2. I opened a new vscode window and opened the Docker extension. Both "Images" and "Containers" show the error message `Failed to connect. Is Docker installed?`

3. I also tried adding the docker Path directly in the user settings. In my case, the path is:

`C:\Program Files\Docker\Docker\resources\bin\docker.exe`

4. Opening a terminal in vscode shows that the docker command is available. 
4.1 Using a git bash terminal:

```
$ which docker
/c/Program Files/Docker/Docker/resources/bin/docker
```

4.2 Using a powershell terminal:

```
Get-Command docker
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     docker.exe                                         0.0.0.0    C:\Program Files\Docker\Docker\resources\bin\docker.exe
```

Version: 1.23.1
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

**Comment by lopezvoliver** [comment] 2022-12-01 08:15
Rolling back to the extension version v1.22.2 solves the issue for me.

**Comment by bwateratmsft** [comment] 2022-12-01 14:26
@lopezvoliver does the issue persist if you restart Docker Desktop and VSCode? Is there any other error message or is it just the "not installed" message?

**Comment by lopezvoliver** [comment] 2022-12-01 14:34
Yes. I tried restarting Docker desktop and vscode, I also tried restarting the PC, and even uninstalling then installing docker again, as well as uninstalling and reinstalling the vscode docker extension. Yes, it was the only error message.

Finally, after installing the previous version of vscode docker extension mentioned above now it is working as expected.

**Comment by bwateratmsft** [comment] 2022-12-01 17:18
@lopezvoliver A couple of clarifying questions.

1. What do you see if you run this in a PowerShell or CMD terminal? This is the exact process we run to check if Docker is installed.
```sh
powershell.exe -c "docker -v"
```
2. Do you have a value for the setting `docker.dockerPath` in either workspace or user settings?

**Comment by dsgthb** [comment] 2022-12-03 10:14
@sebeyruv the extension rollback to v.1.22.2 solved the issue also for me. Thank you @lopezvoliver 

Docker version 20.10.21, build baeda1f

VS Code 1.73.1

Windows 10 Enterprise Version 22H2 Build 19045.225 Windows Feature Experience Pack 120.2212.4180.0

**Comment by lopezvoliver** [comment] 2022-12-04 06:02
> @lopezvoliver A couple of clarifying questions.
> 
> 1. What do you see if you run this in a PowerShell or CMD terminal? This is the exact process we run to check if Docker is installed (assuming default settings).
> 
> ```shell
> powershell.exe -c "docker -v"
> ```
> 
> 2. Do you have a value for the setting `docker.dockerPath` in either workspace or user settings?


1. If I type it exactly as shown above, I get an error about powershell.exe not recognized. If I type only the `docker -v` part, I get the version of docker installed:

```
PS C:\Users\lopezom> powershell.exe -c "docker -v"
powershell.exe : The term 'powershell.exe' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ powershell.exe -c "docker -v"
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (powershell.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\lopezom> docker -v
Docker version 20.10.21, build baeda1f
```

2. When I first encountered the `Failed to connect. Is Docker installed?` message, I didn't have anything set in `docker.dockerPath`. After setting it with the value `C:\Program Files\Docker\Docker\resources\bin\docker.exe` the issue still persisted.

**Comment by jhohlfeld** [comment] 2022-12-05 09:57
Same on Mac OS Monterey

* Docker Desktop 4.14.1
* Docker extension v1.23.1
* VSCode version 1.73.1

**Comment by bwateratmsft** [comment] 2022-12-05 14:59
@lopezvoliver That explains it; we use `powershell.exe` as the shell for all Docker processes on Windows currently. We originally tried `cmd.exe` but shell quoting was an absolute nightmare for it. Clearly PowerShell is installed--that terminal window _is_ a PowerShell window--but perhaps it's not on the `%PATH%` environment variable? What do you see from this command: `cmd /C "where powershell.exe"`

@jhohlfeld what do you see if you do `sh -c 'docker -v'` on the terminal?

**Comment by vucenovic** [comment] 2022-12-05 16:01
I have the same problem running a Linux machine.

**Comment by alanyu9857** [comment] 2022-12-06 06:58
> I have the same problem running a Linux machine.

same on mac

**Comment by TLaue** [comment] 2022-12-06 10:06
same on Mac for me

**Comment by NTpspE** [comment] 2022-12-07 08:24
I'm getting the same issue on MacOS as of this morning, in VSCode the Docker extension is saying "Failed to connect. Is Docker installed?" and prompting me to download the installer. 
Docker is definitely installed, and I can run my containers from the command line just fine, just can't see and manage them from the extension.

**Comment by bwateratmsft** [comment] 2022-12-07 14:25
@NTpspE what do you see if you run `sh -c 'docker -v'` in the terminal?

**Comment by NTpspE** [comment] 2022-12-07 14:26
Hi @bwateratmsft, I get "Docker version 20.10.21, build baeda1f"

**Comment by bwateratmsft** [comment] 2022-12-07 14:31
Ok, that's exactly the expected behavior. Are you able to [install the latest nightly build](https://github.com/microsoft/vscode-docker/issues/1408) of the Docker extension? We made some changes including not using a shell to execute most commands supporting the explorer; it's *possible* this fixes the issue, but we're not totally sure.

**Comment by lopezvoliver** [comment] 2022-12-08 06:40
> @lopezvoliver That explains it; we use `powershell.exe` as the shell for all Docker processes on Windows currently. We originally tried `cmd.exe` but shell quoting was an absolute nightmare for it. Clearly PowerShell is installed--that terminal window _is_ a PowerShell window--but perhaps it's not on the `%PATH%` environment variable? What do you see from this command: `cmd /C "where powershell.exe"`
> 
> @jhohlfeld what do you see if you do `sh -c 'docker -v'` on the terminal?

@bwateratmsft 
I edited my user Environment variables to add the path to PowerShell to `Path`, which in my case was `%SystemRoot%\System32\WindowsPowerShell\v1.0\` . After reloading vscode, I checked that `powershell.exe -c "docker -v"` now gives the expected result:

```
PS > powershell.exe -c "docker -v"
Docker version 20.10.21, build baeda1f
```

I then upgraded to vscode Docker extension 1.23.1, and can confirm that the issue is fixed.

**Comment by dsgthb** [comment] 2022-12-08 13:04
@bwateratmsft 
unfortunately in my case the problem persist. In the mainwhile I've also updated VS Code to the last version (**1.74**) as the tool suggested.

PoweShell path is already set in %PATH% (both on user and system environment variables).

output of _powershell.exe -c "docker -v"_ (from PowerShell terminal):
```
PS > powershell.exe -c "docker -v"
Docker version 20.10.21, build baeda1f
```

output of _cmd  /C "where powershell.exe"_ (from PowerShell terminal):
```
PS > cmd /C "where docker.exe"
C:\Program Files\Docker\Docker\resources\bin\docker.exe
```

Also for me when I first encountered the _Failed to connect. Is Docker installed?_ message, I didn't have anything set in **docker.dockerPath**. After setting it with the value _C:\Program Files\Docker\Docker\resources\bin\docker.exe_ the issue still persisted. If I revert to the v1.22.2 the value of the docker.dockerPath is simply _docker_ and the issue vanishes.


My system is **Windows 10 Enterprise Version 22H2 Build 19045.225 Windows Feature Experience Pack 120.2212.4180.0**

**Comment by justin6case** [comment] 2022-12-13 14:03
It's not working for me either on Centos 7

Docker extension v1.23.2
VSCode version 1.74.0
Docker version 17.06.0-ce, build 02c1d87

**Comment by bwateratmsft** [comment] 2022-12-14 15:32
I'm going to speculatively mark this as fixed by #3769. There are an enormous number of ways that we could misidentify Docker as not being installed, but executing without a shell at all should fix a lot of them. What remains will primarily center around completeness of the `PATH` environment variable--as long as Node can find `docker` in the `PATH` list, we _should_ correctly identify whether or not Docker is installed.

**Closed by bwateratmsft** 2022-12-14 15:32 UTC
Labels: investigate

**Comment by danegsta** [comment] 2022-12-19 19:36
This should hopefully be resolved by the 1.23.3 release, but if anyone is still running into the issue after updating, let us know and we'll re-open the bug.

**Comment by prkaaviya** [comment] 2023-01-26 18:14
I'm seeing this error on Ubuntu 20.04.5 LTS. I'm trying to access docker containers on a remote machine via SSH.

Docker extension shows the images of the containers but does not display the running containers. This is the error message displayed on the extension:
```
Failed to connect. Is Docker running?
Error:  Invalild container JSON
```
Docker extension - v1.23.3
VSCode version - 1.74.3
Docker version - 20.10.0, build 7287ab3

I'm also not able to run hello-world:
```bash
root@ip-10-0-0-198:~# docker run hello-world
docker: Error response from daemon: Exception handling request: 'DockerProxyRequestHandler' object has no attribute 'do_POST_containers_inspect'.
See 'docker run --help'.
```

**Comment by bwateratmsft** [comment] 2023-01-26 19:10
@prkaaviya can you share the output of this command?
`docker container ls --no-trunc --format "{{ json . }}"`

The inability to run the `hello-world` image wouldn't be related to the Docker extension.

**Comment by prkaaviya** [comment] 2023-01-27 04:24
I have received output of the command you have shared but I have truncated the full output (due to company poilicies). Like this 30+ more containers are all in running state, but not visible on the extension.
```bash
root@ip-10-0-0-198:~# docker container ls --no-trunc --format "{{ json . }}"
...
{"Command":"\"\"","CreatedAt":"2023-01-26 10:13:53 +0000 UTC","ID":"158e28ce-0f20-44c2-ac21-3f27b571394f","Image":"...","Labels":"","LocalVolumes":"0","Mounts":"","Names":"...","Networks":"","Ports":"","RunningFor":"18 hours ago","Size":"0B","State":"","Status":"Running"}
...
```

**Comment by prkaaviya** [comment] 2023-02-01 06:29
I checked, all the containers have the listed properties. The containers are created using helm charts.

**Comment by bwateratmsft** [comment] 2023-02-01 21:13
Do you mind trying out the instructions in [this comment](https://github.com/microsoft/vscode-docker/issues/3783#issuecomment-1407173476)? We have recently added some additional diagnostic info that is emitted to the Output window, it might help narrow down what's going wrong.

**Comment by bwateratmsft** [comment] 2023-02-01 21:14
@prkaaviya Do you mind trying out the instructions in [this comment](https://github.com/microsoft/vscode-docker/issues/3783#issuecomment-1407173476)? We have recently added some additional diagnostic info that is emitted to the Output window, it might help narrow down what's going wrong.

**Comment by prkaaviya** [comment] 2023-02-02 06:11
Here are some docker logs with the nightly extension:

```bash
2023-02-02 06:03:25.025 [debug] --- Docker Environment (0) ---
2023-02-02 06:03:25.025 [debug] docker.dockerPath: docker
2023-02-02 06:03:25.025 [debug] docker events --since 1675317803 --until 1675318103 --filter type=container --filter type=image --filter type=network --filter type=volume --filter event=create --filter event=destroy --filter event=die --filter event=kill --filter event=pause --filter event=rename --filter event=restart --filter event=start --filter event=stop --filter event=unpause --filter event=update --filter event=delete --filter event=import --filter event=load --filter event=pull --filter event=save --filter event=tag --filter event=untag --filter event=remove --filter event=prune --format {{json .}}
2023-02-02 06:03:25.025 [debug] docker container ls --all --no-trunc --format {{json .}}
2023-02-02 06:03:25.025 [debug] docker network ls --no-trunc --format {{json .}}
2023-02-02 06:03:25.025 [debug] docker image ls --no-trunc --format {{json .}}
2023-02-02 06:03:25.025 [debug] docker volume ls --format {{json .}}
2023-02-02 06:03:25.025 [error] Error response from daemon: Exception handling request: 'DockerProxyRequestHandler' object has no attribute 'do_GET_events_list'

2023-02-02 06:03:25.025 [error] Error response from daemon: Exception handling request: 'DockerProxyRequestHandler' object has no attribute 'do_GET_networks_list'

2023-02-02 06:03:25.025 [debug] docker events --since 1675318103 --until 1675318403 --filter type=container --filter type=image --filter type=network --filter type=volume --filter event=create --filter event=destroy --filter event=die --filter event=kill --filter event=pause --filter event=rename --filter event=restart --filter event=start --filter event=stop --filter event=unpause --filter event=update --filter event=delete --filter event=import --filter event=load --filter event=pull --filter event=save --filter event=tag --filter event=untag --filter event=remove --filter event=prune --format {{json .}}
2023-02-02 06:03:25.025 [debug] docker -v
2023-02-02 06:03:25.025 [error] Error response from daemon: Exception handling request: 'DockerProxyRequestHandler' object has no attribute 'do_GET_volumes_list'

2023-02-02 06:03:25.025 [error] Error response from daemon: Exception handling request: 'DockerProxyRequestHandler' object has no attribute 'do_GET_events_list'

2023-02-02 06:03:25.025 [debug] docker events --since 1675318403 --until 1675318703 --filter type=container --filter type=image --filter type=network --filter type=volume --filter event=create --filter event=destroy --filter event=die --filter event=kill --filter event=pause --filter event=rename --filter event=restart --filter event=start --filter event=stop --filter event=unpause --filter event=update --filter event=delete --filter event=import --filter event=load --filter event=pull --filter event=save --filter event=tag --filter event=untag --filter event=remove --filter event=prune --format {{json .}}
2023-02-02 06:03:25.025 [debug] Docker version 20.10.0, build 7287ab3

2023-02-02 06:03:25.025 [error] Error response from daemon: Exception handling request: 'DockerProxyRequestHandler' object has no attribute 'do_GET_events_list'

2023-02-02 06:03:25.025 [error] Failed to set up event listener: Error response from daemon: Exception handling request: 'DockerProxyRequestHandler' object has no attribute 'do_GET_events_list'
```

**Comment by bwateratmsft** [comment] 2023-02-02 16:57
@prkaaviya All those errors explain the inability to parse JSON. It seems like something is wrong with your install or your setup of Docker context, proxy, network, etc. There are a lot of possible causes; you're best off searching for those `DockerProxyRequestHandler` errors and seeing what comes up.
