### ISSUE TITLE
There is a warning after disconnecting the Docker Hub registry

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3515] opened 2022-05-09 11:23 UTC
**OS:** Win 10
**Docker Extension Build Version:** 20220506.1

**Repro Steps:**
1. Navigate to Docker registry view -> Connect Registry... -> Docker Hub -> Enter the Docker ID and password to connect.
2. Right click Docker Hub node and select "Disconnect".
3. Check whether there is no warning.

**Expect:**
There is no warning after disconnecting the Docker Hub registry.

**Actual:**
There is a warning after disconnecting the Docker Hub registry.
![image](https://user-images.githubusercontent.com/45614674/167399836-db39605d-bc11-47fc-981d-08e6f3db7c87.png)

**More Info:**
1. This issue does not reproduce on Mac(M1) and Linux.
2. This issue also reproduces on the previous released Docker extension 1.22.0.

**Comment by bwateratmsft** [comment] 2022-05-09 16:26
I created https://github.com/microsoft/vscode/issues/149104, this looks to be external. It does not occur in VSCode 1.66.2 so I assume it's a regression in 1.67.0.

**Comment by bwateratmsft** [comment] 2022-05-09 16:32
Closing since we won't need to do anything to pick up a fix.

**Closed by bwateratmsft** 2022-05-09 16:32 UTC
Labels: AT-CTI, external
