### ISSUE TITLE
Error: Should not be available through command palette

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-docker#870] opened 2019-03-28 18:25 UTC
Repro steps:
1. Create dockerfile
1. Build via ACR
1. Right-click tag, deploy to App Service

Action: vscode-docker.createWebApp
Error type: ERR_ASSERTION
Error Message: Should not be available through command palette

Version: 0.6.1
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
dist/extension.bundle.js:157:607095
Object.module.exports.t.activateInternal.l.callWithTelemetryAndErrorHandling.ue (dist/extension.bundle.js:157:607434)
Object.<anonymous> (dist/extension.bundle.js:157:602665)
Object.<anonymous> (dist/extension.bundle.js:211:110896)
Object.<anonymous> (dist/extension.bundle.js:1:392442)
Generator.next (<anonymous>)
module.exports.n (dist/extension.bundle.js:1:390815)
new Promise (<anonymous>)
module.exports.n (dist/extension.bundle.js:1:390592)
Object.module.exports.t.callWithTelemetryAndErrorHandling (dist/extension.bundle.js:1:392359)
Object.<anonymous> (dist/extension.bundle.js:211:110682)
Generator.next (<anonymous>)
module.exports.n (dist/extension.bundle.js:211:110348)
new Promise (<anonymous>)
module.exports.n (dist/extension.bundle.js:211:110125)
module.exports.t.registerCommand.o.ext.context.subscriptions.push.i.commands.registerCommand.o (dist/extension.bundle.js:211:110557)
d._executeContributedCommand (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:457:160)
d.$executeContributedCommand (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:457:534)
h._doInvokeHandler (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:593:118)
h._invokeHandler (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:592:777)
h._receiveRequest (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:591:436)
h._receiveOneMessage (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:590:279)
define.constructor._protocol.onMessage.e (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:588:565)
u.fire (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:43:254)
e (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:39:64)
u.fire (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:43:254)
s (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:168:754)
Socket.define.constructor._socketDataListener.e (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:168:960)
Socket.emit (events.js:182:13)
addChunk (_stream_readable.js:279:12)
readableAddChunk (_stream_readable.js:264:11)
Socket.Readable.push (_stream_readable.js:219:10)
Pipe.onread (net.js:636:20)
```

</details>

**Comment by fiveisprime** [comment] 2019-03-28 18:25
Worked the second time I clicked "deploy to app service"

**Comment by EricJizbaMSFT** [comment] 2019-06-04 17:07
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/551

**Closed by EricJizbaMSFT** 2019-06-04 17:07 UTC
