### ISSUE TITLE
suggestion: add "docker compose restart" command

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#250] opened 2018-04-18 01:03 UTC
I find as I'm working on a `Dockerfile` I tend to run the commands `docker-compose up` and `docker-compose down` quite a bit in sequence.  I run the container, see that something is wrong, make edits to the `Dockerfile` and then run down and up.  

Maybe a `docker compose: restart` command would be useful.

**Comment by PrashanthCorp** [comment] 2018-07-18 05:36
Is this a dupe of #73?

**Closed** 2018-07-20 19:05 UTC
Labels: P1
