### ISSUE TITLE
containers panel not working

### ISSUE THREAD

**Issue by edwardchenchen** [microsoft/vscode-docker#3731] opened 2022-11-29 23:43 UTC
plugin version 1.23
<img width="365" alt=" 2022-11-30 at 10 43 39" src="https://user-images.githubusercontent.com/6397192/204672794-65e5b5f7-ce06-4eeb-9412-a95ea77a2569.png">

`docker version`
```
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:00 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:20 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jur0slaw** [comment] 2022-11-30 02:39
Same thing happened to me.

**Comment by kuroh123** [comment] 2022-11-30 05:55
This issue is occurring in the latest version of docker extension. For a workaround, just right click on the docker extension and install the previous version.

**Comment by bwateratmsft** [comment] 2022-11-30 13:55
This is a duplicate of #3719. We plan to release a fix today.

**Closed by bwateratmsft** 2022-11-30 13:55 UTC
