### ISSUE TITLE
can't add docker files in wsl  

### ISSUE THREAD

**Issue by sewerganger** [microsoft/vscode-docker#1261] opened 2019-09-11 07:17 UTC
Repro steps:

1. can't add docker file in wsl 

Action: vscode-docker.configure
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open '\home\sewer\paste-any\docker-compose.yml'

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.openSync fs.js:436:3
Object.module.ELECTRON_ASAR.js:160:31
Object.writeFileSync fs.js:1168:35
extension.bundle.js:1:288233extension.bundle.js:1:288233
```

</details>

**Comment by bwateratmsft** [comment] 2019-09-11 14:59
@sewerganger Can you try [this](https://github.com/microsoft/vscode-docker/issues/1189#issuecomment-518724205) as a workaround? Closing as dupe of #954 and #960

**Closed by bwateratmsft** 2019-09-11 14:59 UTC
