### ISSUE TITLE
Mac OS Big Sur zsh:1: command not found: docker

### ISSUE THREAD

**Issue by gagocaan** [microsoft/vscode-docker#2574] opened 2020-12-21 23:58 UTC
When try to run a image from task bar the console output says

``` bash
zsh:1: command not found: docker
```

i can run the images from terminal without problems

**Comment by karolz-ms** [comment] 2020-12-22 01:03
I am sorry: https://github.com/microsoft/vscode-docker/issues/2509#issuecomment-740781160

Duplicate of https://github.com/microsoft/vscode-docker/issues/2254

**Closed by karolz-ms** 2020-12-22 01:03 UTC
Labels: duplicate
