### ISSUE TITLE
Unable to remove docker networks with name <none>

### ISSUE THREAD

**Issue by Nomiluks** [microsoft/vscode-docker#1499] opened 2019-12-17 10:31 UTC
Action: vscode-docker.networks.remove
Error type: 403
Error Message: (HTTP code 403) unexpected - none is a pre-defined network and cannot be removed 

Version: 0.9.0
OS: linux
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546
extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

**Comment by philliphoff** [comment] 2019-12-18 17:36
@Nomiluks Thanks for the report! We have a task to prevent users from attempting to remove a built-in Docker network, as it will always fail. I'll close this issue as a duplicate of #1383.

**Closed by philliphoff** 2019-12-18 17:36 UTC
