### ISSUE TITLE
 unexpected - OCI runtime create failed: container_linux.go

### ISSUE THREAD

**Issue by Cesarcuna** [microsoft/vscode-docker#1303] opened 2019-09-25 13:49 UTC
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 400
Error Message: (HTTP code 400) unexpected - OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/c/GitClone/articulate-0.29.0/articulate-0.29.0/local-storage/rasa/rasa-config.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/9f4e33366db7199d6132fd4bc6e3e8ed295db06b495460d2ec17a28dbfc2e4a3/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/9f4e33366db7199d6132fd4bc6e3e8ed295db06b495460d2ec17a28dbfc2e4a3/merged/app/config.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type 

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034extension.bundle.js:157:703034
extension.bundle.js:157:702997extension.bundle.js:157:702997
module.exports.m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
```

</details>

**Comment by bwateratmsft** [comment] 2019-09-25 13:58
This looks like a duplicate of #1301.

**Closed by bwateratmsft** 2019-09-25 13:58 UTC
