### ISSUE TITLE
Unable to disconnect the 'Connected Registries' which is used invalid URI

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#1183] opened 2019-08-05 10:10 UTC
**OS**: Windows
**Build Version:** [20190804.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8469)

**Steps to reproduce:**
1. Press F1 -> Select 'Connect Registry...'.
2. Select the provider 'Generic Docker Registry(Preview)'.
3. Use an empty URl and username for the registry -> Press 'Enter'.
4. Observe the 'Connect Registries' node.

**Expect Experience:**

1. It shows an error after expanding the 'Connect Registries' node.
2. Able to disconnect the 'Connected Registries' node.

**Actual Experience:**

1. It shows an error after expanding the 'Connect Registries' node.
2. Unable to disconnect the 'Connected Registries' node with the below error.
![image](https://user-images.githubusercontent.com/34729022/62456926-2d132c80-b7ac-11e9-8d1d-a176c734c2f6.png)

**Comment by EricJizbaMSFT** [comment] 2019-08-05 15:38
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/1155

**Closed by EricJizbaMSFT** 2019-08-05 15:38 UTC
Labels: ACR, AT-CTI
