### ISSUE TITLE
There is no data provider registered that can provide view data.

### ISSUE THREAD

**Issue by nickchomey** [microsoft/vscode-docker#4365] opened 2024-08-14 22:04 UTC
Suddenly the Docker extension is no longer working. This is what I see - the icon is blank and i get this error message

![image](https://github.com/user-attachments/assets/09ae6bde-86ab-4380-b554-05831819004c)

However, Docker itself works and I can see the containers, images etc. with the [Docker Explorer](https://marketplace.visualstudio.com/items?itemName=formulahendry.docker-explorer) extension.

![image](https://github.com/user-attachments/assets/ad5d33ef-89fd-4b12-a3ff-7a894d07341a)

WSL version: 2.3.17.0
VS Code Version 1.92.1
Docker Extension Version 1.29.2

![image](https://github.com/user-attachments/assets/24de0357-ce61-42fb-8e4a-59446ac4d615)

**Comment by danegsta** [comment] 2024-08-14 22:17
This looks like a duplicate of #4364; seems that VSCode failed to update your copy of the Docker extension correctly. Can you try uninstalling and re-installing to see if that unblocks you?

**Closed as completed** 2024-08-14 23:50 UTC
