### ISSUE TITLE
Pop up an error dialog when running 'ACR Tasks: Build Image' on Linux

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-docker#701] opened 2018-12-11 11:58 UTC
**OS:** Linux
**Node.js:** V10.14.1
**Extension Build:** 20181209.1

**Repro Steps:**
1.  Open the project [acr-build-helloworld-node](https://github.com/v-xianya/acr-build-helloworld-node?organization=v-xianya&organization=v-xianya) folder in vscode.
5. Right click on the Dockerfile then select 'ACR Tasks: Build Image'.

**Expect:**
The built image shows up in the tree.

**Actual:**
Pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/49798889-5e9f3980-fd7e-11e8-9ef3-340127a939ca.png)

**Comment by StephenWeatherford** [comment] 2018-12-11 20:48
Dupe of #666

**Closed by StephenWeatherford** 2018-12-11 20:48 UTC
Labels: CTI
