### ISSUE TITLE
There is an extra step "Select subscription" when pushing image to ACR with only one subscription selected

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4084] opened 2023-09-22 12:31 UTC
**OS:** Win 10
**Build Version:** 20230922.1
**Regression:** Previous Release

**Repro Steps:**
1. Connect Azure registry and make sure only one subscription is list.
2. Navigate to Image view -> Right click one image and select "Push..." action -> Select "Azure".
3. Check whether the next step is "Select registry" or not.

**Expect:**
The next step is "Select registry".

**Actual:**
The next step is "Select subscription".

**More Info:**
This issue does not reproduce on the current released Docker extension v1.26.1.

**Comment by alexyaang** [comment] 2023-09-22 13:15
This is expected behavior due to the new registry experience we created along with the registries revamp. I'll go ahead and close this one if it's okay with @bwateratmsft

**Comment by bwateratmsft** [comment] 2023-09-22 13:50
I'm OK with it. It's not a trivial amount of work to change but adds such a little burden to users.

**Comment by alexyaang** [comment] 2023-09-22 13:54
yeah i agree

**Comment by bwateratmsft** [comment] 2023-09-22 13:56
We'll close this since it's a fair bit of work to change but has little impact. If we hear from users that it's annoying we can revisit.

**Closed by bwateratmsft** 2023-09-22 13:56 UTC
Labels: AT-CTI, registries
