### ISSUE TITLE
Broken gitlab integration

### ISSUE THREAD

**Issue by Maracko** [microsoft/vscode-docker#2693] opened 2021-02-02 14:22 UTC
I use my gitlab registry inside this extension often, but couple of days ago it stopped working.

Now on the registry I get 401 unauthorized.

I have tried multiple accounts, changing password and using personal access token to login but nothing works.

![image](https://user-images.githubusercontent.com/56165587/106613330-5c098a80-656a-11eb-990c-372917bc4f8d.png)

**Comment by bwateratmsft** [comment] 2021-02-02 14:26
Dupe of #2688

**Closed by bwateratmsft** 2021-02-02 14:26 UTC
