### ISSUE TITLE
error integration Docker x Azure App Service via VSCode

### ISSUE THREAD

**Issue by felipevmbrandao** [microsoft/vscode-docker#2545] opened 2020-12-07 00:58 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.8.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:96513
extension.bundle.js:52:357954extension.bundle.js:52:357954
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by karolz-ms** [comment] 2020-12-07 16:46
This is a duplicate of https://github.com/microsoft/vscode-docker/issues/2347 @felipevmbrandao please follow the link in the error message to adjust your subscription configuration

**Closed by karolz-ms** 2020-12-07 16:46 UTC
Labels: duplicate
