### ISSUE TITLE
Wrong file association for Dockerfile.dockerignore files

### ISSUE THREAD

**Issue by puchm** [microsoft/vscode-docker#2946] opened 2021-05-16 00:23 UTC
Issue Type: <b>Bug</b>

Since Docker 19.03 it is possible to make Dockerfile-specific .dockerignore files using this format:
Dockerfile.dockerignore

"Dockerfile" can be replaced with anything here - it is just the name of the Dockerfile. Currently, if you are using a name like `Dockerfile.dockerignore` or `Dockerfile.dev.dockerignore` it uses the syntax highlighting for Dockerfiles. It should however treat it as a .dockerignore file.

These are the release notes: https://docs.docker.com/engine/release-notes/19.03/

### Temporary fix
Add this to your workspace config:
```
{
    "files.associations": {
        "*.dockerignore": "dockerignore"
    }
}
```

Extension version: 1.12.1
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.49GB free)|
|Process Argv|--crash-reporter-id b4a91c05-7a3c-41e2-b024-94fb17710872|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehovct:30301223
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by RA80533** [comment] 2021-07-02 02:28
This occurs for any file whose `basename` is Dockerfile: Dockerfile.md, Dockerfile.dockerignore (as noted in this issue), etc.

**Comment by karolz-ms** [comment] 2021-07-02 16:21
This is, essentially, a duplicate of #2128 That issue discussed in detail why all files with "Dockerfile" in the name are treated as Dockerfiles, regardless of the extension. Also see #1907 for additional context why we have this policy.

**Comment by puchm** [comment] 2021-07-02 16:42
I understand that `Dockerfile.*` files are treated as dockerfiles. However, wouldn't it be possible to also add a rule for `*.dockerignore` files?
I think the behaviour would stay the same, except if the file extension is `.dockerignore` which would override the original rule.

**Comment by karolz-ms** [comment] 2021-07-02 16:47
That's a valid point

**Comment by bwateratmsft** [comment] 2021-07-20 17:18
It's possible the languages section is order-sensitive, I'll try flipping the order and see if that works.

**Comment by bwateratmsft** [comment] 2021-07-20 20:02
I tried a variety of configurations but none of them were effective. I think that the workaround specified in @puchm's original comment is the way to go.

I still think the reasons for making `Dockerfile.*` be treated as a Dockerfile are valid. However, it doesn't seem possible to specify exclusions or an ordering.

**Closed by bwateratmsft** 2021-07-20 20:02 UTC
Labels: P2, investigate
