### ISSUE TITLE
Shell script is misidentified as a Dockerfile

### ISSUE THREAD

**Issue by rlipscombe** [microsoft/vscode-docker#3211] opened 2021-09-15 09:20 UTC
I've got a shell script that VS Code keeps misidentifying as a Dockerfile. If I set the file type to "Auto Detect", it's detected correctly as a shell script, but if I close and reopen the file, it gets treated as a Dockerfile again.

I've managed to cut it down to this:

```
#!/usr/bin/env bash

if [[ $tag =~ $tag_match_regex ]] ; then
    aws s3 cp \
            "s3://foo.bar.baz/the-server/$UBUNTU_CODENAME/the-first-thing_${VSN}_amd64.deb" \
            "$pending_bucket_base/the-server/$UBUNTU_CODENAME/" \
            --region $s3_region
    aws s3 cp \
            "s3://foo.bar.baz/the-server/$UBUNTU_CODENAME/another-thing_${VSN}_amd64.deb" \
            "$pending_bucket_base/the-server/$UBUNTU_CODENAME/" \
            --region $s3_region
    aws s3 cp \
            "s3://foo.bar.baz/the-server/$UBUNTU_CODENAME/third-thing_${VSN}_amd64.deb" \
            "$pending_bucket_base/the-server/$UBUNTU_CODENAME/" \
            --region $s3_region
fi
```

Create a new directory, open it in VS Code, put the above in a file called `not-a-dockerfile` and open the file.

**Comment by rcjsuen** [comment] 2021-09-15 11:31
@rlipscombe This looks like a duplicate of #3189 which is the same as https://github.com/microsoft/vscode/issues/132173.

From my own testing, the example you have provided is still broken on VS Code 1.60.1.

**Comment by bwateratmsft** [comment] 2021-09-15 13:42
I can reproduce but this is ultimately outside of the Docker extension's control. The AI classification system is incorrectly classifying the above as a Dockerfile.  If you manually set the language mode to "Shell Script", it will stop trying to classify it as a Dockerfile.

**Closed by bwateratmsft** 2021-09-15 13:42 UTC
