### ISSUE TITLE
Connect Registry Docker Hub fails with error message  "name org.freedesktop.secrets was not provided"

### ISSUE THREAD

**Issue by gsd1601** [microsoft/vscode-docker#3178] opened 2021-09-01 10:08 UTC
Q: Does this occur consistently? A: Yes. I tested a restart of VS Code 
Repro steps:
On a RPI4  ( triLinux rpi4pios64b01 5.10.52-v8+ #1441 SMP PREEMPT Tue Aug 3 18:14:03 BST 2021 aarch64 GNU/Linux
I 'm using  extension :ms-azuretools.vscode-docker
On Registries I seledt  Connect Registry  Docker Hub and see the form Sign in to Docker Hub (1/2) 
I can enter my name and then enter my password then I see.
Error Message: The name org.freedesktop.secrets was not provided by any .service files
![CodeDockerExtensionConnectionUI](https://user-images.githubusercontent.com/11822705/131652412-6f319233-d81c-40a1-bc64-760bc12a42a9.png)

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.16.0
OS: linux
OS Release: 5.10.52-v8+
Product: Visual Studio Code
Product Version: 1.59.1
Language: en
Remark: When trying the same with VSC on Windows 10 it works fine with my account[

**Comment by gsd1601** [comment] 2021-09-01 10:10
Trying to upload error message too.
![CodeDockerExtensionConnection](https://user-images.githubusercontent.com/11822705/131653580-78b17451-4e45-4b2d-8107-92ef3118681d.png)

**Comment by bwateratmsft** [comment] 2021-09-01 12:46
Duplicate of #2925. You'll need to install `gnome-keyring`.

**Closed by bwateratmsft** 2021-09-01 12:46 UTC

**Comment by gsd1601** [comment] 2021-09-03 09:30
Great! Installation of gnome-keyring solved the issue. 
Thank you
