### ISSUE TITLE
Won't connet

### ISSUE THREAD

**Issue by Markkbu** [microsoft/vscode-docker#3070] opened 2021-07-16 15:22 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.14.0
OS: linux
OS Release: 5.4.109-26094-g381754fbb430
Product: Visual Studio Code
Product Version: 1.58.1
Language: en

**Comment by karolz-ms** [comment] 2021-07-16 16:58
Most likely a duplicate of #2925. The workaround is to install `gnome-keyring` package.

**Closed by karolz-ms** 2021-07-16 16:58 UTC
