### ISSUE TITLE
AWS ECR docs

### ISSUE THREAD

**Issue by nick-youngblut** [microsoft/vscode-docker#3604] opened 2022-08-21 19:32 UTC
As a new user of vscode-docker, I've found it hard to figure out how to use vscode-docker with AWS ECR, which seems to be possible (e.g., https://github.com/microsoft/vscode-docker/issues/3202), but there doesn't seem to be much in regards to docs (besides [docker-push-ecr-image](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html), but that is CLI-based and not using the vscode-docker GUI features). 

More docs on using vscode-docker with AWS ECR would be appreciated.

**Comment by bwateratmsft** [comment] 2022-08-22 13:07
AWS has a custom auth mechanism that isn't supported by the Docker extension at this time, so I don't think it's currently possible to connect to ECR directly with the extension. I'll resolve this as a dupe of #869 and link this item in there.

**Closed by bwateratmsft** 2022-08-22 13:07 UTC
