### ISSUE TITLE
suggestion: option to reuse terminals

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-docker#251] opened 2018-04-18 01:04 UTC
There is no API to let me see if a terminal is in use, so whenever a command is run we spin up a new terminal.  This leads to a bunch of unused terminals to clean up.  

Suggest to investigate an option that reuses the same terminal, commands are effectively queued up.

**Comment by wsmelton** [comment] 2018-04-24 12:33
Might check [docker-explorer](https://github.com/formulahendry/vscode-docker-explorer) as they reuse terminal sessions in that extension. It seems like they pick up what the terminal is named and simply reference that to find the right terminal to use...but I don't claim to know how extensions are written 😀

**Comment by PrashanthCorp** [comment] 2018-07-27 21:00
Is this a dupe of #74 ?

**Comment by StephenWeatherford** [comment] 2018-09-12 22:31
Consider a flag as to whether or not to show a new terminal.  But it might depend on the command, e.g.:

Run Interactive
Run
Show Logs
Build

Might need more thinking.

**Comment by StephenWeatherford** [comment] 2018-09-12 22:31
Or experimenting

**Comment by bwateratmsft** [comment] 2019-09-16 18:43
Resolved by #1245

**Comment by EricJizbaMSFT** [comment] 2019-09-16 19:55
@bwateratmsft are you sure you closed the right issue here? This issue covers several features as mentioned above in Stephen's comment including compose, run, push image, pull image, view logs, etc. Basically anything that uses [this](https://github.com/microsoft/vscode-docker/blob/master/src/utils/TerminalProvider.ts#L11)

**Comment by bwateratmsft** [comment] 2019-09-16 19:57
Sorry, I was thinking about build which is resolved. But the rest would not be.

**Comment by bwateratmsft** [comment] 2019-09-25 15:56
Alex's suggestion was to create a Task object dynamically, and then execute it. This would result in terminals being re-used (most of the time), but for things like run-interactive, where a task _stays running_, the Task would automatically open a new terminal. Which is awesome!

**Comment by bwateratmsft** [comment] 2020-05-13 15:14
I think this will end up depending on #363

**Comment by bwateratmsft** [comment] 2020-05-14 18:51
Blocked on #1980.

**Closed** 2020-07-20 13:55 UTC
Labels: P2

**Comment by bwateratmsft** [comment] 2020-09-09 15:50
This has been fixed in Docker extension version 1.5.0.
