### ISSUE TITLE
Error start debugging

### ISSUE THREAD

**Issue by yusufkaratoprak** [microsoft/vscode-docker#997] opened 2019-06-17 09:24 UTC
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppProject extension.bundle.js:263:45299
```

</details>

**Comment by uthens** [comment] 2019-06-18 11:02
Same me...

Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

My project build run on visual studio 2017 and 2019 (windows), but can't build on vs code (mac)

**Comment by philliphoff** [comment] 2019-06-24 20:12
@yusufkaratoprak @uthens You can add the `appProject` or `appFolder` properties to your debug configuration like shown below.  Note that you need only specify `appProject` *or* `appFolder`, not both.

```
{
    "configurations": [
        {
            "name": "Docker: Launch .NET Core (Preview)",
            "type": "docker-coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "appProject": "${workspaceFolder}/project/project.csproj",
            "appFolder": "${workspaceFolder}/project"
            "dockerBuild": {
                // Image customizations
            },
            "dockerRun": {
                // Container customizations
            }
        }
    ]
}
```

If neither of those work, let me know and, please, provide any additional details about your project that you can (e.g.  the hierarchy of (project) files within the workspace).

**Comment by uthens** [comment] 2019-06-30 08:46
@philliphoff, Amazing it's worked on my mac, thanks you so much.
On the last week i spend more time for resolving on this problem.
I used time for resolved about 30 min, after i read on your comment! i can continue on my project. 👍 
  ```
{
            "name": "Docker: Launch .NET Core (Preview)",
            "type": "docker-coreclr",
            "request": "launch",
            "preLaunchTask": "build",
             "appProject": "${workspaceFolder}/src",
            "dockerBuild": {
                // Image customizations
                "dockerfile": "${workspaceFolder}/src/Dockerfile.sub.debug"
            },
            "dockerRun": {
                // Container customizations
            }
    }
```

**Comment by EricJizbaMSFT** [comment] 2019-07-25 16:39
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/1113

**Closed by EricJizbaMSFT** 2019-07-25 16:39 UTC
Labels: investigate, needs more info
