### ISSUE TITLE
Fail to debug the .NET Core project with an error "Could not find the task 'docker-run: debug'"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2518] opened 2020-11-23 09:13 UTC
**OS:** Win 10
**Build Version:** 20201114.1
**.NET Core:** 5.0.100

**Repro Steps:**
1. Create a .NET Core MVC/Console project and open it in VS Code insiders 1.52.0.
2. Add Docker files to workspace.
3. Change the configuration to "Docker .NET Core Launch".
4. F5.

**Expect:**
Debug the .NET Core project successfully.

**Actual:**
Fail to debug the .NET Core project with an error "Could not find the task 'docker-run: debug'".
![image](https://user-images.githubusercontent.com/45614674/99945023-d7063600-2dae-11eb-9dde-fd12b1474cd9.png)

**More Info:**
1. This issue also reproduces for .NET Core 3.1 projects.
2. This issue does not reproduce in VS Code 1.51.1.

**Comment by bwateratmsft** [comment] 2020-11-23 14:51
I'm able to reproduce on the latest Insiders build. @alexr00 is this a known issue?

**Comment by alexr00** [comment] 2020-11-23 16:13
A case of bugs on bugs. I updated a bit of old code that wasn't doing what it was intended to do with https://github.com/microsoft/vscode/commit/2720a8022e5f2f22a50ba036eeafd3cc9e7b6a3f, but after it did what it was intended to do (which was only relevant before I implemented `resolveTasks`), it broke cases where extensions don't provide any tasks in `provideTasks` but do use `resolveTask`.

Fixed by https://github.com/microsoft/vscode/commit/542de8a8d7c498cad8de76e94edb498cf36f3251

**Comment by bwateratmsft** [comment] 2020-11-30 14:54
Verified that this is now working in the latest Insiders. Thanks again @alexr00!

**Closed by bwateratmsft** 2020-11-30 14:54 UTC
Labels: AT-CTI, P1, external
