### ISSUE TITLE
DOCKER_HOST setting in v1.23.0+ not working correctly with Podman

### ISSUE THREAD

**Issue by McClunatic** [microsoft/vscode-docker#3766] opened 2022-12-12 18:16 UTC
I've been using the guidance in [this comment](https://github.com/microsoft/vscode-docker/issues/1590#issuecomment-769284759) to configure VS Code Docker to use Podman instead. It's worked perfectly! Unfortunately, the changes made in deprecating `docker.host` (see #3539) have led to issues.

Below is a screenshot of my Docker pane running v1.22.2.

![image](https://user-images.githubusercontent.com/11450013/207120518-8db2a0cd-1f50-4e24-b9ca-55061294ef8e.png)

If I upgrade to v1.23.0+, whether accepting the automatic migration of settings in the process or configuring them manually, I'm instead faced with the below.

![image](https://user-images.githubusercontent.com/11450013/207121572-3f925cd3-e282-4582-b235-5e59b05acfff.png)

Here's a shot of my environment settings in v1.23.2.

![image](https://user-images.githubusercontent.com/11450013/207121920-b0c15dfc-a827-40eb-8e9e-00e0256b1f5f.png)

If it's helpful, I did check for debugging information in the Docker Output tab, but it is empty after upgrading to v1.23.2 and configuring settings. When I revert back to v1.22.2, set `docker.host`, and visit the Docker pane, I can see the following in the Docker Output tab:

```
The Docker extension will try to connect to 'unix:///run/user/1000/podman/podman.sock', via context 'default'.
```

Please let me know if I can provide any more information to help investigate and resolve this! Thanks!

**Comment by bwateratmsft** [comment] 2022-12-12 18:20
This is a known issue. With 1.23.0, we began using the CLI exclusively for communicating with Docker, instead of a combination of the CLI and the HTTP API. While their respective HTTP APIs are nearly identical, the CLIs are more divergent, and Podman requires some more Podman-specific code that we haven't written yet. We're tracking that in #3241 (and I'll resolve this as a dupe of that).

The simplest workaround is going to be to roll back to Docker extension version 1.22.2. You can do so by running the command "Extensions: Install Specific Version of Extension..." in the command palette.

**Closed by bwateratmsft** 2022-12-12 18:20 UTC
