### ISSUE TITLE
Fail to push images to the private registry with an error 'no basic auth credentials'

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#963] opened 2019-06-03 09:22 UTC
**Extension build**: [20190602.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6463&view=logs)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create a development certificate authority -> Using the new CA certificate created to create a self-certificate for SSL.
2. Create a new registry container using the certificate.
3. Set "Http.proxyStrictSSL" as "true" in VS Code.
4. Right-click on Private Registers -> Connect to a private registry... -> Inputting the below 
URL: https://127.0.0.1:5443
Username: testuser
Password: testpassword
5. Right click https://127.0.0.1:5443 -> Set as Default Registry Path.
6. Tag any existing image -> Push the newly-tagged image to the registry.

**Expect Experience:**

The tagged image can be pushed successfully to the private registry.

**Actual Experience:**

Show the message 'no basic auth credenticals' on Terminal.
![image](https://user-images.githubusercontent.com/34729022/58790933-e9713a80-8623-11e9-84c0-5f9b84641af4.png)

**Comment by EricJizbaMSFT** [comment] 2019-06-10 21:18
Related to https://github.com/microsoft/vscode-docker/issues/351

**Comment by EricJizbaMSFT** [comment] 2019-07-03 21:23
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/351

**Closed by EricJizbaMSFT** 2019-07-03 21:23 UTC
Labels: AT-CTI
