### ISSUE TITLE
Add Google Cloud Products in list to Connect Registry.

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vscode-docker#2890] opened 2021-04-19 20:52 UTC
Products Google Cloud to be added to the list to Connect Registry:

- [ ] Container Registry of Google Cloud

- [ ] Artifact Registry of Google Cloud

- [ ] Cloud Run of Google Cloud (Apps deployed.)

- [ ] Cloud Build of Google Cloud (What was created.)

![simplescreenrecorder-2021-04-19_16 33 39](https://user-images.githubusercontent.com/38570195/115300440-f91d9d80-a12d-11eb-806b-b41e295be918.gif)

TO MSCODE: Cadastrar Google Cloud Registry in list to Connect Registry. https://i.imgur.com/PLqGxCd.png

**Comment by dbreshears** [comment] 2021-04-21 18:15
Duplicate of #869

**Closed by dbreshears** 2021-04-21 18:15 UTC
