### ISSUE TITLE
"Deploy Image To Azure App Service" Command Does Not Create Webhook In ACR

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-docker#190] opened 2017-12-13 18:41 UTC
Using the "Deploy Image to Azure App Service" command from VS Code does not create the "Continuous Deployment" webhook in ACR and puts the application in a state where it cannot pull changes from ACR.

To replicate...

* Create a simple Node application
* Create container with extension
* Deploy image to ACR
* Right-click image in extension and select "Deploy Image To Azure App Service"
* Application is deployed to a new Web App For Containers Instance
* Go to application in portal
* Go to Docker tab
* Notice that "Continuous Deployment" is already toggled on
* Go to ACR and look at "Webhooks"
* No webhook exists
* Turn "Continuous Deployment" off on app
* Turn it back on
* Portal reports that the image cannot be found

[VIdeo Of Issue](https://youtu.be/UXWLWimjWbE)

**Comment by johnpapa** [comment] 2017-12-14 18:18
In the portal we have to click the "CI" button in the app service blade. Perhaps we should just auto-add this to be enabled when using the vscode docker extension.

This will allow it to "just work" as expected.

Any reason we shouldnt?

**Comment by fiveisprime** [comment] 2017-12-14 19:43
I'm not sure that I'm following here. When I deploy to app service from docker, I see the CI option turned on and I see **no** webhooks; however, subsequent pushes of the image **do** update automatically.

Are you not seeing your changes get automatically picked up?
Also, what ACR SKU are you on?

**Comment by burkeholland** [comment] 2017-12-14 22:07
I'm on the premium ACR tier. I also see the option turned on automatically, but my application is not updated when I push an updated container (always with "latest" tag).

If no webhook is created, how would the image get pushed to AppService?

**Comment by fiveisprime** [comment] 2019-01-14 17:08
I think there have been some regressions based on API changes made to the platform over time. Right now, when you deploy to app service, the platform sees this as a private registry because it's simply creating app settings for host, username, and password rather than making a proper connection to ACR.

I believe the solution is to make a proper association with the ACR image to pick up all of the features.

**Comment by PrashanthCorp** [comment] 2019-02-15 22:35
I tried reproducing this bug. Here's what I found: 
1. Deploying the webapp - CD is turned on, and no webhook. 
2. Make a change, build the image, and push to ACR - the image is updated automatically but again, no webhook created. 
3. Toggle CD off and on, and webhook works. 
4. At the appservice container settings, change the image being pulled - no changes to the webhook. 

Is there any symptom I'm missing?

**Comment by burkeholland** [comment] 2019-02-19 13:45
That looks exactly like what I was experiencing

**Comment by johnpapa** [comment] 2019-02-19 13:48
This is exactly what I’ve experienced too.

**Comment by EricJizbaMSFT** [comment] 2019-08-08 20:51
@PrashanthCorp isn't this fixed in master? Can we close?

**Comment by fiveisprime** [comment] 2019-08-22 20:14
Appears to have been fixed in https://github.com/microsoft/vscode-docker/pull/1085

**Comment by PrashanthCorp** [comment] 2019-09-04 22:37
Closing as fixed.

**Closed by PrashanthCorp** 2019-09-04 22:37 UTC
Labels: P1
