### ISSUE TITLE
unable to connect to docker hub

### ISSUE THREAD

**Issue by Vityel** [microsoft/vscode-docker#3150] opened 2021-08-16 22:35 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.16.0
OS: linux
OS Release: 5.3.18-59.19-default
Product: Visual Studio Code
Product Version: 1.59.0
Language: ru

**Comment by bwateratmsft** [comment] 2021-08-17 13:38
Duplicate of #2925. @Vityel I'd recommend installing `gnome-keyring`.

**Closed by bwateratmsft** 2021-08-17 13:38 UTC
