### ISSUE TITLE
No multiple Docker attach shell anymore possible

### ISSUE THREAD

**Issue by lraphael** [microsoft/vscode-docker#3771] opened 2022-12-13 16:37 UTC
Type: <b>Bug</b>

It is now only possible to make one "Docker attach shell" per Docker container, not multiple ones.

- Attach Shell to one Container
- Try to repeat (No additional terminal opens)

Extension version: 1.23.2
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:37:54.581Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 5, 6|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 61c524cb-1280-480f-b48f-aac5b147b6e1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by bwateratmsft** [comment] 2022-12-13 16:42
Seems like this is a regression in VSCode. @meganrogge, we added these lines to force starting a new terminal each time certain tasks are run:
https://github.com/microsoft/vscode-docker/blob/3e6f5989018972fbb56471a4c39e573ed4549a78/src/runtimes/runners/TaskCommandRunnerFactory.ts#L54-L58

Have there been changes recently to how task IDs are computed?

**Comment by meganrogge** [comment] 2022-12-13 16:45
Yes, a regression with rerunning tasks https://github.com/microsoft/vscode/issues/168378 will be fixed in the recovery build today and has already been fixed in insider's

**Comment by lraphael** [comment] 2022-12-13 16:54
I just downloaded the latest version from the vscode insiders, but I can still reproduce it there. Is there a more recent version?

**Comment by meganrogge** [comment] 2022-12-13 17:08
Looked at the code you linked and don't think the issue I mentioned above is related. There haven't been other recent problems / changes with tasks that I can think of

**Comment by bwateratmsft** [comment] 2022-12-13 17:55
I'll try installing some older versions of VSCode to see if I can figure out when it appeared. We made some changes in this area in the Docker extension recently, but I tried an extension version from several months ago, before all these changes, and the same issue is present.

**Comment by bwateratmsft** [comment] 2022-12-13 19:26
@meganrogge it looks like it regressed in 1.74.0. I went back to 1.73.1 and it worked (with the current version of the Docker extension, 1.23.2).

**Comment by bwateratmsft** [comment] 2022-12-13 19:32
I found another issue that's _probably_ the same underlying cause. One of the items we execute as a task is `docker pull`; I tried pulling two images at the same time and it ignored the second request. In this case, even the task command line itself is different--and that still wasn't enough to generate a unique task.

**Comment by meganrogge** [comment] 2022-12-13 19:42
@bwateratmsft Can you reproduce it in insider's?

**Comment by bwateratmsft** [comment] 2022-12-13 19:43
Yes, the same issue is present in the latest Insider's build.

**Comment by bwateratmsft** [comment] 2022-12-14 21:52
There isn't a new Insider's build since yesterday (as of this morning) but I checked on the just-released recovery build and everything worked as expected. Thank you @meganrogge!

**Closed** 2022-12-14 21:52 UTC
Labels: fix released, external
