### ISSUE TITLE
Cannot connect to Docker Hub registry

### ISSUE THREAD

**Issue by sontseslav** [microsoft/vscode-docker#1257] opened 2019-09-09 11:58 UTC
Repro steps:
1. Click on "Select Registry"
2. Select "Docker Hub"
3. Type ID and press Enter
4. Type password and press Enter
Actual Result: an error
Expected Result: successfully connected to the registry

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

**Comment by bwateratmsft** [comment] 2019-09-09 13:31
Looks like a dupe of #1229

**Closed by bwateratmsft** 2019-09-09 13:31 UTC
