### ISSUE TITLE
An error occurs when selecting multiple files to open

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3775] opened 2022-12-15 10:29 UTC
**OS:** All
**Build Version:** 20221214.2

**Repro Steps:**
1. Run `docker run -dt redis:latest`.
2. Navigate to "Containers" view -> Expand the"redis:latest" container node ->Expand the "Files" node -> Expand the "etc" folder node.
3. Select multiple files, such as: `bash.bashrc`, `bindresvport.blacklist` and `debconf.conf `-> Click the open button next to `bash.bashrc` file..
4. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.

https://user-images.githubusercontent.com/57662131/207835883-bed875dc-880e-4240-9469-e40c1f920573.mov

**More Info:**
This issue doesn't reproduce when selecting one file to open.

**Comment by danegsta** [comment] 2022-12-16 19:00
I haven't been able to reproduce this particular bug yet, so it's likely some kind of timing issue; since file opening is generally working, this shouldn't block the 1.23.3 release.

**Comment by dbreshears** [comment] 2022-12-21 19:13
Closing since unable to reproduce.

**Closed by dbreshears** 2022-12-21 19:13 UTC
Labels: AT-CTI, not repro
