### ISSUE TITLE
Create and use `${packageName}:${packageVersion}` for Node.js image tag

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2013] opened 2020-05-26 01:49 UTC
This was reproduced on Windows 10 2004, WSL2 Docker Desktop 2.3.0.0, Docker extension version 1.2.0, VS Code version 1.45.1

Repro steps:
1. Create a simple Node.js app
2. Scaffold Docker files using VS Code Docker extension
3. Ensure that package.json has both `name` and `version` properties set (e.g. `guestbook-express` and `1.0.0`, respectively).
4. Run `docker-build` task

Expected: the resulting image should be tagged as `guestbook-express:1.0.0`--at least that was the intent of the design https://code.visualstudio.com/docs/containers/reference#_nodejs-dockerbuild
Actual: the resulting image is tagged as `guestbookexpress:latest` (note wrong tag and removed hyphen in the name).

Further problem:
5. Open `tasks.json` and set `dockerBuild.tag` property to `guestbook-express:1.0.0`
6. Run `docker-build` task again

Expected: the resulting image should be tagged as the task parameters say it should
Actual: nope, it is still `guestbookexpress:latest` 😠

**Comment by bwateratmsft** [comment] 2020-05-26 13:49
@karolz-ms For now at least it's intentional that we do not use package.json's name/version though that's a reasonable change we could make. The most appropriate way to do it would be variable substitution, e.g.
```json
"dockerBuild": {
    "tag": "${packageName}:${packageVersion}"
}
```

I was not able to reproduce second issue:
![image](https://user-images.githubusercontent.com/36966225/82908357-d8f15880-9f35-11ea-82ba-d48bcd21bd05.png)
![image](https://user-images.githubusercontent.com/36966225/82908385-e4dd1a80-9f35-11ea-84be-3d2f9e28b407.png)
![image](https://user-images.githubusercontent.com/36966225/82908414-eeff1900-9f35-11ea-85be-97077262fa9b.png)

**Comment by karolz-ms** [comment] 2020-05-26 23:09
The "further problem" (steps 5 and 6) are a dup of https://github.com/microsoft/vscode/issues/98617

**Comment by karolz-ms** [comment] 2020-05-26 23:11
@bwateratmsft your proposal sounds very good to me

**Comment by bwateratmsft** [comment] 2020-05-27 13:32
@karolz-ms Ok, I'll change the title to reflect what this bug is now about. :smile:

**Comment by dbreshears** [comment] 2024-10-16 18:56
Closing as we don't have plans for this

**Closed by dbreshears** 2024-10-16 18:56 UTC
Labels: enhancement, wontfix, P2, Node/JS
