### ISSUE TITLE
Remove container (in progress)

### ISSUE THREAD

**Issue by baniou** [microsoft/vscode-docker#1477] opened 2019-12-09 23:02 UTC
Repro steps:

1.
2.

Action: vscode-docker.containers.remove
Error type: 409
Error Message: (HTTP code 409) unexpected - removal of container 2a1494813fc76bc4c0b31d058278d4b57dce7e546e6d720363bfbaabbc89bf4d is already in progress 

Version: 0.9.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546
extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment] 2019-12-09 23:55
Closing as a dupe of #1323 (where some long-running Docker tasks do not indicate their progress leading users to invoke them again, which then fail.)

**Closed by philliphoff** 2019-12-09 23:55 UTC
