### ISSUE TITLE
On a Mac, the extension keeps timing out when using Podman instead of Docker

### ISSUE THREAD

**Issue by benatshippabo** [microsoft/vscode-docker#3367] opened 2022-01-05 18:31 UTC
## Steps to reproduce

```sh
# based on this blog post https://www.redhat.com/sysadmin/podman-mac-machine-architecture
brew install podman
pip3 install podman-compose
podman machine init
podman machine start

# to get the ssh path
podman system connection ls
```

Then set the vscode config to use Podman:

```json
{
  "docker.dockerPath": "podman",
  "docker.host": "ssh://core@localhost:50261"
}
```

Afterwards, go to the Docker extension and see the following:
![image](https://user-images.githubusercontent.com/66273043/148268302-2a8e217b-0116-4fd9-a3db-b5ff49800211.png)

## Expected outcome
After configuring the Docker extension, the user should see the list of created containers.

## Context
cross posted here as well https://github.com/containers/podman/discussions/12745#discussion-3780300

**Comment by bwateratmsft** [comment] 2022-01-05 18:56
@benatshippabo do you have an SSH agent set up? Our explorer uses the `dockerode` NPM package, which in turn uses `ssh2`, which unfortunately _requires_ an SSH agent--it is not able to pick up anything from `~/.ssh`, unlike the Docker CLI (and presumably the Podman CLI too). I've noticed in the past that `ssh2` throws a timeout error when it tries and fails to connect to an SSH agent.

More info about setting up an SSH agent here: https://code.visualstudio.com/docs/containers/ssh

**Comment by benatshippabo** [comment] 2022-01-05 19:25
> @benatshippabo do you have an SSH agent set up? Our explorer uses the `dockerode` NPM package, which in turn uses `ssh2`, which unfortunately _requires_ an SSH agent--it is not able to pick up anything from `~/.ssh`, unlike the Docker CLI (and presumably the Podman CLI too). I've noticed in the past that `ssh2` throws a timeout error when it tries and fails to connect to an SSH agent.
> 
> More info about setting up an SSH agent here: https://code.visualstudio.com/docs/containers/ssh

@bwateratmsft  Thanks for the swift reply, I think we are getting somewhere. After adding the ssh private key using:
```sh
ssh-add ~/.ssh/podman-machine-default
```

The error message has now progressed to:
![image](https://user-images.githubusercontent.com/66273043/148276685-5b862326-36f3-49cb-ab72-9ffc356faf0b.png)

**Comment by bwateratmsft** [comment] 2022-01-06 14:57
That looks promising! Is a value present in VSCode for environment variable `SSH_AUTH_SOCK`?

**Comment by benatshippabo** [comment] 2022-01-06 17:14
> That looks promising! Is a value present in VSCode for environment variable `SSH_AUTH_SOCK`?

@bwateratmsft yep, it is set to:

```
❯ echo $SSH_AUTH_SOCK
/private/tmp/com.apple.launchd.KLlERFdN3t/Listeners
```

**Comment by bwateratmsft** [comment] 2022-01-06 17:54
Can you try that value of `dockerodeOptions`' `socketPath` as `docker.host`? I wonder if that works.

**Comment by benatshippabo** [comment] 2022-01-06 17:58
> Can you try that value of `dockerodeOptions`' `socketPath` as `docker.host`? I wonder if that works.

It leads to the same socket hang up error, maybe it's how the socket path is concatenated?

**Comment by bwateratmsft** [comment] 2022-01-06 18:05
Hmm...I wonder if the SSH is actually necessary. Does `unix:///run/user/1000/podman/podman.sock` work for `docker.host`?

**Comment by benatshippabo** [comment] 2022-01-06 18:16
> unix:///run/user/1000/podman/podman.sock

That would be a negative. My understanding is that on a Mac, Podman creates a linux vm to run the containers on and their cli currently interacts through ssh only. Although it seems like they are working on it.

Btw, I added comment [here](https://github.com/containers/podman/discussions/12745#discussioncomment-1920094) so we can figure out how to resolve the `context` command not being available.

**Comment by bwateratmsft** [comment] 2022-01-06 18:22
Rats. Seems like this is yet one more thing that would be solved by #3263. I'll mark this as investigate but it may be pretty similar/the same as #3241, and also maybe just solved by #3263.

**Comment by bwateratmsft** [comment] 2022-01-06 18:26
I had another thought, what happens if you set _all_ of the following settings?
```json
  "docker.dockerPath": "podman",
  "docker.host": "ssh://core@localhost:50261"
  "docker.dockerodeOptions": {
    "socketPath": "ssh://core@localhost:50685/run/user/1000/podman/podman.sock"
  }
```

I don't know for sure without trying it, but I think it might cause the logic that is running `podman context ls ...` to be skipped.

**Comment by benatshippabo** [comment] 2022-01-06 18:32
> I had another thought, what happens if you set _all_ of the following settings?
> 
> I don't know for sure without trying it, but I think it might cause the logic that is running `podman context ls ...` to be skipped.

Hmm, that gave a message we haven't seen yet:
![image](https://user-images.githubusercontent.com/66273043/148432881-eefec3b0-9d8d-413c-a674-83ce2571cedb.png)

**Comment by bwateratmsft** [comment] 2022-01-06 18:33
Is that port of `50685` still accurate? Do both `docker.host` and `docker.dockerodeOptions` have the current port?

**Comment by benatshippabo** [comment] 2022-01-06 18:36
> Is that port of `50685` still accurate? Do both `docker.host` and `docker.dockerodeOptions` have the current port?

Yup they are still accurate:

```json
{
  "docker.dockerPath": "podman",
  "docker.host": "ssh://core@localhost:50685",
  "docker.explorerRefreshInterval": 5000,
  "docker.dockerodeOptions": {
    "socketPath": "ssh://core@localhost:50685/run/user/1000/podman/podman.sock"
  }
}
```

```
❯ podman system connection ls
Name                         Identity                                 URI
podman-machine-default*      /Users/btea/.ssh/podman-machine-default  ssh://core@localhost:50685/run/user/1000/podman/podman.sock
podman-machine-default-root  /Users/btea/.ssh/podman-machine-default  ssh://root@localhost:50685/run/podman/podman.sock
```

**Comment by bwateratmsft** [comment] 2022-01-06 18:40
Hm. I am stumped. Setting `docker.host` in addition to `docker.dockerodeOptions` did indeed skip that `podman context ls ...` logic but I am not sure what would cause the `ENOENT` error. I think that suggests a successful connection to `ssh://core@localhost:50685` but `/run/user/1000/podman/podman.sock` was not found or not accessible. It's not ideal but can you try using root, with `ssh://root@localhost:50685/run/podman/podman.sock`, to see if that works?

**Comment by benatshippabo** [comment] 2022-01-06 18:45
> 

Yeah, same error even when trying to connect as root user. 😞

**Comment by bwateratmsft** [comment] 2022-01-19 18:09
@benatshippabo to make sure I set up a realistic repro, does your Mac have an Intel processor or the newer M1 (aka Apple Silicon)?

**Comment by benatshippabo** [comment] 2022-01-19 19:26
> @benatshippabo to make sure I set up a realistic repro, does your Mac have an Intel processor or the newer M1 (aka Apple Silicon)?

It is on the M1 processor. Thanks @bwateratmsft

**Comment by bwateratmsft** [comment] 2022-01-19 19:35
@philliphoff do you mind trying out the scenario on your M1? I'll try it out on my Intel Macbook and see how it goes.

**Comment by philliphoff** [comment] 2022-01-19 20:26
This is as far as I get with my M1 (the ENOENT error), and is the same whether I specifically set `docker.host` or not.

<img width="885" alt="Screenshot 2022-01-19 at 12 25 44" src="https://user-images.githubusercontent.com/6402946/150208295-26da0dd6-dd1f-4b98-8257-30964686a2d7.png">

**Comment by bwateratmsft** [comment] 2022-01-20 18:10
I've spent some time today looking into this. It seems things are going sideways in `docker-modem`. It successfully establishes a connection to the SSH host, whereupon it runs `docker system dial-stdio` in order to communicate with Docker on the host over ordinary HTTP tunneled through the SSH connection. Naturally, this is not going to work for Podman, since it's literally running a `docker` command.

`dockerode` / `docker-modem` accept a custom `agent` object which could probably be coerced into making it work, but it wouldn't be possible to use this with the Docker extension, because only JSON objects can be fed to `docker.dockerodeOptions`.

@benatshippabo bad news and good news. The bad news is that I don't think there's currently any way to make this work. The good news is that #3263 ought to solve this and we're hoping to get it in our next release. For now, I'll resolve this one as a dupe of that.

**Closed by bwateratmsft** 2022-01-20 18:10 UTC
Labels: investigate

**Comment by benatshippabo** [comment] 2022-01-20 18:59
> I was able to get the same results on my Intel Mac.
> 
> I've spent some time today looking into this. It seems things are going sideways in `docker-modem`. It successfully establishes a connection to the SSH host, whereupon it runs `docker system dial-stdio` in order to communicate with Docker on the host over ordinary HTTP tunneled through the SSH connection. Naturally, this is not going to work for Podman, since it's literally running a `docker` command.
> 
> `dockerode` / `docker-modem` accept a custom `agent` object which could probably be coerced into making it work, but it wouldn't be possible to use this with the Docker extension, because only JSON objects can be fed to `docker.dockerodeOptions`.
> 
> @benatshippabo bad news and good news. The bad news is that I don't think there's currently any way to make this work. The good news is that #3263 ought to solve this and we're hoping to get it in our next release. For now, I'll resolve this one as a dupe of that.

Yeah that makes sense to me. Thanks for keeping me posted @bwateratmsft
