### ISSUE TITLE
Fail to execute docker commands after connecting to remote machine via SSH

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2945] opened 2021-05-15 13:26 UTC
**OS:** Windows
**Build Version:** 20210513.4

**Repro Steps:**
1. Create an Ubuntu 18.04 LTS machine with SSH access--as a remote machine.
2. Install Docker in this Linux machine.
3. In local machine, install Remote-SSH extension in VS Code local instance.
4. Connect to the remote Ubuntu machine via SSH in VS Code.
5. Navigate to Docker view and right click one Docker image to pull.
6. Check whether pull the docker image successfully or not.

**Expect:**
Pull docker image successfully.

**Actual:**
Fail to pull docker image with an error.
![image](https://user-images.githubusercontent.com/45614674/118362808-c303fa00-b5c3-11eb-8768-e5713976b90e.png)

**More Info:**
This bug also reproduces when executing other docker commands, such as push/run...

**Comment by MicePilot** [comment] 2021-05-17 02:23
I have similar problems
![image](https://user-images.githubusercontent.com/13869645/118424456-e0d37b00-b6f9-11eb-91ef-367529a6e7a1.png)

**Comment by karolz-ms** [comment] 2021-06-09 16:53
Seems external to VS Code extension. I have opened https://github.com/microsoft/vscode-remote-release/issues/5157 for the Remote-SSH devs to investigate.

**Comment by karolz-ms** [comment] 2021-06-14 21:17
The issue seems to be fixed in VS Code 1.57.0 release. Please re-open if it reproduces again, but at this moment looks like we are back in business.

**Closed by karolz-ms** 2021-06-14 21:17 UTC
Labels: AT-CTI, bug, external
