### ISSUE TITLE
tried to remove dangling images

### ISSUE THREAD

**Issue by nbcmguarin0** [microsoft/vscode-docker#1468] opened 2019-12-05 21:39 UTC
Repro steps:

1.
2.

Action: vscode-docker.images.prune
Error type: 409
Error Message: (HTTP code 409) unexpected - a prune operation is already running 

Version: 0.9.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546
extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment] 2019-12-05 23:11
This is likely a duplicate of #1323.

**Closed by philliphoff** 2019-12-05 23:11 UTC
