### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cristianholz** [microsoft/vscode-docker#1504] opened 2019-12-23 18:12 UTC
Repro steps:

1.
2.

Action: vscode-docker.networks.create
Error type: 404
Error Message: (HTTP code 404) driver not found - could not find plugin host in v1 plugin registry: plugin not found 

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546extension.bundle.js:324:440546
extension.bundle.js:324:440508extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
IncomingMessage.EventEmitter.emit domain.js:471:20
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by ravipal** [comment] 2019-12-26 20:27
Dupe of #1444

**Closed by ravipal** 2019-12-26 20:27 UTC
Labels: duplicate
