### ISSUE TITLE
докер

### ISSUE THREAD

**Issue by irinazheltisheva** [microsoft/vscode-docker#2352] opened 2020-09-28 13:28 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 1.6.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.2
Language: ru

<details>
<summary>Call Stack</summary>

```
DockerNetCoreDebugConfigurationProvider.resolveDockerDebugConfiguration extension.bundle.js:1276:115167
extension.bundle.js:1276:115074extension.bundle.js:1276:115074
Object.<anonymous> extension.bundle.js:33:983874
extension.bundle.js:33:983065extension.bundle.js:33:983065
o extension.bundle.js:33:982751
Object.callWithTelemetryAndErrorHandling extension.bundle.js:33:983782
DockerNetCoreDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:1276:115005
extensionHostProcess.js:934:493extensionHostProcess.js:934:493
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by bwateratmsft** [comment] 2020-09-28 15:16
Dupe of #1451

**Closed by bwateratmsft** 2020-09-28 15:16 UTC
