### ISSUE TITLE
Impossible to connect to hub.docker.com registry from VSCode @ RPi

### ISSUE THREAD

**Issue by PeterHric** [microsoft/vscode-docker#2982] opened 2021-06-01 13:29 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.13.0
OS: linux  Raspbian 10.x
OS Release: 5.10.17-v7l+
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

**Comment by karolz-ms** [comment] 2021-06-01 17:39
Duplicate of https://github.com/microsoft/vscode-docker/issues/2925

**Closed by karolz-ms** 2021-06-01 17:39 UTC
Labels: duplicate
