### ISSUE TITLE
An error "timeout after 1000 ms" occurs after stopping debugging a Python project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2202] opened 2020-07-28 08:32 UTC
**OS:** Win 10
**Build Version:** 20200724.4

**Repro Steps:**
1. Open a Python Django/Flask project and add Docker support for it in VS Code insider.
2. F5 --> Wait for navigating to the Terminal window "Python Debug Console" during debugging --> Stop debugging.
3. Check the result.

**Expect:**
There is no error after stopping debugging.

**Actual:**
An error "timeout after 1000 ms" occurs after stopping debugging.
![image](https://user-images.githubusercontent.com/45614674/88639508-72ccb180-d0ef-11ea-8aa2-5f1aa6ea0bf4.png)

**Comment by bwateratmsft** [comment] 2020-07-28 12:11
This is coming from the Python extension.

**Comment by bwateratmsft** [comment] 2020-07-28 13:12
I was able to reproduce this a few times. I think I know what is happening. Python's debug model is to start a "server" session on the local machine and a "client" session within the container. The "server" session is started and waits for the "client" session to connect back to it.

The client session takes up to a few seconds to make that connection (this is that `docker exec ... debugpy ...` call). If you click "Stop" during this time period, the server session tries to send the stop message to the client, but fails because the client hasn't connected yet. The error pops up. The server then "gives up" on sending that message, but the debug session then stops. Because the session stops, our code to remove the container activates, and the container is removed, so the client session is cleaned up.

I don't think there is really anything we can do about this issue, but fortunately the negative effects it would have had are mitigated by our container removal. The only negative effect is the error toast. For now I'll close this issue, but if we get some user reports maybe we can look at fixes within VSCode or debugpy.

**Closed by bwateratmsft** 2020-07-28 13:12 UTC
Labels: AT-CTI, Python Debug
