### ISSUE TITLE
Unable to add new context through the extension (no shortcut and/or icon)

### ISSUE THREAD

**Issue by western-hoolock** [microsoft/vscode-docker#4075] opened 2023-09-18 13:01 UTC
Version 1.26.0 installed on Windows.

Is there a way to add a new docker context through the extension? Currently I can not find any shortcut or + icon (as there is for the Network for example). Right now I have to invoke `docker context create ...` myself in a terminal in order to add a new context, the extension recognizes contexts added that way just fine but I feel like there should be a way to do it through the extension?

**Comment by bwateratmsft** [comment] 2023-09-20 18:17
I'm going to resolve this as a dupe of #2115, and slightly adjust the title of 2115 as well.

**Closed by bwateratmsft** 2023-09-20 18:17 UTC
Labels: feature
