### ISSUE TITLE
I can not run this code what is the proplem ?

### ISSUE THREAD

**Issue by 775705m** [microsoft/vscode-docker#2505] opened 2020-11-19 19:46 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 1.4.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerNetCoreDebugConfigurationProvider.resolveDockerDebugConfiguration extension.bundle.js:578:847643
extension.bundle.js:578:847550extension.bundle.js:578:847550
Object.<anonymous> extension.bundle.js:3:495519
extension.bundle.js:3:494710extension.bundle.js:3:494710
o extension.bundle.js:3:494396
Object.callWithTelemetryAndErrorHandling extension.bundle.js:3:495427
DockerNetCoreDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:578:847481
extensionHostProcess.js:950:964extensionHostProcess.js:950:964
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by bwateratmsft** [comment] 2020-11-20 14:18
Duplicate of #1451. Also, the legacy `docker-coreclr` debug configuration has been removed and replaced by `docker`.

**Closed by bwateratmsft** 2020-11-20 14:19 UTC
