### ISSUE TITLE
Root password needed sometime when connet remote linux container from mac os

### ISSUE THREAD

**Issue by Raphael-Hao** [microsoft/vscode-docker#1769] opened 2020-03-19 05:42 UTC
![image](https://user-images.githubusercontent.com/19326656/77035347-5acd7e80-69e7-11ea-9922-4ac4621574db.png)

If i restart local vscode and the remote vscode, sometimes the root password is not needed.

BTW, I have already add current no-root user to docker user group.

**Comment by bwateratmsft** [comment] 2020-03-19 13:21
@Raphael-Hao is this a Docker-in-Docker setup or are you using Remote - SSH?

**Comment by Raphael-Hao** [comment] 2020-03-19 13:23
yes, I am using Remote-SSH.

**Comment by bwateratmsft** [comment] 2020-03-19 13:28
If you SSH into the remote system with a terminal, and do some Docker operations from the command line, does the password prompt ever come up?

**Comment by Raphael-Hao** [comment] 2020-03-19 13:33
No. If i do the Docker operations in a newly-launched integrated terminal of vscode, the password doesn't prompt, too. Only in the terminal launched by Docker extension, the password prompt. Even when i run the docker command manually in the terminal launched by the extension .

**Comment by bwateratmsft** [comment] 2020-03-19 14:41
Interesting...I have one idea. In one of the terminal windows created by the Docker extension, after running some command, can you try the following? Our extension has user-settings that will set these environment variables in terminals it creates. That's the only difference I can think of between terminals created by our extension vs. any other terminals within VSCode.
```bash
echo $DOCKER_HOST
echo $DOCKER_MACHINE_NAME
echo $DOCKER_CERT_PATH
echo $DOCKER_TLS_VERIFY
```

These settings are `docker.host`, `docker.machineName`, `docker.certPath`, and `docker.tlsVerify`, respectively.

**Comment by Raphael-Hao** [comment] 2020-03-19 14:46
Input: `echo $DOCKER_HOST` 
Output: `ssh://cwh@epcc.sjtu.edu.cn:8206`
Other environment variables are all empty.

**Comment by bwateratmsft** [comment] 2020-03-19 14:50
I see, it looks like the extension is operating in UI mode instead of workspace mode. Can you try adding the following user setting to `settings.json`?

```json
    "remote.extensionKind": {
        "ms-azuretools.vscode-docker": "workspace"
    }
```

Once you connect to the remote session you should be able to do "Install in SSH: ..." from the Extensions view:
![image](https://user-images.githubusercontent.com/36966225/77080096-4aa9a500-69cf-11ea-8d19-0785ef20c9d4.png)

After that, I think this issue *should* go away. It will be running the commands within the SSH host, instead of running them on your local machine.

**Comment by Raphael-Hao** [comment] 2020-03-19 16:05
In fact, I already have them in my settings.json. And the docker extension is installed in remote.
![image](https://user-images.githubusercontent.com/19326656/77087308-eeca3500-6a3d-11ea-82d4-fd7b15e469a4.png)
I will reinstall all the thing about vscode to see if this weird bug exists.

**Comment by bwateratmsft** [comment] 2020-03-19 16:16
If the `$DOCKER_HOST` setting is still present that probably means it somehow got into the workspace settings. In essence, the server is trying to do Docker calls to itself via SSH. Try removing those settings in the Remote settings (i.e. not the User settings):

![image](https://user-images.githubusercontent.com/36966225/77088878-7763b980-69db-11ea-901d-1ca7fc8d052b.png)

**Comment by Raphael-Hao** [comment] 2020-03-19 17:09
Resolved. Thx for your reply

**Comment by Raphael-Hao** [comment] 2020-03-20 01:59
Finally, I figure out that this is a conflict between remote container extension and the docker extension. You need a `dokcer.host` to attach a remote container in remote container extension. But when you run docker extension on remote host via remote ssh, the `docker.host` will cause the docker calls to itself via SSH.

**Comment by bwateratmsft** [comment] 2020-03-20 13:34
Why would the `docker.host` setting have migrated from the remote container to the remote SSH server?

**Comment by Raphael-Hao** [comment] 2020-03-20 13:47
When attaching a remote container via remote container, it runs the local docker-cli. When building a docker image via remote ssh, it runs the remote docker-cli. Thus, when i try to attach the remote container through remote ssh, the `docker.host` causes a confilct.

**Comment by bwateratmsft** [comment] 2020-03-20 13:53
I'm not sure I understand what you mean:

> attach the remote container through remote ssh

**Comment by Raphael-Hao** [comment] 2020-03-20 14:01
![image](https://user-images.githubusercontent.com/19326656/77170508-167cd400-6af6-11ea-8002-4e76f2e55acb.png)

I build docker image on remote host via remote ssh extension. Then I try to attach a docker container  
directly through the same vscode  window

**Comment by bwateratmsft** [comment] 2020-03-20 14:04
By "Attach" to that container, do you mean "Attach Shell" or "Attach Visual Studio Code"?

**Comment by Raphael-Hao** [comment] 2020-03-20 14:08
"Attach Visual Studio Code", It seems that this operation is using the local docker-cli and It needs the `docker.host` to run.

**Comment by bwateratmsft** [comment] 2020-03-20 14:18
@chrmarti What do you think for this? To summarize, the user is connected via Remote - SSH to an SSH server, where they build a container, and then do "Attach Visual Studio Code" on the container. Because the local CLI is used for that operation, `docker.host` is required (set to that SSH server), but if `docker.host` is present in the remote settings then in remote Docker terminals within the Remote - SSH session, it SSHs to itself (which results in lots of unneeded password prompts). Is it possible to keep Docker in workspace mode, set the `docker.host` on the host side to SSH, and on the remote side stay empty?

@Raphael-Hao In the meantime, it might work better in this case to change the extension kind to UI, but please note that will require an SSH agent to be configured. More information here: https://code.visualstudio.com/docs/containers/ssh

```json
    "remote.extensionKind": {
        "ms-azuretools.vscode-docker": "ui"
    }
```

**Comment by Raphael-Hao** [comment] 2020-03-20 14:24
OK, Thank you

**Comment by karolz-ms** [comment] 2020-03-20 16:03
Why, in this scenario, is it necessary to set docker.host in VSCode, instead on relying on DOCKER_HOST variable in the local and/or remote environment?

@Raphael-Hao said
> You need a dokcer.host to attach a remote container in remote container extension.
Why is this the case?

**Comment by bwateratmsft** [comment] 2020-03-20 16:12
@karolz-ms AFAIK that's how the Remote - Containers extension was implemented. Need @chrmarti to chime in.

**Comment by karolz-ms** [comment] 2020-03-20 16:15
@bwateratmsft but this is `Remote-SSH`?

**Comment by bwateratmsft** [comment] 2020-03-20 16:17
@karolz-ms It's both. Remote - SSH where a container is built, then Attach VSCode to said container.

**Comment by Raphael-Hao** [comment] 2020-03-20 16:29
@bwateratmsft @karolz-ms  It seems to be working. The Remote Containers extention uses the local environment variable. The docker extension in `Remote-SSH` does not use that. Then, there is no confilct.

**Comment by chrmarti** [comment] 2020-03-24 15:45
> @chrmarti What do you think for this? To summarize, the user is connected via Remote - SSH to an SSH server, where they build a container, and then do "Attach Visual Studio Code" on the container. Because the local CLI is used for that operation, `docker.host` is required (set to that SSH server), but if `docker.host` is present in the remote settings then in remote Docker terminals within the Remote - SSH session, it SSHs to itself (which results in lots of unneeded password prompts). Is it possible to keep Docker in workspace mode, set the `docker.host` on the host side to SSH, and on the remote side stay empty?

The remote setting will override the local user setting also for UI extensions. So UI and workspace extensions will see the setting's value from the remote. We could inspect the setting to find out if the local (user scope) value is different from the remote (machine scope) value, but I'm not sure using that would usually result in expected behavior.

**Comment by bwateratmsft** [comment] 2020-03-24 15:57
It seems to me then that everything is behaving as intended. The Docker extension cannot just ignore settings it is given, so we must respect the `docker.host` value even if that means SSH'ing to self, and if remote settings are meant to override local settings then this is also expected behavior from Remote - Containers.

Especially since there's other workarounds possible I'm OK with resolving this as by-design.

**Closed by bwateratmsft** 2020-03-24 15:57 UTC
Labels: needs more info, remote

**Comment by chrmarti** [comment] 2020-03-24 19:54
Make sense. We might at some point introduce our own settings in Remote-Containers that would take precedence over the Docker extension's ones (for Remote-Containers).
