### ISSUE TITLE
There is no running container in the Containers view for a short time after executing "Run Interactive" Command

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3703] opened 2022-11-17 09:41 UTC
**OS:** M1
**Build Version:** 20221116.1

**Repro steps:**
1. Run `docker run hello-world`.
2. Right click the image "hello-world:latest" -> Run Interactive.
3. Check whether there is a running container in the Containers view for a short time.

**Expect:**
There is a running container in the Containers view for a short time.
![actual](https://user-images.githubusercontent.com/57662131/202400183-611d86c2-44c5-49d4-8583-a62c6abe6846.gif)

**Actual:**
There is no running container in the Containers view for a short time.

**More Info:**
1. This issue also reproduces after executing "Run" Command.
2. This issue doesn't reproduce on Windows and Linux.

**Comment by bwateratmsft** [comment] 2022-11-18 14:26
It's hard to tell for sure from the GIF, but it looks like things were happening just slowly enough to avoid the 500 ms debounce, so several refresh calls stacked up. Additionally, the one-minute refresh may have happened at the same time, aggravating it.

**Comment by bwateratmsft** [comment] 2023-11-07 16:48
I'm going to close this unless we see more feedback that it is an issue. It doesn't seem to reproduce for me at this point.

**Closed by bwateratmsft** 2023-11-07 16:48 UTC
Labels: P3, AT-CTI, investigate
