### ISSUE TITLE
Can't access registries in Docker widget in Visual Studio

### ISSUE THREAD

**Issue by aaronc318** [microsoft/vscode-docker#1115] opened 2019-07-09 04:09 UTC
Repro steps:

1.
2.

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.4
OS: win32
Product: Visual Studio Code
Product Version: 1.36.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser extension.bundle.js:1:644951
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-07-09 16:16
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/935

@aaronc318 we should have a release out soon that improves this experience

**Closed by EricJizbaMSFT** 2019-07-09 16:16 UTC
