### ISSUE TITLE
The dockerfile editor shows the contextual help in a really annoying and aggressive way.

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode-docker#236] opened 2018-03-13 14:21 UTC
>This issue has been moved from [Microsoft/vscode/](https://github.com/Microsoft/vscode/issues/45656)
Author is @andrask.
---
Issue Type: <b>Bug</b>

The dockerfile editor pops up the contextual help dialog (e.g. for the RUN command) while typing.  This is annoying, it covers the text below and it moves with the cursor.  Just don't show this popup at all.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:01:43.521Z)
OS version: Linux x64 4.4.0-116-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3549)|
|Load (avg)|0, 0, 0|
|Memory (System)|15.56GB (2.98GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.25
python|ms-|2018.2.1
java|red|0.20.0
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2

</details>
Reproduces only with extensions

---

**Comment by chrisdias** [comment] 2018-03-14 01:10
duplicate of https://github.com/Microsoft/vscode-docker/issues/150

you can disable popups on a per file type basis:

``` json
    "[dockerfile]": {
        "editor.parameterHints": false,
        "editor.quickSuggestions": {
            "other": false,
            "comments": false,
            "strings": false
        }
    },
```

**Closed by chrisdias** 2018-03-14 01:10 UTC

**Comment by andrask** [comment] 2018-03-14 08:42
I disabled the Docker plugin and kept the syntax highlight. Would be better if this toolbox appeared on-demand, like in PyCharm with CTRL+P.
Thanks a lot!

**Comment by rcjsuen** [comment] 2018-03-14 09:38
@andrask You can use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Space</kbd>to get the dialog to popup after you've turned it off in the settings. You can also change this shortcut (`editor.action.triggerParameterHints`) to be something else if you wish.

**Comment by andrask** [comment] 2018-03-20 08:06
@rcjsuen  Thanks for the note. I enabled it again and changed the config. We will see how it works out. To be honest, I would consider the dialog turned off by default. It becomes less useful as time passes. Who needs the same info about `RUN` or `COPY` if it has been shown 30 times already in the same file?  In its current form it is really distracting as others noted, as well. :disappointed:

**Comment by rcjsuen** [comment] 2018-03-20 08:35
@andrask Thank you for your feedback.

I have provided a list of possible solutions to making this feature more user-friendly in [another issue](https://github.com/Microsoft/vscode-docker/issues/150#issuecomment-374514809). Having it be disabled completely is one of the proposed solutions. If you have time, please take a look at my comment and provide your feedback there. I would really appreciate it.
