### ISSUE TITLE
[Codespaces] No webpage opens after clicking the "learn more" button

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2944] opened 2021-05-15 11:09 UTC
**Environment:** GitHub Codespaces (Remote/Local)
**Build Version:** 20210513.4

**Repro Steps:**

1. Start up a private local registry using the command **`docker run -d --rm --name noAuthRegistry -p 5100:5000 registry`**.
2. Go to the "REGISTRIES" node -> Click 'Connect Registry...' -> Select 'Generic Docker Registry(Preview)' -> Input the URL: `http://localhost:5100` -> Username: <`Press Enter`>.
3. Push an image to the registry -> Right click the pushed image -> Select "Delete Image..." -> "Yes" -> Click "Learn more" when popping up a notification.
  ![image](https://user-images.githubusercontent.com/62053665/118358102-e0c76400-b5af-11eb-9c83-68b9704067ff.png)
4. Check whether open a webpage.

**Expect:**
Open a webpage in the browser: https://docs.docker.com/registry/configuration/#delete

**Actual:**
No webpage opens.

**Comment by bwateratmsft** [comment] 2021-08-04 13:29
The root cause is indeed the same as #2943, so resolving this one as dupe.

**Closed by bwateratmsft** 2021-08-04 13:29 UTC
Labels: AT-CTI, P3, bug
