### ISSUE TITLE
Action: vscode-docker.registries.connectRegistry

### ISSUE THREAD

**Issue by kid1995** [microsoft/vscode-docker#2886] opened 2021-04-16 17:52 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.12.1
OS: linux
OS Release: 5.10.23-1-MANJARO
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

**Comment by bwateratmsft** [comment] 2021-04-16 18:58
Duplicate of #722

**Closed by bwateratmsft** 2021-04-16 18:58 UTC
