### ISSUE TITLE
Containers panel fails for Swarm containers in v1.23.0

### ISSUE THREAD

**Issue by gpeb2** [microsoft/vscode-docker#3728] opened 2022-11-29 18:39 UTC
OS: Windows 10 + WSL2

Repro steps:

1. Launch VS with extension v1.23.0
2. Create a file called ```docker-compose.yml``` containing the following:
    ```
    version: '3.8'
    services:
      busybox:
        image: busybox
        deploy:
          restart_policy:
            condition: none
   ```
    The `restart_policy` is only set so that it doesn't keep spinning up new containers.

3. Run ```docker stack deploy --compose-file=docker-compose.yml test```

Expect:

Containers listed in panel

Actual:

Error message:
```
Failed to connect. Is Docker installed?
```
![image](https://user-images.githubusercontent.com/893883/204612238-3310d5e0-e385-4477-b0d5-e9468ac7bd7f.png)
or
```
Failed to connect. Is Docker running?
    Error: Invalid image name
```
![image](https://user-images.githubusercontent.com/893883/204614240-fc32a935-69a5-40fa-ba22-041fc73c3baf.png)

More Info:

Containers reappear when the `test_busybox` service is removed.

Rolling back to the previous version (1.22.2) works.

Output from ```docker version```:
```
Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by bwateratmsft** [comment] 2022-11-29 18:51
I suspect it's the same issue as #3719. Can you share the output of this command?
`docker container ls --all --no-trunc`

**Comment by gpeb2** [comment] 2022-11-29 18:56
> I suspect it's the same issue as #3719. Can you share the output of this command? `docker container ls --all --no-trunc`

Yes it's:
```CONTAINER ID                                                       IMAGE                                                                                    COMMAND   CREATED          STATUS                      PORTS     NAMES
9b4a20ec11cd5ebc67da4de012605108d2ae2ad85bccaa96ef8df210ff633be9   busybox:latest@sha256:fcd85228d7a25feb59f101ac3a955d27c80df4ad824d65f5757a954831450185   "sh"      45 seconds ago   Exited (0) 43 seconds ago             test_busybox.1.swyda0hipiwrizusnpnn47dtb
```

**Comment by bwateratmsft** [comment] 2022-11-29 18:57
Yep, looks the same as #3719. I'll close this one as a dupe of that.

**Closed by bwateratmsft** 2022-11-29 18:57 UTC
