### ISSUE TITLE
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.sre-tools.com, not registry-1.docker.io

### ISSUE THREAD

**Issue by joemaster** [microsoft/vscode-docker#1997] opened 2020-05-19 11:48 UTC
Does this occur consistently? 
Repro steps:

1. any of the docker pull, run, build commands
2. tried several ways to produce and install self-signed certificates, to no avail.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Command failed: docker login  --username joemaster571 --password-stdin
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.sre-tools.com, not registry-1.docker.io

Version: 1.2.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:308:12
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment] 2020-05-19 13:37
@joemaster A couple of questions--

1. Do you have a proxy set up?
1. What do you see if you open https://registry-1.docker.io/ in the browser?

**Comment by joemaster** [comment] 2020-05-19 20:47
No proxies set up. I had this running for some years with the default setup, as localhost only. But, Kubernetes is working fine.

The site cannot be reached page appears whenever I open the address.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bwateratmsft** [comment] 2020-05-20 12:22
This sounds like a network issue, in that case. When I open that page, I get a blank 200 OK response.

**Comment by joemaster** [comment] 2020-05-20 12:41
Mr. Brandon, so this is not a certificate problem. I've been stuck on that for days now. Trying both in wsl, ms code etc., no luck. I tried resetting hardware and VMs also. Nothing.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bwateratmsft** [comment] 2020-05-20 12:59
@karolz-ms any ideas? Aside from a proxy or some firewall, I can't think of what would be trying to intercept the connection and attach a different SSL certificate. Unless it's malware.

**Comment by joemaster** [comment] 2020-05-20 13:23
I do have a good docker running on my macbook. Everything there is perfect. I'm now on the process of mimicking my daemons, configs files there. I'll be in touch. Thank you very much.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bwateratmsft** [comment] 2020-06-01 17:51
This looks like a dupe of https://github.com/docker/for-linux/issues/994, DNS caching issues, in short. Amazon gave an IP from Docker Hub to "sre-tools.com" too quickly, so DNS entries were not updated in peoples' caches.

**Closed by bwateratmsft** 2020-06-01 17:51 UTC
Labels: needs more info
