### ISSUE TITLE
Linting on empty file

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode-docker#114] opened 2017-08-29 20:06 UTC
Windows
Testing https://github.com/Microsoft/vscode/issues/33053

1. create an empty `.dockerfile`
2. you get a linting error

![image](https://user-images.githubusercontent.com/1051190/29841585-c8892d1e-8cba-11e7-9569-53d81a319e46.png)

Expected - no error for empty file.

**Comment by rcjsuen** [comment] 2017-08-29 20:27
@seanmcbreen Hi Sean, thank you very much for testing vscode-docker.

The validator tries its best to mimic what the Docker engine does. If you try to ask Docker to build an empty Dockerfile, it will provide a similar error to warn the user that a Dockerfile cannot be empty.

```
$ cat Dockerfile
$ docker build .
Sending build context to Docker daemon  86.15MB
Error response from daemon: the Dockerfile (Dockerfile) cannot be empty
```

**Comment by BennyHarv3** [comment] 2018-04-11 17:30
I'm seeing this error anytime I open a Dockerfile that's under source control that I've moved; the error pops up for the related `.git` file, which is an empty file.

In the screenshot below, I moved the file `Dockerfile-Gradle` to `gradle/Dockerfile-Gradle`, and the extension says that my non-existent file has an error. Once I commit, the error goes away. Could the linter ignore these files?

![screen shot 2018-04-11 at 1 24 45 pm](https://user-images.githubusercontent.com/9916587/38632863-fc7469cc-3d8b-11e8-9d17-e1888ab6b0f9.png)

**Comment by rcjsuen** [comment] 2018-04-11 18:04
@BennyHarv3 Thank you for the bug report. I am having problems reproducing the error but I think I've seen it before. I don't think it is related to #237 if the problem is what I think it is although it may be inadvertently fixed by the same fix.

**Comment by StephenWeatherford** [comment] 2018-10-03 23:01
Closing due to lack of response.  Feel free to reopen if you have new information.  Thanks.

**Closed by StephenWeatherford** 2018-10-03 23:01 UTC
