### ISSUE TITLE
Pop up an extra dialog when F5ing a MVC project with a "xxx.csproj" file opened in the editor

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#4008] opened 2023-07-14 03:15 UTC
**OS:** All
**Build Version:** 20230712.5
**Regression:** Not a regression

**Repro Steps:**

1. Make sure installed XML extension.
2. Create and open a MVC project by command `dotnet new mvc`.
3. Make sure the project doesn't have Launch.json file.
4. The "xxx.csproj" file opened in the editor -> F5.
5. Check whether start debugging directly.

**Expect:**
Start debugging directly.

**Actual:**
Pop up an extra dialog.
![2](https://github.com/microsoft/vscode-docker/assets/107091828/9ff91e41-b132-4664-9334-4f746048ef32)

**More Info:**
This issue also reproduces for Console project by command `dotnet new console`.

**Comment by alexyaang** [comment] 2023-07-14 13:27
Closing this since this is expected behavior.

**Closed by alexyaang** 2023-07-14 13:27 UTC
Labels: AT-CTI
