### ISSUE TITLE
Docker Connect Registry

### ISSUE THREAD

**Issue by mikaelosterberg** [microsoft/vscode-docker#1442] opened 2019-11-21 11:15 UTC
Repro steps:
Add local gitlab container registry using user token. 
container registry uses self signed cert.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.8.2
OS: linux (Kbuntu)
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

**Comment by bwateratmsft** [comment] 2020-03-31 17:15
Dupe of #722

**Closed by bwateratmsft** 2020-03-31 17:15 UTC
Labels: investigate
