### ISSUE TITLE
Push Docker Image to DockerHub get  Error Message: (n.stack || "").split is not a function

### ISSUE THREAD

**Issue by hunglee** [microsoft/vscode-docker#2843] opened 2021-04-05 07:19 UTC
Does this occur consistently?  No 
Repro steps:

1. Push Image to DockerHub
2.

Action: vscode-docker.images.push
Error type: TypeError
Error Message: (n.stack || "").split is not a function

Version: 1.11.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.55.0
Language: en

<details>
<summary>Call Stack</summary>

```
getCallstack extension.bundle.js:16:365761
Object.parseError extension.bundle.js:16:366112
new RegistryConnectErrorTreeItem extension.bundle.js:305:64657
DockerHubAccountTreeItem.loadMoreChildrenImpl extension.bundle.js:859:271956
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by bwateratmsft** [comment] 2021-04-05 14:54
Duplicate of #2833

**Closed by bwateratmsft** 2021-04-05 14:54 UTC

**Comment by bwateratmsft** [comment] 2021-04-05 15:50
Changing this to be a duplicate of #2839.
