### ISSUE TITLE
Debugging Python in Docker

### ISSUE THREAD

**Issue by JanPalasek** [microsoft/vscode-docker#3823] opened 2023-02-03 21:08 UTC
I created a sample project using `Docker > Add Docker Files to Workspace`.

Then I ran Ctrl + F5, it correctly builds the image but then it raises an error that I can't get rid of:

```
Invalid message: "pythonPath" is not valid if "python" is specified.
```

Here is the sample project. I left everything default, just added `app.py` with a hello world message.

[test.zip](https://github.com/microsoft/vscode-docker/files/10582764/test.zip)

## Versions

- System: Windows 11 using WSL 2 on Ubuntu 20.04.
- Docker vscode: v1.23.3
- Python vscode: v2023.2.0

**Comment by eladavron** [comment] 2023-02-05 08:28
Started seeing this too

**Comment by cdena** [comment] 2023-02-06 15:15
I am also having this same issue and I found there is an open issue on the vscode repo as well.

https://github.com/microsoft/vscode/issues/173319

**Comment by bwateratmsft** [comment] 2023-02-06 15:23
Did this issue start happening recently, or has it been a few weeks? It might be a Python extension issue.

**Comment by gailmichi** [comment] 2023-02-06 15:46
Same problem here on v1.75, last week my docker project was running without any problems. No updates on python since then, maybe auto-update on VSCode.

VSCode: 1.75
Python: 3.10.9
Mac: 13.2

**Comment by bwateratmsft** [comment] 2023-02-06 16:28
No updates on Docker extension since 19 December; Python extension was updated today, and IIRC sometime last week as well. So I think it's something between VSCode and/or Python extension.

**Comment by isserver1** [comment] 2023-02-07 11:31
Reported here as well
https://github.com/microsoft/vscode-python/issues/20655

**Comment by SpyRefused** [comment] 2023-02-07 22:52
Same here, it had version 1.75. Windows 11.

I fixed it by downgrading to 1.74 (and reinstall Python Extension)

**Comment by raldebsi** [comment] 2023-02-14 07:22
Same problem here. It was working fine 10 minutes ago. I had to restart VS Code due to a crash, and it decided to update. Now I get this error.

**Comment by cesarlaforet** [comment] 2023-02-16 09:53
same problem :(

Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by debemdeboas** [comment] 2023-02-16 20:33
Same error here. It suddenly decided to stop working after the update.

**Comment by eladavron** [comment] 2023-02-28 13:26
It has **not** been solved by https://github.com/microsoft/vscode-docker/issues/3641

**Comment by danegsta** [comment] 2023-02-28 22:25
#3641 was an unrelated Python debugging issue; this specific issue is unfortunately external to the Docker extension that will require a fix in either vscode itself or (more likely) the Python extension to resolve. We're keeping this issue opened as a tracking issue, but https://github.com/microsoft/vscode-python/issues/20655 is the issue to follow for any progress on a fix in the Python extension.

**Comment by raldebsi** [comment] 2023-03-01 00:36
Thank you for your response

**Comment by atomey** [comment] 2023-03-01 23:03
Confirmed here also. I was unable to debug my Docker/Python application with VSCode after 1.74. I have now had to downgrade twice to 1.74.3 to resume normal Docker/Python debug functionality in VSCode. 

I'm using a virtualenv also for my Python path in case it matters.

**Comment by ultrablue** [comment] 2023-03-03 18:10
Is downgrading the only known workaround?

**Comment by bwateratmsft** [comment] 2023-03-03 18:17
@ultrablue the pre-release version of the Python extension seems to [fix the issue](https://github.com/microsoft/vscode-python/issues/20655#issuecomment-1451045168). You can get it by going to the Extensions view, right-clicking the Python extension, and choosing "Switch to Pre-Release Version":
![image](https://user-images.githubusercontent.com/36966225/222796811-a0d2e422-fb5e-42f5-84ea-a7d7c3d30c91.png)

**Comment by ultrablue** [comment] 2023-03-03 18:37
@bwateratmsft Confirmed. It looks like that did the trick for me.
Thank you!!

**Comment by atomey** [comment] 2023-03-03 18:39
This is working for me now in 1.76 VSCode which was released in last 2 days.

**Comment by dbreshears** [comment] 2023-03-08 19:02
Thanks for confirming.  Will close this issue since it is being handled externally

**Closed by dbreshears** 2023-03-08 19:02 UTC
Labels: external, tracking, Python
