### ISSUE TITLE
Quay.io Docker registry add attempt

### ISSUE THREAD

**Issue by shaneholloman** [microsoft/vscode-docker#984] opened 2019-06-11 14:40 UTC
Repro steps:

1. right click private registry to add
2. enter http://quay.io `also tried https://quay.io`
3. enter user
4. enter good api key

Action: vscode-docker.connectCustomRegistry
Error type: Error
Error Message: OAuth support has not yet been implemented in this preview feature.  This registry does not appear to support basic authentication.

Version: 0.6.2
OS: linux
Product: Visual Studio Code - Insiders
Product Version: 1.36.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.connectCustomRegistry extension.bundle.js:157:520554
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-06-11 15:40
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/869

**Closed by EricJizbaMSFT** 2019-06-11 15:40 UTC
