### ISSUE TITLE
when creating new app service plan by vscode, I took error bellow 

### ISSUE THREAD

**Issue by MarceloNascimento** [microsoft/vscode-docker#2672] opened 2021-01-26 00:48 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.9.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:120661
extension.bundle.js:52:332789extension.bundle.js:52:332789
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by bwateratmsft** [comment] 2021-01-26 14:27
Dupe of #2582. @MarceloNascimento you can follow the link in the error message to learn more about enabling the subscription for the Microsoft.Web namespace.

**Closed by bwateratmsft** 2021-01-26 14:27 UTC
