### ISSUE TITLE
failed to attach the debugger within the alotted timeout.

### ISSUE THREAD

**Issue by johanez** [microsoft/vscode-docker#1860] opened 2020-04-14 13:21 UTC
Does this occur consistently? 
Repro steps:

1.Steps to reproduce
follow this tutorial for Django: https://code.visualstudio.com/docs/containers/quickstart-python
2.

Action: docker-launch
Error type: string
Error Message: Failed to attach the debugger within the alotted timeout.

Version: 1.0.0
OS: linux
OS Release: 4.15.0-96-generic
Product: Visual Studio Code
Product Version: 1.44.0
Language: en

**Comment by bwateratmsft** [comment] 2020-04-14 16:03
@haniamr Can you take a look?

**Comment by haniamr** [comment] 2020-04-14 18:40
@johanez thanks for reporting this. I have some steps/questions to help troubleshoot this issue:

- Copy the "docker run" command from the terminal window and re-execute it manually to start the container. Does the container start successfully?
- If yes, then run the following commands in a terminal:
    - `docker exec -it {containerId} bash` // You can also do "Attach shell" from the Docker explorer
    - `ls /pydbg`
    - `cat /dbglogs/ptvsd-1.log` // If the file is found
- Going back to the "docker run" command, it should have a volume mapping that looks like that: `/tmp/{appFolderName}:/dblogs:rw`, can you do an `ls` on that directory?

Please share the output of the commands to help us understand what is going on.

Thanks!

**Comment by intv0id** [comment] 2020-04-19 09:38
I had the same issue and investigated a bit, the `/tmp/{appFolderName}:/dblogs:rw` isn't working on my machine whereas this binding appears when inspecting the docker container. Creating a file in the `/dblogs` path doesn't make it appear in `/tmp/{appFolderName}` of the host. 

What is happening is `/tmp/{appFolderName}/ptvsd-1.log` not being found in the `ensureDebuggerReady` function which prevents the `created` variable from being set to `true`.


Changing `/tmp` to my home directory as follows is fixing the issue:

```
export async function getTempDirectoryPath(): Promise<string> {
    return await fse.realpath("/home/[your home directory]/tmp/");
}
```

**FYI**

* The docker command: 
``` bash
 docker run -dt -P --name "cloudfolioserver-dev" -e "FLASK_APP=app.py" -e "PTVSD_LOG_DIR=/dbglogs" --label "com.microsoft.created-by=visual-studio-code" -v "/home/user/.vscode-insiders/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/old_ptvsd:/pydbg:ro" -v "/tmp/cloudfolio-server:/dbglogs:rw" -p "5678:5678" --entrypoint "python" "cloudfolioserver:latest" /pydbg/ptvsd --host 0.0.0.0 --port 5678 --wait -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000
```

* `"Starting server daemon on"`appears on `/dblogs/ptvsd-1.log`in the docker container.

* docker version:
```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.13.4
 Git commit:        1752eb3
 Built:             Sat Nov 16 01:05:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       9552f2b
  Built:            Sat Nov 16 01:07:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

* The permissions attached to the `/tmp/{appFolderName}`are

```
ls -al /tmp/cloudfolio-server/
drwxr-xr-x  2 user user  4096 avril 18 23:12 .
drwxrwxrwt 29 root root 77824 avril 19 11:30 ..
```

**Comment by haniamr** [comment] 2020-04-20 18:57
Thanks for the detailed feedback, @intv0id. I tried to repro the issue using the same Docker version you have on an Ubuntu (18.04) VM but couldn't, may I ask what distro are you using?

We've seen this problem before where for some odd reason files that are created in a container under /tmp/ don't show up in the host, but I thought that was related to virtualization since it was a nested VM scenario https://github.com/microsoft/vscode-docker/issues/1710.

**Comment by intv0id** [comment] 2020-04-20 21:11
Thanks @haniamr 

I'm using ubuntu 19.10, and trying to debug this sample code https://github.com/cloudfolio/cloudfolio-server on the april version of vscode (also tried vscode-insider, which had no effect as expected).

Aside from this, docker introduced [tmpfs mounts](https://docs.docker.com/storage/tmpfs/) on the latests versions of the engine and only for linux. Not sure it is related.

**Comment by haniamr** [comment] 2020-04-22 21:40
Thanks, I've started up a clean Ubuntu VM and chose to install Docker from the software center (18.09.9) and ended up reproducing the issue. 

For some odd reason, the permissions do not propagate correctly from host <-> container when files/directories are created under the /tmp/ directory. I'm not really sure where the problem is.

The thing that fixes it for me is to upgrade Docker to the latest (19.03.8), which does have the "tmpfs mounts" as you mentioned however that is not really what we're using (we're using bind mounts), so I can't say for sure this is the problem but it can definitely be related.

Please give that a try and let me know if this resolves it for you.

**Comment by intv0id** [comment] 2020-04-25 11:50
Sorry for the late answer. Thanks for your findings, version 19.03 is working fine.

**Comment by haniamr** [comment] 2020-04-27 18:36
Thanks for the confirmation, I'll close this issue. Please feel free to reach out if you have any further questions/issues.

**Closed by haniamr** 2020-04-27 18:36 UTC
Labels: Python Debug, needs more info
