### ISSUE TITLE
The webpage keeps loading forever after debugging Django project more than 3 times

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2191] opened 2020-07-24 08:36 UTC
**OS:** Win 10
**Build Version:** 20200723.3

**Repro Steps:**
1. Open a Python Django project and add Docker support for it in VS Code insider.
2. Debug this project more than 3 times.

**Expect:**
The webpage opens successfully every debugging.

**Actual:**
The webpage keeps loading forever after debugging 3 times.
![image](https://user-images.githubusercontent.com/45614674/88374036-962fed80-cdcb-11ea-96fc-402bd2077866.png)

**More Info:**
1. This issue does not reproduce for Flask project.
2. Please debug again to reproduce this issue if you can't reproduce it during debugging.

**Comment by bwateratmsft** [comment] 2020-07-24 12:37
I've seen this happen but every time it was VSCode silently hitting a breakpoint or halting on an exception.

**Comment by bwateratmsft** [comment] 2020-07-24 13:47
I haven't been able to repro today though as mentioned I've seen this in the past. @v-ruizh, if you hit this issue again can you check VSCode to see if it is stopped at an exception or breakpoint, etc.? If so, see if pressing continue (F5) in VSCode causes the web page to be loaded.

**Comment by v-ruizh** [comment] 2020-07-27 08:04
@bwateratmsft I can also reproduce this issue. No any breakpoint is set and there is no exception stopping the debugging. I have a video to record this issue, have sent you by Teams.

**Comment by dbreshears** [comment] 2020-08-07 01:48
@v-ruizh .  I am also unable to reproduce this on VSCode Insiders or VSCode.  Tried debugging 5 or 6 times each.

**Comment by v-ruizh** [comment] 2020-08-13 02:21
This issue does not reproduce on the machine with Docker Desktop + WSL2 enabled. It only reproduces without WSL2, it's an unstable issue. I will verify it on other machine and update the result after verification.

**Comment by bwateratmsft** [comment] 2020-09-29 16:35
I was not able to repro with WSL2 turned off. One thing to validate--Docker usually picks a new port every time, so if you refresh on an existing tab, it may show that loading-forever behavior--there's nothing listening on the other end. We open a new tab each time we debug; that tab should always have the latest port and work. Any others may not.

**Comment by bwateratmsft** [comment] 2020-10-12 18:49
We'll close this issue for now unless we hear from customers. I have seen something like this occur on multiple platforms--debugging "starts" but never attaches and continues, and the site isn't running. Since it's occurred on multiple platforms I suspect it is a VSCode issue. In any case, we cannot reliably reproduce this so we'll close for now.

**Closed by bwateratmsft** 2020-10-12 18:49 UTC
Labels: AT-CTI, Python Debug, investigate, not repro
