### ISSUE TITLE
MissingSubscriptionRegistration in VScode extension

### ISSUE THREAD

**Issue by vincentiroleh** [microsoft/vscode-docker#2960] opened 2021-05-21 17:51 UTC
Does this occur consistently? 
Yes

Repro steps:

1. Action: vscode-docker.registries.azure.createRegistry
2. Error type: MissingSubscriptionRegistration
3. Error Message: The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.12.1
OS: linux
OS Release: 5.11.0-17-generic
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1211545
extension.bundle.js:2:1199379
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by karolz-ms** [comment] 2021-05-21 17:55
Duplicate of https://github.com/microsoft/vscode-docker/issues/2347

**Closed by karolz-ms** 2021-05-21 17:55 UTC
Labels: duplicate
