### ISSUE TITLE
Fail to push an image that doesn't exist in the Docker Hub to Docker Hub

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3917] opened 2023-04-26 08:09 UTC
**OS:** All
**Build Version:** 20230425.3
**Docker Desktop Version:** 4.19.0 (106053)

**Repro Steps:**
1. Connect Docker Hub registry and make sure no image in it.
2. Navigate to "Images" view -> Right click an image -> Push... -> Select "Docker Hub" -> Select namespace -> Tag image.
3. Check whether succeeds to push an image to Docker Hub.

**Expect:**
Succeed to push an image to Docker Hub.

**Actual:**
Fail to push an image to Docker Hub.
<img width="1088" alt="Screenshot 2023-04-26 at 13 48 34" src="https://user-images.githubusercontent.com/57662131/234500140-7fe92a5d-1e81-46d7-aff8-ff30b9c27707.png">

**More Info:**
1. This issue doesn't reproduce when pushing an image that exists in the Docker Hub to Docker Hub.
2. This issue doesn't reproduce when pushing an image to Azure registry.

**Comment by karolz-ms** [comment] 2023-04-26 17:29
I cannot reproduce this. 🤔 

@v-xinda when you say "image that doesn't exist in the Docker Hub", do you mean the repository exists, but it is empty? See the screenshot below:

![image](https://user-images.githubusercontent.com/15271049/234655300-e9f27d3b-181e-423b-bd46-d545b2f7c7b4.png)

In other words, I am wondering whether you are trying to upload an image to an empty repository, vs upload an image to a repository that does not exist yet. If it is the latter, I can imagine you might get "access denied" error.

**Comment by v-xinda** [comment] 2023-04-27 02:24
@karolz-ms   "image that doesn't exist in the Docker Hub" means that the repository exists and it is empty. But I also can't reproduce this issue using the same machine today.

**Comment by karolz-ms** [comment] 2023-04-27 16:56
OK. I am going to close this for now, as I suspect it was a transient Docker Hub issue, but feel free to reopen if it happens again.

**Closed by karolz-ms** 2023-04-27 16:56 UTC
Labels: info-needed, AT-CTI, registries
