### ISSUE TITLE
Is not running on Raspberry Pi 

### ISSUE THREAD

**Issue by gamegear04** [microsoft/vscode-docker#3073] opened 2021-07-17 17:24 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.14.0
OS: linux
OS Release: 5.10.17-v7+
Product: Visual Studio Code
Product Version: 1.58.2
Language: de

**Comment by karolz-ms** [comment] 2021-07-19 03:34
Most likely a duplicate of #2925. The workaround is to install gnome-keyring package.

**Closed by karolz-ms** 2021-07-19 03:34 UTC
