### ISSUE TITLE
jjj

### ISSUE THREAD

**Issue by amir5813** [microsoft/vscode-docker#2921] opened 2021-05-07 09:41 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.help.openStartPage
Error type: Error
Error Message: Webview is disposed

Version: 1.12.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.56.0
Language: en

<details>
<summary>Call Stack</summary>

```
g.assertNotDisposed extensionHostProcess.js:88:55210
g.set html [as html] extensionHostProcess.js:88:54416
StartPage.createOrShow extension.bundle.js:2:4383398
async openStartPage extension.bundle.js:2:4385088
```

</details>

**Comment by karolz-ms** [comment] 2021-05-08 00:24
Duplicate of https://github.com/microsoft/vscode-docker/issues/2820

**Closed by karolz-ms** 2021-05-08 00:24 UTC
