### ISSUE TITLE
vscode docker.install Docker error

### ISSUE THREAD

**Issue by mohamedkhalid** [microsoft/vscode-docker#1939] opened 2020-05-04 19:50 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.installDocker
Error type: 1
Error Message: Process '"C:\Users\khalid\AppData\Local\Temp\docker_1588621...' exited with code 1
Error: The system cannot execute the specified program.

Version: 1.1.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:477087
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment] 2020-05-04 19:52
Duplicate of #1926

**Closed by bwateratmsft** 2020-05-04 19:52 UTC
