### ISSUE TITLE
Cannot connect to the Docker

### ISSUE THREAD

**Issue by Yahampath** [microsoft/vscode-docker#1254] opened 2019-09-07 19:45 UTC
Repro steps:
1. install docker v1.18 into ubuntu 18.08
2. install VSCode

Docker Version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Wed Jun 20 21:43:51 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Wed Jun 20 21:42:00 2018
  OS/Arch:      linux/amd64
  Experimental: false

Action: vscode-docker.openUrl
Error type: TypeError
Error Message: Cannot read property 'openUrl' of undefined

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.t.registerTrees.i.registerCommand extension.bundle.js:361:339782
module.exports.t.registerCommand.o.ext.context.subscriptions.push.i.commands.registerCommand.s.callWithTelemetryAndErrorHandling.e extension.bundle.js:211:112741
Object.<anonymous> extension.bundle.js:1:462722
module.exports.n extension.bundle.js:1:460883
module.exports.n extension.bundle.js:1:460660
Object.module.exports.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:462641
Object.<anonymous> extension.bundle.js:211:112522
module.exports.n extension.bundle.js:211:112188
module.exports.n extension.bundle.js:211:111965
module.exports.t.registerCommand.o.ext.context.subscriptions.push.i.commands.registerCommand.o extension.bundle.js:211:112397
_executeContributedCommand extensionHostProcess.js:518:163
_.executeCommand extensionHostProcess.js:517:426
Object.executeCommand extensionHostProcess.js:667:438
ContainersTreeItem.<anonymous> extension.bundle.js:31:102977
module.exports.n extension.bundle.js:31:98850
module.exports.n extension.bundle.js:31:98627
data extension.bundle.js:31:102878
ContainersTreeItem.<anonymous> extension.bundle.js:31:100961
```

</details>

**Comment by bwateratmsft** [comment] 2019-09-07 23:06
Looks like a dupe of #1220

**Closed by bwateratmsft** 2019-09-07 23:06 UTC
