### ISSUE TITLE
Customize Add Docker Files To Workspace

### ISSUE THREAD

**Issue by conradwt** [microsoft/vscode-docker#2026] opened 2020-05-28 22:21 UTC
**Goal**

I would like to be able to add additional languages as well as customize existing languages for my development workflows without having to submit a PR to update the extension.

**Currently**

The supported languages are fixed and new customizations need to be redeployed within a future version of this extension.

**Possible Solution**

Extend the extension to allow users to add their own templates to a designated directory that would get picked up and displayed within VS Code when one uses `Docker Add` command.

**Comment by bwateratmsft** [comment] 2020-05-29 13:32
I think this is basically what #1617 is about, so I'll mark this one as a dupe of that. I did update the issue text there to include your additional suggestions.

**Closed by bwateratmsft** 2020-05-29 13:32 UTC
