### ISSUE TITLE
Error connecting to ECR with temporary password

### ISSUE THREAD

**Issue by macsj200** [microsoft/vscode-docker#3202] opened 2021-09-10 23:36 UTC
I'm trying to connect to AWS ECR via the registries tab using the username `AWS` and a temporary password.

I obtain the temporary password with `aws ecr get-login-password`.

When I connect to the registry I get an Invalid JSON error.
![image](https://user-images.githubusercontent.com/5246841/132927578-be97f228-b31e-48d0-8d91-3082967e80cd.png)

Additionally, I encounter the following errors with incorrect/missing credentials:

<details>
<summary>Stale temporary password 403 error</summary>

![image](https://user-images.githubusercontent.com/5246841/132927616-c353aae3-58a8-4eb6-a7f3-e1f76e3991ea.png)

</details>

<details>
<summary>No username/password set error</summary>

![image](https://user-images.githubusercontent.com/5246841/132927647-4f218d8a-1afc-4302-96ff-573745f9211c.png)

</details>

Does anybody have any suggestions for how to connect to ECR via this extension?

Note that I _was_ able to successfully push a tagged image to ECR via the `docker` CLI so I believe my credentials are functional.

[Related issue](https://github.com/microsoft/vscode-docker/issues/3201): I'd like to be able to easily re-authenticate (specify a new password) with an ECR URI.

[This issue](https://github.com/microsoft/vscode-docker/issues/869) is also related, but I'd like to try this without re-configuring something like `credsStore` in `~/.docker/config.json` (I already tried using the [ECR creds helper](https://github.com/awslabs/amazon-ecr-credential-helper#Configuration) and I want to see if I can get it to work with password-based auth).

**Comment by macsj200** [comment] 2021-09-10 23:39
[Example ECR auth with `docker login`](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html)

**Comment by bwateratmsft** [comment] 2021-09-13 13:22
The initial issue, about unexpected end of JSON input, would be a dupe of #3185 and should be fixed in the upcoming 1.17 release.

ECR may work with the temp password (once the fix for #3185 is in place), as it is a V2 compliant registry, but Amazon has their own mechanism for "real" authentication (i.e. not the temp password). Consequently, an auth mechanism would have to be implemented for ECR to work properly. That is covered between #869 and #2033.

**Closed by bwateratmsft** 2021-09-13 13:22 UTC
