### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by CashMorris** [microsoft/vscode-docker#1159] opened 2019-07-25 16:46 UTC
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: ENOENT
Error Message: connect ENOENT //./pipe/docker_engine

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.0
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by nturinski** [comment] 2019-07-25 17:21
Closing as a duplicate of https://github.com/microsoft/vscode-docker/issues/1158

**Closed by nturinski** 2019-07-25 17:21 UTC
