### ISSUE TITLE
Error: Invalid container JSON

### ISSUE THREAD

**Issue by nvablaest** [microsoft/vscode-docker#3773] opened 2022-12-14 08:19 UTC
Does this occur consistently? Yes

Docker PS shows that service and containers are running but VS code extension fails to connect: Error: Invalid container JSON

Version: 1.23.2
OS: linux
OS Release: 5.4.0-135-generic
Product: Visual Studio Code
Product Version: 1.74.0
![Screenshot 2022-12-14 091920](https://user-images.githubusercontent.com/70451571/207542875-2db460c8-e943-439c-b187-2270a7cc6aa0.png)

Language: en

**Comment by chopinx** [comment] 2022-12-14 08:37
I have the same problem, have you found the solution?

**Comment by chopinx** [comment] 2022-12-14 08:41
I rollback to v1.20.0, and it works. I guess this problem occurs in the latest version.

**Comment by nadar** [comment] 2022-12-14 15:04
Same

**Comment by bwateratmsft** [comment] 2022-12-14 15:14
Dupe of #3724

**Closed by bwateratmsft** 2022-12-14 15:14 UTC

**Comment by Andry30** [comment] 2022-12-16 04:23
I rollback to v1.22.2 and it works

**Comment by cilence** [comment] 2022-12-16 12:07
I rollback to v1.22.2 and it works

**Comment by jvoinot** [comment] 2023-01-23 14:15
I have the same problem with the latest version v1.23.3.
I rollback to v1.22.2 and it works.

**Comment by JustinGrote** [comment] 2023-01-31 03:25
Same problem for me, in my case I was using podman. Was there a breaking change in JSON format?

**Comment by bwateratmsft** [comment] 2023-01-31 14:16
Podman's JSON objects are in a slightly different format. We're working on a solution for it, #3241.
