### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jeremmy-hub** [microsoft/vscode-docker#2935] opened 2021-05-13 11:23 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.help.openStartPage
Error type: Error
Error Message: Webview is disposed

Version: 1.12.1
OS: linux
OS Release: 5.10.0-kali4-amd64
Product: Visual Studio Code
Product Version: 1.56.1
Language: en

<details>
<summary>Call Stack</summary>

```
g.assertNotDisposed extensionHostProcess.js:88:55210
g.set html [as html] extensionHostProcess.js:88:54416
StartPage.createOrShow extension.bundle.js:2:4383398
openStartPage extension.bundle.js:2:4385088
```

</details>

**Comment by karolz-ms** [comment] 2021-05-14 15:37
Duplicate of https://github.com/microsoft/vscode-docker/issues/2820

**Closed by karolz-ms** 2021-05-14 15:37 UTC
