### ISSUE TITLE
Go app pops up a warning dialog "No valid ports are available" when opening the container in browser after executing "Run"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#2897] opened 2021-04-23 09:49 UTC
**OS:** Mac
**Build Version:** 20210417.1

**Repro Steps:**
1. Create a new folder e.g. 'dockergo' --> cd dockergo.
2. Do `go mod init microsoft.com/dockergo` in command line.
3. Open dockergo folder in VS Code.
4. Add main.go file in the same directory, with the following content.
```
package main
import (
		"fmt"
		"net/http"
	)
	
	func main() {
		http.HandleFunc("/", serveRoot)
	
		err := http.ListenAndServe(":3000", http.DefaultServeMux)
		if err != nil {
			fmt.Println(err.Error())
		}
	}
	
	func serveRoot(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "Hello, world!")
	}
```
5. F1 --> Docker: Add Docker Files to Workspace --> Go --> 3000 -->Yes.
6. Right-click on `Dockerfile` --> Build Image --> Keep default image name dockergo:latest.
7. Right-click on `dockergo:latest` in the IMAGES view --> **Run**.
8. Right-click on `dockergo:latest` in the CONTAINERS view --> Open in Browser.
9. Check whether open a web page or not.

**Expect:**
Open a web page that "Hello, world!" is displayed.

**Actual:**
Pop up a warning dialog "No valid ports are available".
![Screen Shot 2021-04-23 at 3 46 59 PM](https://user-images.githubusercontent.com/57662131/115855431-d0fbaa80-a45d-11eb-8585-9e086f0d510a.png)

**More Info:**
This issue doesn't reproduce after executing "**Run Interacive**" command.

**Comment by philliphoff** [comment] 2021-04-23 22:25
@v-xinda Is this repeatable, even after machine or Docker restarts?  I'm not able to reproduce it on my (M1) Mac with the latest Go tools; the browser opens as expected.

If it *can* reliably reproduce can you perhaps attach a `.zip` of the workspace?

**Comment by v-xinda** [comment] 2021-04-25 09:02
@philliphoff This issue still reproduces after restarting machine or Docker. Please get the workspace from `dockergo.zip`.
Workspace: [dockergo.zip](https://github.com/microsoft/vscode-docker/files/6371602/dockergo.zip)

**Comment by karolz-ms** [comment] 2021-06-08 17:00
@v-xinda can you add the output of "Inspect" operation on the container (right-click in Docker explorer and choose "Inspect"), and also what is the terminal output when you start the container. For the latter it should be something like

`> Executing task: docker run --rm -d  -p 3000:3000/tcp dockergo:latest <`

Also please verify that the container is running after step 7? Not stopped?

Assuming the container IS running, if you manually type `http://localhost:3000` address in the browser, do you get the "Hello, World!" response from the container?

**Comment by v-xinda** [comment] 2021-06-09 02:19
@karolz-ms Hi, you can get more details from the below:
1. There is no log message in Output terminal after executing "Inspect" for the container, only open a `dockergo:latest.json` file.
![image](https://user-images.githubusercontent.com/57662131/121281582-b34dac00-c90a-11eb-9e48-f77a6e922097.png)
2. Show the below messages in Terminal when I start the container by running the `dockergo:latest` image.
![image](https://user-images.githubusercontent.com/57662131/121281960-61595600-c90b-11eb-85a8-bf4b4af37220.png)
3. I make sure the container is running after executing step7. 
![image](https://user-images.githubusercontent.com/57662131/121282243-be550c00-c90b-11eb-80a4-ee02b2b5f5a9.png)
4. Get the "Hello World" after manually typing `http://localhost:3000` address in the browser.
![image](https://user-images.githubusercontent.com/57662131/121282384-fbb99980-c90b-11eb-9552-228e966a0a03.png)

**Comment by v-xinda** [comment] 2021-06-09 02:29
Verified this issue on the latest build 20210608.4, it doesn't reproduce.

**Comment by karolz-ms** [comment] 2021-06-09 15:45
OK, thanks. Since I could not reproduce either, I am going to close this for now.

**Closed by karolz-ms** 2021-06-09 15:45 UTC
Labels: AT-CTI, not repro
