### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by ppscarvalho** [microsoft/vscode-docker#2364] opened 2020-10-01 17:11 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.createRegistry
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.6.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:33:66487
extension.bundle.js:33:1636251extension.bundle.js:33:1636251
processTicksAndRejections task_queues.js:94:5
async AzureRegistryCreateStep.execute extension.bundle.js:1276:35083
```

</details>

**Comment by bwateratmsft** [comment] 2020-10-01 17:43
Duplicate of #2347

**Closed by bwateratmsft** 2020-10-01 17:43 UTC
