### ISSUE TITLE
Web Disposed

### ISSUE THREAD

**Issue by jabahum-coder** [microsoft/vscode-docker#2923] opened 2021-05-08 13:32 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.help.openStartPage
Error type: Error
Error Message: Webview is disposed

Version: 1.12.1
OS: linux
OS Release: 4.19.0-9-amd64
Product: Visual Studio Code
Product Version: 1.56.0
Language: en

<details>
<summary>Call Stack</summary>

```
g.assertNotDisposed extensionHostProcess.js:88:55210
g.set html [as html] extensionHostProcess.js:88:54416
StartPage.createOrShow extension.bundle.js:2:4383398
async openStartPage extension.bundle.js:2:4385088
```

</details>

**Comment by karolz-ms** [comment] 2021-05-09 23:59
Thanks, @jabahum-coder . This is a duplicate of https://github.com/microsoft/vscode-docker/issues/2820

**Closed by karolz-ms** 2021-05-09 23:59 UTC
