### ISSUE TITLE
extension failed to update inside vs code every time i installed it manually  in ubuntu 19.10

### ISSUE THREAD

**Issue by EslamIsmail93** [microsoft/vscode-docker#1437] opened 2019-11-16 00:33 UTC
Repro steps:

1.
2.

Action: vscode-docker.images.remove
Error type: 409
Error Message: (HTTP code 409) conflict - conflict: unable to delete b563dbff99d4 (cannot be forced) - image has dependent child images 

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098
extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by bwateratmsft** [comment] 2019-11-16 05:28
Dupe of #1391

**Closed by bwateratmsft** 2019-11-16 05:28 UTC
