### ISSUE TITLE
Consider volume management in the sidebar

### ISSUE THREAD

**Issue by orinokai** [microsoft/vscode-docker#866] opened 2019-03-22 11:05 UTC
Currently the sidebar shows Images, Containers and Registries. It would be great if it also showed Volumes and those volumes could be right clicked and removed. This would be great for clearing up after testing (when you don't want to do a full prune).

**Comment by pd93** [comment] 2019-05-05 20:21
This would be super helpful. I'd also like to see this for docker networks for the same reasons.

**Comment by StephenWeatherford** [comment] 2019-05-07 19:51
Good to know, thanks for the comments.

**Comment by julielerman** [comment] 2019-05-23 12:11
YES PLEASE! I just ran into a problem with a forgotten volume creating issues and it took me a few hours to check for it. It would be cool if this already awesome extension could be the hero for solving problems like that. :)

**Comment by EricJizbaMSFT** [comment] 2019-06-03 23:40
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/373

**Closed by EricJizbaMSFT** 2019-06-03 23:40 UTC
Labels: P2, enhancement
