### ISSUE TITLE
Allow to use self hosted gitlab registry.

### ISSUE THREAD

**Issue by uhlhosting** [microsoft/vscode-docker#1832] opened 2020-04-08 20:19 UTC
Issue Type: <b>Feature Request</b>

I see that there is a feature to add registries in docker from several places like azure, gitlab, i would like to setup hosted gitlab is this possible, will be in future?

Extension version: 1.0.0
VS Code version: Code - Insiders 1.44.0-insider (ea935488ec0e5415d4205c1f33ba332fd417f85a, 2020-04-07T12:27:31.043Z)
OS version: Darwin x64 19.4.0

**Comment by bwateratmsft** [comment] 2020-04-08 20:20
Isn't GitLab single-tenant hosting gone?

**Comment by bwateratmsft** [comment] 2020-04-08 20:52
I added this request to our list over in #869, so I will close this one as a duplicate of that.

**Closed by bwateratmsft** 2020-04-08 20:52 UTC
Labels: needs more info

**Comment by uhlhosting** [comment] 2020-04-08 21:11
@bwateratmsft according to this, gitlab has v2 support.

As of GitLab 11.9, we began shipping version 2.7.1 of the Docker container registry, which disables the schema1 manifest by default. If you are still using older Docker clients (1.9 or older), you may experience an error pushing images. See omnibus-4145 for more details.

**Comment by bwateratmsft** [comment] 2020-04-08 21:15
Can you link that? If GitLab has added V2 support I am definitely going to investigate further.

**Comment by uhlhosting** [comment] 2020-04-09 00:22
Sure here you go @bwateratmsft https://docs.gitlab.com/ce/administration/packages/container_registry.html#supporting-older-docker-clients

**Comment by bwateratmsft** [comment] 2020-04-09 13:12
Since this registry is based on the common `registry` image, it may already be possible, or become possible in 1.1 due to some additional work we did on V2 registries.

Can you run command `Docker Registries: Connect registry...`, choose `Generic Docker Registry (Preview)` as the provider, provide your registry URL and credentials, and try it out?

In 1.1 we added support for OAuth to registries in some cases, so if the registry requires OAuth it won't yet be possible in 1.0.

**Comment by uhlhosting** [comment] 2020-04-09 17:43
<img width="933" alt="image" src="https://user-images.githubusercontent.com/6324047/78924511-48041200-7a9a-11ea-88d3-9c39c3f2efe7.png">
seems its not liking it. i wonder why the gitlab.com code cant be tested for self hosted.

**Comment by bwateratmsft** [comment] 2020-04-09 17:46
Do you know if your registry requires OAuth or does it allow password auth?

**Comment by uhlhosting** [comment] 2020-04-09 17:51
I am not sure on this one. Will try to check. I believe will follow same principle like in gitlab.com maybe you can take a look to see the approach used there, since that one is already supported.

**Comment by uhlhosting** [comment] 2020-04-09 17:52
My guess based on this:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/6324047/78925342-91089600-7a9b-11ea-9675-0227ff38106a.png">
is that they do use oauth in order to provision the token support for registry.

**Comment by bwateratmsft** [comment] 2020-04-09 17:55
If you want, you could try installing the latest nightly version of the extension: [How to install Nightly version of Docker extension](https://github.com/microsoft/vscode-docker/issues/1408)

This has the OAuth changes we made for our upcoming 1.1 version of the extension.
