### ISSUE TITLE
The name org.freedesktop.secrets was not provided by any .service files

### ISSUE THREAD

**Issue by vscodr** [microsoft/vscode-docker#2213] opened 2020-07-31 03:38 UTC
Connecting the docker up registry from the docker extension inside vscode

1.select 'connect registry'
2.provide username
provide password
get the error. 

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.4.1
OS: linux
OS Release: 5.4.0-42-lowlatency
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

**Comment by karolz-ms** [comment] 2020-07-31 16:24
This is a duplicate of https://github.com/microsoft/vscode-docker/issues/722  I will try to get that bug prioritized higher; seems like people keep stumbling upon it

@vscodr what registry are you using? Does it require authentication?

**Comment by vscodr** [comment] 2020-08-01 00:44
I am trying to use docker hub. I am using Ubuntu 20.04

**Comment by karolz-ms** [comment] 2020-08-04 22:36
@vscodr what kind of desktop configuration are you using?

I believe Ubuntu 20.04 has `gnome-keyring` installed by default. This is my configuration and I am not able to reproduce the issue

**Comment by karolz-ms** [comment] 2020-08-05 21:29
I was able to reproduce.

**Comment by karolz-ms** [comment] 2020-08-06 15:29
PR submitted https://github.com/microsoft/vscode-docker/pull/2220

**Comment by karolz-ms** [comment] 2020-08-07 15:40
Fixed by https://github.com/microsoft/vscode-docker/pull/2220

**Closed by karolz-ms** 2020-08-07 15:40 UTC
