### ISSUE TITLE
Highlight is broken in `heredocs` regions of the docker file

### ISSUE THREAD

**Issue by romintomasetti** [microsoft/vscode-docker#4188] opened 2023-12-13 13:00 UTC
When using `heredocs` sections in a Docker file, this extension does not seem to correctly highlight.

See the below screenshot. The comment is not colorized.

However, other linters I've tried manage to do it correctly. I'll mention https://github.com/hadolint/hadolint for instance.

Is there anything I can do to help you with this?

![image](https://github.com/microsoft/vscode-docker/assets/22600251/bd2ce3d6-40ae-49da-b6df-ccf5c8b9dc78)

**Comment by rcjsuen** [comment] 2024-03-26 00:36
> When using `heredocs` sections in a Docker file, this extension does not seem to correctly highlight.
> 
> See the below screenshot. The comment is not colorized.
> 
> However, other linters I've tried manage to do it correctly. I'll mention https://github.com/hadolint/hadolint for instance.

@romintomasetti Sorry, could you explain how hadolint provides syntax highlighting? It is a tool for linting Dockerfiles and not about syntax highlighting.

**Comment by romintomasetti** [comment] 2024-03-27 14:07
Let's compare the output in `VS Code`.
|  *without* this extension | with this extension enabled |
|----|--|
| ![image](https://github.com/microsoft/vscode-docker/assets/22600251/4ce19b94-53d5-4697-b92a-843a14928952)  | ![image](https://github.com/microsoft/vscode-docker/assets/22600251/1ee53a7f-7f2d-4ad1-b97d-79b0e927bfc9) |

Basically, the `# Command` was in green but your extension makes it blue (in my color settings), making the code harder to read.

**Comment by rcjsuen** [comment] 2024-03-27 14:40
> Basically, the `# Command` was in green but your extension makes it blue (in my color settings), making the code harder to read.

@romintomasetti That is a (positive) side effect of the `#` character being the character for comments in a Dockerfile.

```Dockerfile
FROM alpine
COPY <<EOF test.go
// this is a comment
EOF
```
If you had the above Dockerfile where `//` is the character for comments it would not get highlighted.

**Comment by rcjsuen** [comment] 2024-03-27 14:50
```JSON
"[dockerfile]": {
    "editor.semanticHighlighting.enabled": false
}
```
If you would like to disable semantic highlighting, you can put the snippet above in your `settings.json` which will put you in the default colouring provided by Visual Studio Code instead of what the language server is calculating.

**Comment by rcjsuen** [comment] 2024-06-19 19:42
@bwateratmsft I think we can consider this to be a duplicate of #4183.

**Closed** 2024-06-24 14:20 UTC
Labels: duplicate, language-server
