### ISSUE TITLE
The new created context start to move back and forth shortly in context view

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2442] opened 2020-10-27 08:20 UTC
**OS:** Windows 10
**Build Version:** 20201026.13

**Repro Steps:**
Click the + sign or command to create a context and check it in context view.

**Expect:**
The new created context shows well in context view.

**Actual:**
The new created context start to move back and forth shortly in context view, then shows well in context view.
![context](https://user-images.githubusercontent.com/45614674/97274832-24ef5300-1870-11eb-9332-27695afe26c2.gif)

**Comment by bwateratmsft** [comment] 2020-10-27 17:29
I wonder if this is something to do with the fix in #2438.

**Comment by bwateratmsft** [comment] 2020-11-04 14:09
I'm able to reproduce without much trouble.

**Comment by bwateratmsft** [comment] 2022-10-14 17:39
Closing since we're doing ACA instead with #3535.

**Closed by bwateratmsft** 2022-10-14 17:39 UTC
Labels: P3, AT-CTI
