### ISSUE TITLE
Hard to see the "Read More" icon from Dockerfile "FROM" snippet when setting VS Code in Light theme

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3015] opened 2021-06-18 10:22 UTC
**OS:** Win 10
**Build Version:** 20210615.1

**Repro Steps:**
1. Open VS Code and set the theme to Light.
2. Create one Dockerfile and press "Ctrl+Space".
3. Hover the mouse over the "FROM" snippet.
4. Check whether the "Read More" icon is easy to see or not.

**Expect:**
The "Read More" icon is easy to see, like it in Dark theme.
![image](https://user-images.githubusercontent.com/45614674/122546667-c75b8100-d061-11eb-8598-0d75ca1a5474.png)

**Actual:**
Hard to see the "Read More" icon in Light theme.
![image](https://user-images.githubusercontent.com/45614674/122546563-ac890c80-d061-11eb-82d5-b199490340bc.png)

**More Info:**
This issue does not reproduce in Dark theme.

**Comment by karolz-ms** [comment] 2021-06-18 17:03
@rcjsuen is this UI part of Dockerfile lang service, or something VS Code provides?

**Comment by rcjsuen** [comment] 2021-06-18 17:48
> @rcjsuen is this UI part of Dockerfile lang service, or something VS Code provides?

@karolz-ms This looks like a theming issue with VS Code itself. The same issue can be reproduced in JavaScript.

![image](https://user-images.githubusercontent.com/15629116/122599092-c7e12100-d03b-11eb-94be-4dbb36e62f87.png)

**Comment by karolz-ms** [comment] 2021-06-18 18:05
Thanks Remy! Resolving as external.

**Closed by karolz-ms** 2021-06-18 18:05 UTC
Labels: AT-CTI
