### ISSUE TITLE
vscode-docker.images.selectGroupBy

### ISSUE THREAD

**Issue by JackieJ** [microsoft/vscode-docker#1056] opened 2019-06-19 16:17 UTC
Repro steps:

1.
2.

Action: docker.activate
Error type: Error
Error Message: command 'vscode-docker.images.selectGroupBy' already exists

Version: 0.6.3
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
d.registerCommand extensionHostProcess.js:497:447
Object.registerCommand extensionHostProcess.js:716:422
Object.module.exports.t.registerCommand extension.bundle.js:211:110531
ue extension.bundle.js:157:609314
Object.<anonymous> extension.bundle.js:157:611927
Object.<anonymous> extension.bundle.js:1:394616
module.exports.n extension.bundle.js:1:392954
module.exports.n extension.bundle.js:1:392731
Object.module.exports.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:394533
Object.module.exports.t.activateInternal extension.bundle.js:157:610822
```

</details>

**Comment by nturinski** [comment] 2019-06-19 17:28
@JackieJwe just changed the publisher from "PeterJausovec" to "ms-azuretools". It's possible your machine still has an extension under the old publisher.

To fix this, you can go to your "Extensions" page and uninstall v0.6.2 of the extension with "PeterJausovec" as the publisher: Then reinstall the extension from "Extension" page and hopefully you should be good to go.

Closing this is a duplicate of #1008.

**Closed by nturinski** 2019-06-19 17:28 UTC
