### ISSUE TITLE
Registry extension pulls image with lowercase tag

### ISSUE THREAD

**Issue by ecki** [microsoft/vscode-docker#4225] opened 2024-02-03 04:57 UTC
When I use the Docker registry explorer on my Windows 11 with Docker Desktop it shows me my custom repository (Generic Registry V2) and lists all the Image repositories and versions. It list a version tag correctly as "6.7.0-SNAPSHOT" but when I use the context menu to "Pull" it, it creates a task pulling "docker image pull registry/base/repo:6.7.0-snapshot" - i.e. it lowercased the tag and docker responds with manifest not found.

Name: Docker
Id: ms-azuretools.vscode-docker
Version: 1.28.0
Publisher: Microsoft

![image](https://github.com/microsoft/vscode-docker/assets/361432/20294aff-fc9c-4997-a459-e8f544513f0e)

**Comment by bwateratmsft** [comment] 2024-02-07 14:04
Duplicate of https://github.com/microsoft/vscode-docker/issues/4179. This will be fixed in the next release of the Docker extension (1.29.0), tentatively scheduled for Monday, 12 Feb.

**Closed by bwateratmsft** 2024-02-07 14:04 UTC
