### ISSUE TITLE
failed while trying to add my docker hub registry credentials

### ISSUE THREAD

**Issue by hsarena** [microsoft/vscode-docker#1329] opened 2019-10-08 21:15 UTC
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.8.1
OS: linux
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

**Comment by bwateratmsft** [comment] 2019-10-09 13:17
Duplicate of #722.

**Closed by bwateratmsft** 2019-10-09 13:17 UTC
