### ISSUE TITLE
Docker push: Cancelling at the quick pick gives a user-facing error: 

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-docker#443] opened 2018-09-04 18:48 UTC
Repro steps:
Command Palette -> Docker push -> Hit escape (do not pick an image)

Action: vscode-docker.image.push
Error type: TypeError
Error Message: Cannot read property 'includes' of undefined

Version: 0.1.1-alpha
OS: win32

**Comment by StephenWeatherford** [comment] 2018-09-04 19:45
Dupe of #440

**Closed by StephenWeatherford** 2018-09-04 19:45 UTC
Labels: P1, bug
