### ISSUE TITLE
Automatic Prompting for Azure login

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#1767] opened 2020-03-19 00:04 UTC
Although I am already connected to my Azure registry, pushing to my registry failed with an Authentication Required message. 

Suggestions: 
- Could we use the registry connection credential from within the docker extension to automatically log them in?
- Could we popup a dialog so the user can log in?
- Could we provide a login flow from the CLI similar to how push works for GitHub when a user is not authenticated. 

In this scenario I'm a user that has already connected to my registry so I wouldn't be worried about "giving VS Code my password". 

If the user is pushing to a registry outside of the account in the Docker extension, then they would be required to do `az acr login` no matter what. I personally tried doing `az login` multiple times from CLI before realizing `az acr login` was necessary.  

![image](https://user-images.githubusercontent.com/20650058/77018036-5ba7d700-6939-11ea-859e-2aba9f0143fb.png)

**Comment by bwateratmsft** [comment] 2020-03-19 13:17
Was already planning to deal with this with the other work, so I'll mark it for 1.1.

**Comment by bwateratmsft** [comment] 2020-03-27 18:54
I'm going to mark this as a dupe of #351.

**Closed by bwateratmsft** 2020-03-27 18:54 UTC
Labels: P1
