### ISSUE TITLE
Does this occur consistently? 

### ISSUE THREAD

**Issue by lcx978** [microsoft/vscode-docker#1962] opened 2020-05-09 07:23 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.installDocker
Error type: ECONNRESET
Error Message: read ECONNRESET

Version: 1.1.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.0
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
TLSWrap.onStreamRead stream_base_commons.js:183:27
```

</details>

**Comment by karolz-ms** [comment] 2020-05-11 01:16
Duplicate of #1913

**Closed by karolz-ms** 2020-05-11 01:16 UTC
Labels: duplicate
