### ISSUE TITLE
cant remove generic docker registry

### ISSUE THREAD

**Issue by youhide** [microsoft/vscode-docker#1177] opened 2019-08-02 17:35 UTC
Repro steps:
1. use disconnect from command pallet
2. we got invalid url...

Action: vscode-docker.registries.disconnectRegistry
Error type: ERR_INVALID_URL
Error Message: Invalid URL: 

Version: 0.7.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
onParseError url.js:237:17
parse url.js:246:3
new URL url.js:321:5
GenericDockerV2RegistryTreeItem.get host [as host] extension.bundle.js:31:159472
GenericDockerV2RegistryTreeItem.get label [as label] extension.bundle.js:157:487343
GenericDockerV2RegistryTreeItem.get effectiveLabel [as effectiveLabel] extension.bundle.js:1:464668
ConnectedRegistriesTreeItem.compareChildrenImpl extension.bundle.js:31:100254
module.exports.loadMoreChildrenInternal.n._cachedChildren._cachedChildren.concat.sort extension.bundle.js:31:102539
ConnectedRegistriesTreeItem.<anonymous> extension.bundle.js:31:102522
o extension.bundle.js:31:98683
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-08-02 17:44
@youhide please see workaround here: https://github.com/microsoft/vscode-docker/issues/1155#issuecomment-515172916

Closing as duplicate of that issue

**Closed by EricJizbaMSFT** 2019-08-02 17:44 UTC
