### ISSUE TITLE
Azure App service currently only supports running images from Azure Container Registries with admin enabled

### ISSUE THREAD

**Issue by mohammedalialimonster** [microsoft/vscode-docker#2700] opened 2021-02-04 20:15 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: Error
Error Message: Azure App service currently only supports running images from Azure Container Registries with admin enabled

Version: 1.9.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.53.0
Language: en

<details>
<summary>Call Stack</summary>

```
getNewSiteConfig extension.bundle.js:924:172856
processTicksAndRejections task_queues.js:97:5
deployImageToAzure extension.bundle.js:924:172319
```

</details>

**Comment by bwateratmsft** [comment] 2021-02-04 20:16
Dupe of #2623 and others. We plan on enabling MSI with #1685.

**Closed by bwateratmsft** 2021-02-04 20:16 UTC
