### ISSUE TITLE
I was not able to connect to my dockerhub account thru VS studio in Debian

### ISSUE THREAD

**Issue by paulorobles** [microsoft/vscode-docker#1256] opened 2019-09-09 05:05 UTC
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

**Comment by bwateratmsft** [comment] 2019-09-09 13:31
Looks like a duplicate of #1229

**Closed by bwateratmsft** 2019-09-09 13:31 UTC
