### ISSUE TITLE
Pruning images

### ISSUE THREAD

**Issue by CarlosMarioSom** [microsoft/vscode-docker#1395] opened 2019-11-05 21:34 UTC
Repro steps:

1.
2.

Action: vscode-docker.images.prune
Error type: 409
Error Message: (HTTP code 409) unexpected - a prune operation is already running 

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098
extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment] 2019-11-05 21:36
Dupe of #1323

**Closed by bwateratmsft** 2019-11-05 21:36 UTC
