### ISSUE TITLE
Docker not showing containers on local machine after update

### ISSUE THREAD

**Issue by BrendanBasson4** [microsoft/vscode-docker#3838] opened 2023-02-17 06:39 UTC
I recently updated my docker extension and for some reason non of the containers on my device are getting picked up by the extension. The extension keeps loading with no end.

OS: Ubuntu 20.04.5 LTS
VSCode: 1.75.1
Docker: 23.0.1, build a5ee5b1
Docker Extension: 1.23.3

**Comment by danegsta** [comment] 2023-02-21 20:29
@BrendanBasson4 do you use any VSCode/Docker remoting functionality (either connecting to a remote VSCode session over SSH or connecting to a non-default Docker daemon via Docker context/DOCKER_HOST environment variable)?

**Comment by danegsta** [comment] 2023-02-23 19:00
@BrendanBasson4 if you're using the snap versions of both vscode and docker, you may be running into an issue we've identified a workaround for here: https://github.com/microsoft/vscode-docker/issues/3821#issuecomment-1441210011

**Comment by BrendanBasson4** [comment] 2023-02-24 07:18
@danegsta I installed docker via the terminal on my local machine. vscode I installed via snap so I don't know whether this could be the problem. Note: it works when I revert to the previous version of the extension.

**Comment by danegsta** [comment] 2023-02-24 17:28
@BrendanBasson4 do you see any errors in the container/image views or does it simply say "No items found"? Can you run the command `which docker` from the command line and share the result?

**Comment by BrendanBasson4** [comment] 2023-02-28 06:02
@danegsta which docker outputs /usr/local/bin/docker. When I open the screen it starts loading but never stops doesn't say anything.

**Comment by danegsta** [comment] 2023-02-28 22:29
@BrendanBasson4 you may very well be running into the specific problem from [this issue comment](https://github.com/microsoft/vscode-docker/issues/3783#issuecomment-1445181032) or more generally [this issue](https://github.com/microsoft/vscode-docker/issues/3779) tracking some performance issues with Docker under certain circumstances.

**Comment by BrendanBasson4** [comment] 2023-03-01 06:13
@danegsta Looks like it I see the only fix is to reduce my containers by the looks of it

**Comment by bwateratmsft** [comment] 2023-03-02 15:40
I'll resolve this as a dupe of #3779.

**Closed by bwateratmsft** 2023-03-02 15:40 UTC
Labels: info-needed
