### ISSUE TITLE
not able to connect to registry

### ISSUE THREAD

**Issue by ganeshkuma241196** [microsoft/vscode-docker#3192] opened 2021-09-07 00:53 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.createRegistry
Error type: NoResourceFoundError
Error Message: No matching resources found.

Version: 1.16.1
OS: linux
OS Release: 5.4.0-81-generic
Product: Visual Studio Code
Product Version: 1.60.0
Language: en

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.<anonymous> extension.bundle.js:2:5042659
fulfilled extension.bundle.js:2:5036459
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by bwateratmsft** [comment] 2021-09-07 12:44
This is an external issue (https://github.com/microsoft/vscode-azure-account/issues/53). Dupe of #2662. Try restarting VSCode and see if the error still occurs.

**Closed by bwateratmsft** 2021-09-07 12:44 UTC
