### ISSUE TITLE
Error trying to "Connect Registry"

### ISSUE THREAD

**Issue by fabiojapa** [microsoft/vscode-docker#2009] opened 2020-05-23 01:42 UTC
Does this occur consistently? Yes
Repro steps:

1. Click "connect to registry" 
2. Choose "Docker hub"
3. Try to Signin login / password
4. Error

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.2.0
OS: linux - kubuntu 20.04
OS Release: 5.4.0-31-generic
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by bwateratmsft** [comment] 2020-05-26 13:30
Dupe of #722

**Closed by bwateratmsft** 2020-05-26 13:30 UTC
