### ISSUE TITLE
Connect Registry login dockerhub fails

### ISSUE THREAD

**Issue by derKosi** [microsoft/vscode-docker#3001] opened 2021-06-14 08:17 UTC
Cannot Login to docker hub via Docker extension
Login through terminal works fine, so this is Docker extension related

Does this occur consistently? Yes
Repro steps:

1. setup openSuse
2. install vscode
3. install Docker extention (1.13.0)
4. try to connect to Registry docher hub

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

Version: 1.13.0
OS: linux
OS Release: 5.3.18-lp152.78-default
Product: Visual Studio Code
Product Version: 1.57.0
Language: en

**Comment by karolz-ms** [comment] 2021-06-14 16:59
Most likely a duplicate of #2925. The workaround is to install `gnome-keyring` package.

**Closed by karolz-ms** 2021-06-14 16:59 UTC
