### ISSUE TITLE
Not able to register / login to Private Registries

### ISSUE THREAD

**Issue by syednadeembe** [microsoft/vscode-docker#899] opened 2019-04-16 08:45 UTC
Repro steps:

1. Navigate to Registries within Docker explorer 
2. Try to add a private registry 

Action: vscode-docker.connectCustomRegistry
Error type: Error
Error Message: OAuth support has not yet been implemented in this preview feature.  This registry does not appear to support basic authentication.

Version: 0.6.1
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.connectCustomRegistry (dist/extension.bundle.js:157:513712)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-06-10 20:57
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/869

**Closed by EricJizbaMSFT** 2019-06-10 20:57 UTC
