### ISSUE TITLE
Honour more settings from docker context (i.e TLS)

### ISSUE THREAD

**Issue by smhc** [microsoft/vscode-docker#2951] opened 2021-05-18 11:44 UTC
This extension currently retrieves the 'docker host' setting from the current docker context, but does not inherit any other settings:
https://github.com/microsoft/vscode-docker/blob/main/src/docker/DockerodeApiClient/DockerodeUtils.ts#L63

Ideally it should retrieve the ca, cert, and other TLS settings. Without this, having a 'docker context' set to a host that requires TLS causes this extension to fail to connect as it does not specify all the required settings.

Docker does support a 'DOCKER_CERT_PATH' env var, but with a context you may specify the certificate, key and ca files independently.

My guess is the code at:
https://github.com/microsoft/vscode-docker/blob/5fbb515f139332a6febb881cb75abdd2d1f1dd39/src/docker/ContextManager.ts#L268

Would need to be updated to parse out the ca,key and cert. Then the code at:
https://github.com/microsoft/vscode-docker/blob/main/src/docker/DockerodeApiClient/DockerodeUtils.ts#L84

Would need to be updated with something like:
```
 return new Dockerode(
{
  ca: fs.readFileSync(currentContext.CA),
  cert: fs.readFileSync(currentContext.CERT),
  key: fs.readFileSync(currentContext.KEY),
});
```

**Comment by smhc** [comment] 2021-05-18 12:01
Looks like this might be a duplicate of : https://github.com/microsoft/vscode-docker/issues/2058

A shame there is apparently 'a lot of difficulty' mapping the connection params from the context. It'd be nice if it could at least support the most common connection string params of 'ca=/xxx/ca.pem,cert=/yyy/cert.pem,key=/zzz/key.pem'.

**Comment by smhc** [comment] 2021-05-18 12:20
Running:
```
docker context create machine --docker "host=tcp://192.168.99.120:2376,ca=/home/user/myCA.pem,cert=/home/user/server.crt,key=/home/user/server.key" --default-stack-orchestrator swarm

docker context inspect machine --format="{{json .}}"
```

Outputs:
```
[
    {
        "Name": "machine",
        "Metadata": {
            "StackOrchestrator": "swarm"
        },
        "Endpoints": {
            "docker": {
                "Host": "tcp://192.168.99.120:2376",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {
            "docker": [
                "ca.pem",
                "cert.pem",
                "key.pem"
            ]
        },
        "Storage": {
            "MetadataPath": "/home/user/.docker/contexts/meta/bc020a35b7f9cb1382e7b534c68e3c531d849b119bf14f75ddead6cc45c3ccc1",
            "TLSPath": "/home/user/.docker/contexts/tls/bc020a35b7f9cb1382e7b534c68e3c531d849b119bf14f75ddead6cc45c3ccc1"
        }
    }
]
```


In the "TLSPath"/docker directory ("/home/user/.docker/contexts/tls/bc020a35b7f9cb1382e7b534c68e3c531d849b119bf14f75ddead6cc45c3ccc1/docker") there are three files:

```
ca.pem  cert.pem  key.pem
```

These appear to be the required files for the connection. Would it be possible to derive this information via an 'inspect' and pass it to Dockerode?

**Comment by bwateratmsft** [comment] 2021-07-12 14:12
> Looks like this might be a duplicate of : #2058

I'll go ahead and resolve this as a dupe of #2058, but please add anything to #2058 that you think is missing!

**Closed by bwateratmsft** 2021-07-12 14:12 UTC
Labels: enhancement
