### ISSUE TITLE
Cannot debug dotnet Docker amd64 container on host OSX M2

### ISSUE THREAD

**Issue by eitanbehar** [microsoft/vscode-docker#4009] opened 2023-07-16 13:11 UTC
Type: <b>Bug</b>

1) On a MacBook Pro OSX M2
2) Follow guide from VSCode documentation:
https://code.visualstudio.com/docs/containers/debug-netcore
3) Change base image to platform linux amd64
FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/runtime:6.0 

Extension version: 1.25.2
VS Code version: Code 1.80.0 (Universal) (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:39:33.766Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexyaang** [comment] 2023-07-17 13:26
@eitanbehar What is the error you're seeing?

**Comment by eitanbehar** [comment] 2023-07-17 14:54
there is no error (at least I don't see it), the container runs, but the breakpoint is faded out with message that "no symbols have been loaded"
Note that if I remove --platform=linux/amd64 then it will run/debug smoothly.
If it helps, I can provide a full working example

**Comment by bwateratmsft** [comment] 2023-07-17 15:00
It's possible that an Apple Silicon Macbook is not capable of debugging an amd64 container. We should investigate @alexyaang.

**Comment by alexyaang** [comment] 2023-07-17 15:10
@eitanbehar Thanks for providing more info! I'll do some investigating since I have a M1 Mac as well. 👍 

@bwateratmsft That is a possibility. time to try it myself

**Comment by eitanbehar** [comment] 2023-07-17 15:20
@alexyaang thanks for looking into this, please, let me know if more details are needed.

**Comment by alexyaang** [comment] 2023-07-17 18:17
@eitanbehar I was able to replicate this issue and I think I know why. :smile: Can you drop the contents of your `launch.json`, `tasks.json`, and your `Dockerfile`? And to confirm, your project is targeting .NET 6, correct?

**Comment by eitanbehar** [comment] 2023-07-18 17:58
@alexyaang sure, adding the whole project for better share
https://github.com/eitanbehar/docker-samples/tree/main/httpListener

**Comment by alexyaang** [comment] 2023-07-19 20:30
@eitanbehar After some further investigation, it seems that the core issue lies in the inability for our debuggers to debug an amd64 container on an arm64 machine. This explains why, when you remove the `--platform=linux/amd64` flag, debugging works as expected. 

Without the `--platform` flag, Docker automatically determines the platform based on the architecture and settings of your computer. In your case, it defaults to `linux/arm64`, allowing you to successfully debug because you are on an `arm64` machine. Consequently, this appears to be a debugger-related problem. I'm going to mark this as a duplicate of https://github.com/microsoft/vscode-docker/issues/2884.

**Comment by eitanbehar** [comment] 2023-07-20 04:37
@alexyaang thanks your efforts on this. So if I understand correctly, this scenario is not currently supported, do you happen to know if there is a plan to address it in a near future. I am not looking for a commitment, just your gut feelings on this.
Btw, I found this note in the release notes for net7, which might be related: 
".NET 7 is not supported being run (emulated) via [QEMU](https://www.qemu.org/). QEMU is used, for example, to emulate Arm64 containers on x64, and vice versa."
https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#qemu
Thanks again, Eitan

**Comment by alexyaang** [comment] 2023-07-21 16:15
@eitanbehar Your understanding is correct. I believe this scenario is not supported in .NET 6 or .NET 7. 

However, progress is being made in .NET 8 :) https://github.com/dotnet/dotnet-docker/issues/4388#issuecomment-1459038566

**Comment by bwateratmsft** [comment] 2023-07-26 18:05
I'll close this as a dupe of #2884. Hopefully this becomes available soon!

**Closed by bwateratmsft** 2023-07-26 18:05 UTC
Labels: duplicate, investigate, .NET
