### ISSUE TITLE
Issue of not able to create plan

### ISSUE THREAD

**Issue by zehxiong** [microsoft/vscode-docker#2380] opened 2020-10-09 22:33 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.6.0
OS: darwin
OS Release: 18.6.0
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:33:66487
extension.bundle.js:33:1636251
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment] 2020-10-12 13:48
Duplicate of #2347

**Closed by bwateratmsft** 2020-10-12 13:48 UTC
