### ISSUE TITLE
[feature request] recognize docker-compose.<something>.yml files

### ISSUE THREAD

**Issue by waspinator** [microsoft/vscode-docker#261] opened 2018-05-08 00:02 UTC
Docker compose has an option to override files for use in different situations. A common pattern seems to be to append a `.<something>` to a docker-compose file. Could we add recognition of those type of files? 

https://docs.docker.com/compose/extends/#example-use-case

**Comment by chrisdias** [comment] 2018-05-09 02:26
what are you thinking about when you say "recognition"?  According to the docs, a `docker-compose.override.yml` will automatically be picked up. If you have another file then you have to pass them to `docker-compose` with multiple `-f` parameters. There is no way to easily specify the order of files in VS Code.  I could have a multiple pick list, but there is no explicit order with that.

tell me more what you would like to see... thx.

**Comment by waspinator** [comment] 2018-05-09 13:55
It's not a big deal I know, but I'd like to see a pink whale instead of an exclamation mark as the file icon. I'm not sure if any actual linting is happening to the docker-compose file, but if it is, having the whale icon gives me more confidence that vscode knows what kind of file it is.

![icon example](https://i.imgur.com/swWp4tA.png)

**Comment by robertpeteuil** [comment] 2018-06-19 23:39
This is related to a request I made in January in #206

**Comment by AArnott** [comment] 2018-06-20 18:49
@chrisdias As #223 describes, the `docker-compose.override.yml` file will only be automatically picked up if no `-f` switch is specified. This VS Code Docker extension's UI *forces* us to specify exactly one yml file, which turns into a `-f` switch. This means no file is automatically picked up, and no single file has the right content for local development, since local development is facilitated by `docker-compose.yml` and `docker-compose.override.yml` combined.

**Comment by PrashanthCorp** [comment] 2018-08-13 22:52
@AArnott, it looks like the `-f`  switch is specified by default. See [here](https://github.com/Microsoft/vscode-docker/blob/7c95b8dcc042b6cc7f4595684414b365d3146c02/commands/docker-compose.ts#L84). 

Would the gist of your request be that this flag be made optional?

**Comment by AArnott** [comment] 2018-08-13 23:17
Yes.

**Comment by StephenWeatherford** [comment] 2018-08-15 22:58
@PrashanthCorp Please pull last issue into a separate bug.

**Comment by StephenWeatherford** [comment] 2018-08-15 22:59
Should enter an issue against vscode.

**Comment by bwateratmsft** [comment] 2019-10-21 14:18
Marking this one as a dupe of #379 and #520

**Closed by bwateratmsft** 2019-10-21 14:18 UTC
Labels: P2
