### ISSUE TITLE
I have an isue

### ISSUE THREAD

**Issue by wahyudin2003ti** [microsoft/vscode-docker#1921] opened 2020-04-28 18:59 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.installDocker
Error type: ECONNRESET
Error Message: read ECONNRESET

Version: 1.1.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
TLSWrap.onStreamRead stream_base_commons.js:183:27
```

</details>

**Comment by bwateratmsft** [comment] 2020-04-28 19:00
Dupe of #1913.

**Closed by bwateratmsft** 2020-04-28 19:00 UTC
