### ISSUE TITLE
Unable to remove Docker image

### ISSUE THREAD

**Issue by cchinnaraj** [microsoft/vscode-docker#1406] opened 2019-11-08 17:25 UTC
Repro steps:

1.
2.

Action: vscode-docker.images.remove
Error type: 409
Error Message: (HTTP code 409) conflict - conflict: unable to delete 204216b3821e (cannot be forced) - image has dependent child images 

Version: 0.8.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098
extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by bwateratmsft** [comment] 2019-11-08 17:26
Duplicate of #1391.

**Closed by bwateratmsft** 2019-11-08 17:26 UTC
