### ISSUE TITLE
Invalid lint errors

### ISSUE THREAD

**Issue by Tadimsky** [Microsoft/vscode-docker#259] opened 2018-05-07 06:25 UTC
I'm seeing an error in VS Code showing that I have an invalid command:
`\.RU["CMD`
But I do not have that command in my file:
![image](https://user-images.githubusercontent.com/1149244/39687743-9fae7626-5184-11e8-9ae0-0443825f6e83.png)

**Comment by rcjsuen** [comment] 2018-05-07 14:01
Hi, @Tadimsky. Thank you for your bug report. If you close and reopen the editor, does the problem occur again? Based on the strangeness of the printed error, I think this might be caused by rcjsuen/dockerfile-language-server-nodejs#216.

**Comment by Tadimsky** [comment] 2018-05-07 16:09
Ok and it looks like that's waiting on 
PR #249 to get in.

**Comment by rcjsuen** [comment] 2018-05-07 16:53
@Tadimsky Yes. Closing and reopening the editor fixes the problem for you though, right?

**Comment by chrisdias** [comment] 2018-05-07 16:57
re: PR #249 sorry for taking so long, i want to get this done this week.  will do my best!

**Comment by chrisdias** [comment] 2018-05-23 05:57
should be fixed now

**Closed by chrisdias** 2018-05-23 05:57 UTC
