### ISSUE TITLE
Cant see any containers, nor images, yet many are running

### ISSUE THREAD

**Issue by PeterHric** [microsoft/vscode-docker#3821] opened 2023-02-02 08:16 UTC
Type: <b>Bug</b>

I have logged into my docker hub account, run docker compose up, which had downloded all necessary images, run them and now everything is up and running. Yet, I do not see any of those mentioned in the title.

Likewise:
No networks, neither volumes visible - yet I have several up and running..
Looks like it can't connect to the active docker daemon ??

However:
I do see everything correctly in the registries pane...

I also can not pull image from docker hub: "Process exited with code 1"

Extension version: 1.23.3
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 5.4.0-137-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 3015)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|4, 2, 1|
|Memory (System)|11.39GB (6.27GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 977c745a-5dda-491e-9168-3e8b7bf9e81b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
pyind779:30647091
89544117:30613380
pythonsymbol12cf:30652349

```

</details>

**Comment by bwateratmsft** [comment] 2023-02-02 16:54
@PeterHric do any of the panels show an error message? What output do you get from these commands?
`docker -v`
`docker container ls --no-trunc --all --format "{{ json . }}"`
`docker image ls --no-trunc --all --format "{{ json . }}"`

**Comment by PeterHric** [comment] 2023-02-03 11:35
This is what I see..
![Screenshot at 2023-02-03 12-31-20](https://user-images.githubusercontent.com/7198139/216593227-32721d0a-07ac-4e6c-b2cd-c1fd71fcf085.png)

Docker version 20.10.17, build 100c70180

$ docker ps
CONTAINER ID   IMAGE                                                   COMMAND                  CREATED        STATUS        PORTS                                                                                                                                                                                                                                                                                                         NAMES
a5a6c7b32e75   romeriusph/uni_private:scada_rest_api_1_feb_2023        "dotnet ScadaRestApp…"   45 hours ago   Up 45 hours   0.0.0.0:6000-6001->6000-6001/tcp, :::6000-6001->6000-6001/tcp                                                                                                                                                                                                                                                 r-scadarestapi-1
1e567578e7a8   romeriusph/uni_private:notification_agent_24_jan_2023   "dotnet ConsumerAgen…"   45 hours ago   Up 45 hours                                                                                                                                                                                                                                                                                                                 r-consumeragent-1
29aa8224f3b4   romeriusph/uni_private:store_controller_24_jan_2023     "dotnet RestaurantAp…"   45 hours ago   Up 45 hours                                                                                                                                                                                                                                                                                                                 r-storecontroller-1
9d52944bde41   romeriusph/uni_private:scada_core_24_jan_2023           "dotnet ScadaCore.dll"   45 hours ago   Up 45 hours                                                                                                                                                                                                                                                                                                                 r-scadacore-1
26921a29e4c8   romeriusph/uni_public:rabbitmq_all_open                 "docker-entrypoint.s…"   45 hours ago   Up 45 hours   0.0.0.0:1883->1883/tcp, :::1883->1883/tcp, 0.0.0.0:4369->4369/tcp, :::4369->4369/tcp, 0.0.0.0:5671-5672->5671-5672/tcp, :::5671-5672->5671-5672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp, 0.0.0.0:25672->25672/tcp, :::25672->25672/tcp, 15675/tcp, 0.0.0.0:15675->15672/tcp, :::15675->15672/tcp   r-broker-1
9c8026ab71ee   romeriusph/uni_public:mysql_oct_2022                    "docker-entrypoint.s…"   45 hours ago   Up 45 hours   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 0.0.0.0:33060->33060/tcp, :::33060->33060/tcp

docker image ls --no-trunc --all --format "{{ json . }}"
{"Containers":"N/A","CreatedAt":"2023-02-01 13:17:21 +0100 CET","CreatedSince":"47 hours ago","Digest":"\u003cnone\u003e","ID":"sha256:d9b6de307acb9bd32aa90c3ec458ee01959293dfb411e6bbeacc98943151d2ed","Repository":"romeriusph/uni_private","SharedSize":"N/A","Size":"336MB","Tag":"scada_rest_api_1_feb_2023","UniqueSize":"N/A","VirtualSize":"335.9MB"}
{"Containers":"N/A","CreatedAt":"2023-02-01 12:44:10 +0100 CET","CreatedSince":"2 days ago","Digest":"\u003cnone\u003e","ID":"sha256:f33731a59f8bfd16a85fa4f7b6ef5c94a10dd42de35dbe329861693708c7e804","Repository":"romeriusph/uni_private","SharedSize":"N/A","Size":"340MB","Tag":"restaurant_rest_api_1_feb_2023","UniqueSize":"N/A","VirtualSize":"340.2MB"}
{"Containers":"N/A","CreatedAt":"2023-01-24 11:00:26 +0100 CET","CreatedSince":"10 days ago","Digest":"\u003cnone\u003e","ID":"sha256:8cdf592817221aac9a725fd1c12332d3c41125d733aabe28f76bceee442e70fd","Repository":"romeriusph/uni_private","SharedSize":"N/A","Size":"246MB","Tag":"scada_core_24_jan_2023","UniqueSize":"N/A","VirtualSize":"246.1MB"}
{"Containers":"N/A","CreatedAt":"2023-01-24 10:59:31 +0100 CET","CreatedSince":"10 days ago","Digest":"\u003cnone\u003e","ID":"sha256:b3a893091fa45150bdc9cd4e493503d64b0137fc870807a54d18ccfc7a637cf3","Repository":"romeriusph/uni_private","SharedSize":"N/A","Size":"248MB","Tag":"store_controller_24_jan_2023","UniqueSize":"N/A","VirtualSize":"247.6MB"}
{"Containers":"N/A","CreatedAt":"2023-01-24 10:56:45 +0100 CET","CreatedSince":"10 days ago","Digest":"\u003cnone\u003e","ID":"sha256:ad3db8aca7376d2e3f41bb8755be2f46db2a98704a095cf70b8481d63c382681","Repository":"romeriusph/uni_private","SharedSize":"N/A","Size":"251MB","Tag":"notification_agent_24_jan_2023","UniqueSize":"N/A","VirtualSize":"251.1MB"}
{"Containers":"N/A","CreatedAt":"2022-10-07 10:27:23 +0200 CEST","CreatedSince":"3 months ago","Digest":"\u003cnone\u003e","ID":"sha256:a84264c506967f72d73afbd76d320374e60cac7ef5d27273ca16f01b6f8ba6b7","Repository":"romeriusph/uni_private","SharedSize":"N/A","Size":"235MB","Tag":"robotic_sw_verti_deli_oct_7","UniqueSize":"N/A","VirtualSize":"234.8MB"}
{"Containers":"N/A","CreatedAt":"2022-10-07 10:24:36 +0200 CEST","CreatedSince":"3 months ago","Digest":"\u003cnone\u003e","ID":"sha256:26cb24de9349fdd7c41290d952257497c52a571f05d77befe724a7f13503a360","Repository":"romeriusph/uni_private","SharedSize":"N/A","Size":"232MB","Tag":"robotic_verti_deli_vm_app_oct_7","UniqueSize":"N/A","VirtualSize":"231.8MB"}
{"Containers":"N/A","CreatedAt":"2022-09-14 23:46:31 +0200 CEST","CreatedSince":"4 months ago","Digest":"\u003cnone\u003e","ID":"sha256:43fcfca0776df8e192d1647da2866237fbd9f8e875fb496e4ca887369b2dd995","Repository":"romeriusph/uni_public","SharedSize":"N/A","Size":"449MB","Tag":"mysql_oct_2022","UniqueSize":"N/A","VirtualSize":"449MB"}
{"Containers":"N/A","CreatedAt":"2021-07-06 17:09:26 +0200 CEST","CreatedSince":"19 months ago","Digest":"\u003cnone\u003e","ID":"sha256:35686b02b68da55a677f8a16116a6cc7ffd1306116c079bea619e486cee4513e","Repository":"romeriusph/uni_public","SharedSize":"N/A","Size":"8.35MB","Tag":"mosquitto_v2.0.10__mqtt_5.0__acceptsAll","UniqueSize":"N/A","VirtualSize":"8.345MB"}
{"Containers":"N/A","CreatedAt":"2021-05-27 17:59:25 +0200 CEST","CreatedSince":"20 months ago","Digest":"\u003cnone\u003e","ID":"sha256:2057c74f20324943033a26fabe3f3100d9025d962f208901ba94ab993bd3de77","Repository":"romeriusph/uni_public","SharedSize":"N/A","Size":"150MB","Tag":"rabbitmq_all_open","UniqueSize":"N/A","VirtualSize":"150.2MB"}

**Comment by PeterHric** [comment] 2023-02-03 11:36
docker container ls --no-trunc --all --format "{{ json . }}"
{"Command":"\"dotnet RestaurantRestApp.dll\"","CreatedAt":"2023-02-01 15:50:03 +0100 CET","ID":"01572848177e7e4adf2c2cfec9561012b984eef83df80ac9089a77f05e5ffbad","Image":"romeriusph/uni_private:restaurant_rest_api_1_feb_2023","Labels":"com.docker.compose.project.config_files=/home/peter/Projects/R/docker-compose.yml,com.docker.compose.project.working_dir=/home/peter/Projects/R,org.opencontainers.image.ref.name=ubuntu,org.opencontainers.image.version=20.04,com.docker.compose.config-hash=8973a0a8e05a8dc4ba12e4b92cfca8373b90bb51cdcc1b2de0470c3c356c0dea,com.docker.compose.image=sha256:f33731a59f8bfd16a85fa4f7b6ef5c94a10dd42de35dbe329861693708c7e804,com.docker.compose.oneoff=False,com.docker.compose.service=restaurantrestapi,com.docker.compose.version=2.5.0,com.docker.compose.container-number=1,com.docker.compose.depends_on=mysql_db:service_started,broker:service_started,com.docker.compose.project=r","LocalVolumes":"1","Mounts":"r_cert_vol","Names":"r-restaurantrestapi-1","Networks":"r_restaurant-be","Ports":"","RunningFor":"45 hours ago","Size":"6.51kB (virtual 340MB)","State":"exited","Status":"Exited (0) 24 hours ago"}
{"Command":"\"dotnet ScadaRestApp.dll\"","CreatedAt":"2023-02-01 15:50:03 +0100 CET","ID":"a5a6c7b32e7564d1cc7658437908d21b178aba5da0735c0f37a1dab4762a6a8c","Image":"romeriusph/uni_private:scada_rest_api_1_feb_2023","Labels":"com.docker.compose.depends_on=mysql_db:service_started,broker:service_started,com.docker.compose.project.config_files=/home/peter/Projects/R/docker-compose.yml,org.opencontainers.image.ref.name=ubuntu,org.opencontainers.image.version=20.04,com.docker.compose.container-number=1,com.docker.compose.image=sha256:d9b6de307acb9bd32aa90c3ec458ee01959293dfb411e6bbeacc98943151d2ed,com.docker.compose.oneoff=False,com.docker.compose.project=r,com.docker.compose.project.working_dir=/home/peter/Projects/R,com.docker.compose.service=scadarestapi,com.docker.compose.version=2.5.0,com.docker.compose.config-hash=b940a32dbe1c3daa9e98f24c3637f8a601b3a08deda72cdae1f57582524d697f","LocalVolumes":"1","Mounts":"r_cert_vol","Names":"r-scadarestapi-1","Networks":"r_restaurant-be","Ports":"0.0.0.0:6000-6001-\u003e6000-6001/tcp, :::6000-6001-\u003e6000-6001/tcp","RunningFor":"45 hours ago","Size":"9.89kB (virtual 336MB)","State":"running","Status":"Up 45 hours"}
{"Command":"\"dotnet ConsumerAgent.dll\"","CreatedAt":"2023-02-01 15:50:03 +0100 CET","ID":"1e567578e7a8f17d58934ffdc41cdf0dea52b47dc9552dceee02f48a32a93a64","Image":"romeriusph/uni_private:notification_agent_24_jan_2023","Labels":"com.docker.compose.container-number=1,com.docker.compose.project=r,org.opencontainers.image.ref.name=ubuntu,com.docker.compose.version=2.5.0,com.docker.compose.config-hash=cd320ef734d9d3311c18f6a56d21157260a3053cf28d14761e3918c9f1925077,com.docker.compose.depends_on=mysql_db:service_started,broker:service_started,com.docker.compose.image=sha256:ad3db8aca7376d2e3f41bb8755be2f46db2a98704a095cf70b8481d63c382681,com.docker.compose.oneoff=False,com.docker.compose.project.config_files=/home/peter/Projects/R/docker-compose.yml,com.docker.compose.project.working_dir=/home/peter/Projects/R,com.docker.compose.service=consumeragent,org.opencontainers.image.version=20.04","LocalVolumes":"0","Mounts":"","Names":"r-consumeragent-1","Networks":"r_restaurant-be","Ports":"","RunningFor":"45 hours ago","Size":"5.76kB (virtual 251MB)","State":"running","Status":"Up 45 hours"}
{"Command":"\"dotnet RestaurantApp.dll\"","CreatedAt":"2023-02-01 15:50:03 +0100 CET","ID":"29aa8224f3b43812fce4e5e9bd128ee3dcc93fc3cf07c20f4ed37a541cc947b6","Image":"romeriusph/uni_private:store_controller_24_jan_2023","Labels":"com.docker.compose.oneoff=False,com.docker.compose.project.config_files=/home/peter/Projects/R/docker-compose.yml,com.docker.compose.service=storecontroller,com.docker.compose.version=2.5.0,com.docker.compose.config-hash=592f3d6e9c2cb184bb0aabd2bfa85ef0214f8a7ad906badcb3779e87f9c0dd45,com.docker.compose.container-number=1,com.docker.compose.depends_on=mysql_db:service_started,broker:service_started,com.docker.compose.image=sha256:b3a893091fa45150bdc9cd4e493503d64b0137fc870807a54d18ccfc7a637cf3,com.docker.compose.project=r,com.docker.compose.project.working_dir=/home/peter/Projects/R","LocalVolumes":"0","Mounts":"","Names":"r-storecontroller-1","Networks":"r_restaurant-be","Ports":"","RunningFor":"45 hours ago","Size":"10.4kB (virtual 248MB)","State":"running","Status":"Up 45 hours"}
{"Command":"\"dotnet ScadaCore.dll\"","CreatedAt":"2023-02-01 15:50:03 +0100 CET","ID":"9d52944bde41f3856cb11ccbb19a6bf5cc3a40d3f3db7f4cfa2f4dde3f8d0e4f","Image":"romeriusph/uni_private:scada_core_24_jan_2023","Labels":"com.docker.compose.service=scadacore,com.docker.compose.version=2.5.0,org.opencontainers.image.ref.name=ubuntu,com.docker.compose.depends_on=mysql_db:service_started,broker:service_started,com.docker.compose.image=sha256:8cdf592817221aac9a725fd1c12332d3c41125d733aabe28f76bceee442e70fd,com.docker.compose.project=r,com.docker.compose.project.working_dir=/home/peter/Projects/R,org.opencontainers.image.version=20.04,com.docker.compose.config-hash=1352cf3a40a94f9b7863f8583bf8e02369875e89373fd20052f7307abfdc9034,com.docker.compose.container-number=1,com.docker.compose.oneoff=False,com.docker.compose.project.config_files=/home/peter/Projects/R/docker-compose.yml","LocalVolumes":"0","Mounts":"","Names":"r-scadacore-1","Networks":"r_restaurant-be","Ports":"","RunningFor":"45 hours ago","Size":"6.42kB (virtual 246MB)","State":"running","Status":"Up 45 hours"}
{"Command":"\"docker-entrypoint.sh rabbitmq-server\"","CreatedAt":"2023-02-01 15:50:03 +0100 CET","ID":"26921a29e4c8dc462913271268c13fbc9d622501014b5d21f0fc4f27d378d96b","Image":"romeriusph/uni_public:rabbitmq_all_open","Labels":"com.docker.compose.project.working_dir=/home/peter/Projects/R,com.docker.compose.service=broker,com.docker.compose.version=2.5.0,com.docker.compose.config-hash=9ceace4b046df90daf2b5fb4ffe25717a3a6fae0ed538ae6a35bc7e5a337c591,com.docker.compose.depends_on=,com.docker.compose.oneoff=False,com.docker.compose.project=r,com.docker.compose.container-number=1,com.docker.compose.image=sha256:2057c74f20324943033a26fabe3f3100d9025d962f208901ba94ab993bd3de77,com.docker.compose.project.config_files=/home/peter/Projects/R/docker-compose.yml","LocalVolumes":"1","Mounts":"r_broker_vol","Names":"r-broker-1","Networks":"r_restaurant-be","Ports":"0.0.0.0:1883-\u003e1883/tcp, :::1883-\u003e1883/tcp, 0.0.0.0:4369-\u003e4369/tcp, :::4369-\u003e4369/tcp, 0.0.0.0:5671-5672-\u003e5671-5672/tcp, :::5671-5672-\u003e5671-5672/tcp, 0.0.0.0:15672-\u003e15672/tcp, :::15672-\u003e15672/tcp, 0.0.0.0:25672-\u003e25672/tcp, :::25672-\u003e25672/tcp, 15675/tcp, 0.0.0.0:15675-\u003e15672/tcp, :::15675-\u003e15672/tcp","RunningFor":"45 hours ago","Size":"1.18kB (virtual 150MB)","State":"running","Status":"Up 45 hours"}
{"Command":"\"docker-entrypoint.sh mysqld\"","CreatedAt":"2023-02-01 15:50:03 +0100 CET","ID":"9c8026ab71eead573a4e8ce68090683ff4c003da1ff723e55b0f728cf13fa0da","Image":"romeriusph/uni_public:mysql_oct_2022","Labels":"com.docker.compose.service=mysql_db,com.docker.compose.version=2.5.0,com.docker.compose.config-hash=e71e4d8f446561f158009285b9b11239a99357256b5f7bb10e36a5f4114a529f,com.docker.compose.container-number=1,com.docker.compose.depends_on=,com.docker.compose.project.config_files=/home/peter/Projects/R/docker-compose.yml,com.docker.compose.project.working_dir=/home/peter/Projects/R,com.docker.compose.image=sha256:43fcfca0776df8e192d1647da2866237fbd9f8e875fb496e4ca887369b2dd995,com.docker.compose.oneoff=False,com.docker.compose.project=r","LocalVolumes":"1","Mounts":"r_db_vol","Names":"r-mysql_db-1","Networks":"r_restaurant-be","Ports":"0.0.0.0:3306-\u003e3306/tcp, :::3306-\u003e3306/tcp, 0.0.0.0:33060-\u003e33060/tcp, :::33060-\u003e33060/tcp","RunningFor":"45 hours ago","Size":"6B (virtual 449MB)","State":"running","Status":"Up 45 hours"}

**Comment by bwateratmsft** [comment] 2023-02-06 15:07
Thanks @PeterHric! Do you have a value for the VSCode setting `docker.environment`?

**Comment by PeterHric** [comment] 2023-02-08 21:19
Seems not: Ctrl+Shift+P -> docker.environment  
Result: Not found..

**Comment by danegsta** [comment] 2023-02-09 01:00
@PeterHric Can you check the extension settings (Ctrl+, by default or Ctrl+Shift+P > Preferences: Open Workspace Settings) as well? You can search for docker.environment there and it should show you if any are set. You may need to check for both the User and Workspace tabs to make sure.

**Comment by PeterHric** [comment] 2023-02-09 21:25
![image](https://user-images.githubusercontent.com/7198139/217942417-66bd2806-3d3e-45b6-a553-aeac80a6ab2e.png)
I am not sure what U mean by "both the User and Workspace tabs"   Ain't see any such stuff there..

**Comment by PeterHric** [comment] 2023-02-09 21:27
![image](https://user-images.githubusercontent.com/7198139/217942901-d793f1e2-6812-4af2-aaf2-e79b66960ca3.png)

**Comment by danegsta** [comment] 2023-02-10 17:19
@PeterHric there's definitely no extension specific environment overrides then. Can you run the command `docker context ls` and share the output? As well, could you expand and then share a screenshot of the contents of the "CONTEXTS" section in the Docker pane in VSCode?

**Comment by PeterHric** [comment] 2023-02-16 15:28
Oh, come on.. Does this have end somewhere ?
I'd better reinstall vscode & docker from scratch i guess.
Aint got time for this !

**Comment by danegsta** [comment] 2023-02-16 17:42
I understand the frustration; unfortunately there are a lot of different potential configurations between the OS, Docker, VSCode, and the Docker extension that could all lead to a behavior like this. Specifically, based on the behavior you're seeing, when you run docker commands from your terminal, it's executing them against one Docker environment (where your images and containers are running), while when we spawn a docker command from the extension, it's running against a different runtime environment (and therefore we're not seeing any images/containers).

This could be a matter of different environment variables being applied to the terminal and the VSCode process (differences in PATH or DOCKER_HOST would be one possible culprit and the settings you checked are an additional configuration point where the extension can override those environment variables). Docker context is another configuration point where Docker can be setup to talk to different runtime endpoints and if any are configured, it's possible VSCode is using a different one by default or configuration. Bash/sh configurations could also cause different behavior for a command run from the terminal vs. a process spawned from vscode. Beyond that, SSH remoting is another scenario where the terminal and VSCode might be running commands against entirely different machines. There are other increasingly less likely (and increasingly harder to diagnose) scenarios beyond those that could also be a root cause.

Because of how many different possible causes there are, the only real way to track down the root cause is to check the various possible settings/configurations that could be contributing until a source of the discrepancy is found. We'd be happy to keep suggesting additional troubleshooting steps if you decide you want to try anything else, but completely understand wanting to try a full re-install to see if that resolves the issue.

**Comment by danegsta** [comment] 2023-02-21 21:01
@PeterHric The fact that `docker context ls` isn't returning any results when we run it from the extension is really weird, as Docker should always have at least at least one default context. I've found references to [similar issues](https://askubuntu.com/questions/1315822/docker-containers-running-but-not-showing-up-in-docker-ps) related to multiple Docker installs on a machine which is worth considering.

Just to make sure, are you running VSCode in a remoting configuration (connecting to a remote machine via the SSH remoting extension for development)? If everything is running locally, can you run `ps aux | grep containerd` and share the output? It should indicate if more than one Docker daemon instance is running locally.

**Comment by TonyNyagah** [comment] 2023-02-22 11:06
I'm facing the same issue. I'm running vscode in Linux Mint inside VirtualBox though.
![Screenshot from 2023-02-22 14-05-02](https://user-images.githubusercontent.com/9380753/220602644-4fff36b8-c525-498c-824a-4a64f899146d.png)

**Comment by danegsta** [comment] 2023-02-22 19:38
@TonyNyagah are your using any of the VSCode remoting features (SSH remoting extension, etc.) to connect to a remote machine? Also, can you run the command `ps aux | grep containerd` and share the output?

**Comment by PeterHric** [comment] 2023-02-22 20:49
Nope, I am using it locally @T430
Else, I'd mention it..

***@***.***:~/Projects/R$ ps aux | grep containerd
root        1216  0.0  0.0 1575952 7732 ?        Ssl  feb06   1:45
containerd --config /run/snap.docker/containerd/containerd.toml --log-level
error
peter     177050  0.0  0.0  11568  2664 pts/2    S+   21:47   0:00 grep
--color=auto containerd
***@***.***:~/Projects/R$

st 22. 2. 2023 o 20:38 David Negstad ***@***.***> napísal(a):

**Comment by danegsta** [comment] 2023-02-23 04:41
@PeterHric Okay, I think I've finally managed to reproduce the issue and get some understanding around it. This seems to specifically be an issue with access to stdout being blocked by the snap sandbox when invoking one snap application (docker) from another (VSCode).

It's going to take quite a bit more digging to figure out how we can fix this particular problem in the long term as the snap sandboxing isn't something we directly control, but you should be able to workaround it by setting the "Docker Path" property in the VSCode settings to `/snap/docker/current/bin/docker` (assuming snap installed the docker binaries to the default path) to have the extension execute the Docker CLI binaries directly.

**Comment by marcio-pessoa** [comment] 2023-02-23 14:54
The solution proposed by @danegsta works perfectly.

**Comment by bwateratmsft** [comment] 2023-03-02 15:39
I'll resolve this issue as a dupe of #3843, so users can easily find the solutions in that issue.

**Closed** 2023-03-02 15:39 UTC
Labels: info-needed
