### ISSUE TITLE
Logged errors are duplicated in the OUTPUT window

### ISSUE THREAD

**Issue by charris-msft** [microsoft/vscode-docker#3617] opened 2022-09-16 20:59 UTC
## Issue
I've run through the "Build Image in Azure..." process a number of times and I've been tripped up by seeing errors logged multiple times. At first, I thought there was some kind of automatic retry happening.

I finally realized after seeing this a few times that the timestamps were identical and the output was just being duplicated.

Here are some examples:
![image](https://user-images.githubusercontent.com/74415662/190733967-cf2219c6-85bd-403c-8fa7-d50e97869ad9.png)

## Expected behavior
I expect to see each line of output exactly once in the OUTPUT window.

## Video Repros
https://microsoft.sharepoint.com/:f:/t/JEM/EklDiahGaQtDigc5E2SlrYAB3YU7H2NvdoiyIo1AkQUZ-A?e=eCGRIh

**Comment by bwateratmsft** [comment] 2022-09-19 13:09
These logs are being streamed from Azure. Need to investigate whether the duplication is happening on service-side (in which case we can't do anything about it) or if it's happening on the client.

**Comment by charris-msft** [comment] 2022-09-19 15:28
This is the only extension where I have seen this kind of behavior. I've used App Service and Container Apps quite a bit and I've never seen the duplicate lines.

If it is on the server side, it would be great to open an issue against that team.

**Comment by bwateratmsft** [comment] 2023-03-09 16:44
I'm going to resolve this as a dupe of #3616, it appears to ultimately be the same issue, just manifesting differently.

**Closed by bwateratmsft** 2023-03-09 16:44 UTC
Labels: P2, investigate, Azure/ACR
