### ISSUE TITLE
'Tasks: Run tasks' causes the docker getting started page to show

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-docker#2907] opened 2021-04-27 20:43 UTC
1. In a VS Code workspace that has not active the docker extension yet
2. Run the `Tasks: Run tasks` command
3. Try to select a task

**Bug**
The docker getting started page pops up, canceling the task selection UI

I believe this is because `Tasks: Run tasks` activates the docker extension

**Comment by dbreshears** [comment] 2021-04-28 23:10
Thanks for letting us know. We will investigate

**Comment by karolz-ms** [comment] 2021-06-02 22:25
Duplicate of https://github.com/microsoft/vscode-docker/issues/2953

**Closed by karolz-ms** 2021-06-02 22:25 UTC
Labels: P2, bug, investigate
