### ISSUE TITLE
Add Docker does not generate compose file

### ISSUE THREAD

**Issue by Urgen-Dorjee** [microsoft/vscode-docker#1224] opened 2019-08-24 16:26 UTC
I have installed Docker Extension 0.7.0, "Docker: Add Docker files to workspace" does not generate or create docker-compose.yml to the project. It's only create Dockerfile. Why is that, as per documentation it says :- Automatic Dockerfile, docker-compose.yml, and .dockerignore file generation (Press F1 and search for Docker: Add Docker files to Workspace)

Visual Code Version: 1.37.1
 
Thanks

**Comment by bwateratmsft** [comment] 2019-08-26 13:20
@Urgen-Dorjee What project type did you choose (e.g. Node, ASP.NET Core, etc.)?

**Comment by Urgen-Dorjee** [comment] 2019-08-26 14:26
I choose ASP.NET Core, I guess it should work as per your documentation reference..  Any idea!!

**Comment by bwateratmsft** [comment] 2019-09-04 13:54
For now I'll resolve this one as a duplicate of #840 since that covers this scenario.

**Closed by bwateratmsft** 2019-09-04 13:54 UTC
