### ISSUE TITLE
no se puede connectar a docker hub

### ISSUE THREAD

**Issue by haacho** [microsoft/vscode-docker#2194] opened 2020-07-25 00:18 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.4.1
OS: linux
OS Release: 5.6.19-2-MANJARO
Product: Visual Studio Code
Product Version: 1.47.2
Language: es

**Comment by karolz-ms** [comment] 2020-07-27 16:59
Duplicate of https://github.com/microsoft/vscode-docker/issues/722

**Closed by karolz-ms** 2020-07-27 16:59 UTC
