### ISSUE TITLE
Docker push fails after latest update with `(n.stack || "").split is not a function` or `Error: Decryption failed`

### ISSUE THREAD

**Issue by JensMagnus** [microsoft/vscode-docker#2839] opened 2021-04-04 11:55 UTC
Does this occur consistently? Yes.
Repro steps:

1. Right click on docker image and select "Push"
2. Make sure you've the latest version (1.55), worked previously.

Action: vscode-docker.images.push
Error type: Error
Error Message: Running the contributed command: 'vscode-docker.registries.logInToDockerCli' failed.

Version: 1.11.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.0
Language: en

<details>
<summary>Call Stack</summary>

```
S._executeContributedCommand extensionHostProcess.js:86:106930
processTicksAndRejections task_queues.js:97:5
async pushImage extension.bundle.js:859:265262
```

</details>

**Comment by hunglee** [comment] 2021-04-05 07:31
same problem

**Comment by bwateratmsft** [comment] 2021-04-05 15:10
@JensMagnus @hunglee I haven't been able to reproduce, does this happen consistently? e.g. does restarting VSCode make it go away?

**Comment by bwateratmsft** [comment] 2021-04-05 15:30
I was able to reproduce this or at least something similar. This error, #2843, and #2833 all seem to actually be this: https://github.com/microsoft/vscode/issues/120558

**Comment by bwateratmsft** [comment] 2021-04-05 15:48
@JensMagnus @hunglee @Dynatrace-Adam-Gardner I spoke to @RMacfarlane, and due to a change in the way encryption is  being done on Windows specifically, you will need to disconnect and reconnect to your registries. This should only be a one-time deal.

Steps:

1. Run command `Docker Registries: Disconnect`, and choose "Docker Hub" (or whichever registry is having problems)
1. Run command `Docker Registries: Connect Registry...` to reconnect your registry. You will need to reenter your password.

**Comment by bwateratmsft** [comment] 2021-04-06 20:15
We've put a PR into our upcoming 1.12.0 release that will make the error message better. It should now say "Error: Decryption failed". The workaround is the same--[disconnect the registry and reconnect](https://github.com/microsoft/vscode-docker/issues/2839#issuecomment-813464813).

**Comment by bwateratmsft** [comment] 2021-04-06 20:37
I updated the title to make it easy for others to discover this issue, since there's not really anything we can do about it...

**Comment by bwateratmsft** [comment] 2021-04-09 19:21
I'm going to close this as external since it's by-design from VSCode. To recap for those joining the thread, this is a one-time thing; on Windows the VSCode team changed the way their secrets API stores things, which requires reentering them. You can do this by disconnecting the affected registries and reconnecting them.

I'll leave the issue pinned for a while to make it as discoverable as possible.

**Closed by bwateratmsft** 2021-04-09 19:21 UTC
Labels: P0, external, investigate, tracking

**Comment by ArtNow198** [comment] 2021-04-26 14:35
> Does this occur consistently? Yes.
> Repro steps:
> 
> 1. Right click on docker image and select "Push"
> 2. Make sure you've the latest version (1.55), worked previously.
> 
> Action: vscode-docker.images.push
> Error type: Error
> Error Message: Running the contributed command: 'vscode-docker.registries.logInToDockerCli' failed.
> 
> Version: 1.11.0
> OS: win32
> OS Release: 10.0.19042
> Product: Visual Studio Code
> Product Version: 1.55.0
> Language: en
> 
> Call Stack
