### ISSUE TITLE
Error Message: (HTTP code 409) conflict - conflict: unable to delete c90075a9f74a (cannot be forced) - image has dependent child images 

### ISSUE THREAD

**Issue by ProblemaResolt** [microsoft/vscode-docker#1357] opened 2019-10-22 14:30 UTC
Repro steps:

1.
2.

Action: vscode-docker.images.remove
Error type: 409
Error Message: (HTTP code 409) conflict - conflict: unable to delete c90075a9f74a (cannot be forced) - image has dependent child images 

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: ja

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034extension.bundle.js:157:703034
extension.bundle.js:157:702997extension.bundle.js:157:702997
m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment] 2019-10-22 14:31
Duplicate of #1354. You can't delete an image that is in use by containers.

**Closed by bwateratmsft** 2019-10-22 14:31 UTC
