### ISSUE TITLE
Error when pushing image to ACR

### ISSUE THREAD

**Issue by dbafromthecold** [Microsoft/vscode-docker#666] opened 2018-11-29 09:45 UTC
Repro steps:
Running through the Docker: ACR Tasks: Build Image in VS Code
Error is generated when trying to push image to Azure

Action: vscode-docker.acr.quickBuild
Error type: SourceLocationNotFound
Error Message: The provided source location 'source/201811290000/20791c20-86a1-41c6-ae5c-07b8473fe461.tar.gz' is invalid or doesn't exists. Please use 'GetBuildSourceUploadUrl' to get a valid location to upload the source.

Version: 0.4.0
OS: win32

**Comment by StephenWeatherford** [comment] 2018-11-30 00:44
@dbafromthecold Does this reproduce every time?  Or does it sometimes succeed?  Anything else you could test us that might help us narrow down the issue?  Thx.

**Comment by dbafromthecold** [comment] 2018-11-30 10:53
@StephenWeatherford It's failed each time I've tried. Am working with a simple dockerfile (to test): -

`FROM mcr.microsoft.com/mssql/server:2019-CTP2.0-ubuntu

RUN /opt/mssql/bin/mssql-conf set sqlagent.enabled true 

CMD /opt/mssql/bin/sqlservr`

![image](https://user-images.githubusercontent.com/28392876/49284969-10408f80-f48e-11e8-8188-7386169c0057.png)

I can't see any other errors/logs to provide any further information I'm afraid.

**Comment by rosanch** [comment] 2018-12-07 20:02
The bug is the same that the on #679. The fix has been merged into master. It was fixed by the PR #656

**Comment by rosanch** [comment] 2018-12-08 00:37
Sorry. Closed this by mistake. It appears to be an error with one of the libraries being used in Linux machines. I'm looking into this issue.

**Comment by StephenWeatherford** [comment] 2018-12-11 20:41
@rosanch According to the error info above, this was on Win32, not Linux...?  It seems suspicious to me that the provided "source location" in the error is a relative path, shouldn't it be absolute?

#701 also shows this same error, although I wasn't able to repro.

**Comment by StephenWeatherford** [comment] 2018-12-11 20:46
@rosanch Actually, I think I know the cause:

In uploadSourceCode, you're not waiting for the blob upload to complete:
```
    blob.createBlockBlobFromLocalFile(blobInfo.containerName, blobInfo.blobName, tarFilePath, (): void => { });
```

**Closed** 2018-12-13 08:10 UTC
Labels: P1, bug
