### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by Niason** [microsoft/vscode-docker#2143] opened 2020-07-10 17:17 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.createRegistry
Error type: Error
Error Message: Entry not found in cache.

Version: 1.3.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.47.0
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902extension.js:229:168902
extension.js:229:54276extension.js:229:54276
extension.js:229:53143extension.js:229:53143
H._callback extension.js:1:186814
H.t._callback.t.callback.t.callback extension.js:181:5470
H.emit events.js:203:13
H.<anonymous> extension.js:181:18298
H.emit events.js:203:13
IncomingMessage.<anonymous> extension.js:181:17140
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by bwateratmsft** [comment] 2020-07-10 18:16
Dupe of #2122

**Closed by bwateratmsft** 2020-07-10 18:16 UTC
