### ISSUE TITLE
extension cannot list aci containers on linux

### ISSUE THREAD

**Issue by okarika** [microsoft/vscode-docker#2933] opened 2021-05-13 08:46 UTC
I created an ACI context successfully.
locally the extension listed the containers fine, but when I switched to the ACI context successfully, i got the error:
Failed to connect. Is Docker running?
Error:  14 UNAVAILABLE: No connection established

The additional troubleshooting page doesn't mention anything about ACI contexts

**Comment by okarika** [comment] 2021-05-13 08:51
my docker version is:
Docker version 20.10.6, build 370c289

**Comment by karolz-ms** [comment] 2021-06-09 20:21
I can reproduce

**Comment by bwateratmsft** [comment] 2021-07-28 18:36
I've seen this error as well. I've been able to make it go away with a Docker Desktop restart.

**Comment by JustinGrote** [comment] 2021-07-29 00:20
Happened to me on Windows, it got stuck with a InvalidAuthenticationToken tenant even after starting a clean vscode in a new userdatadir, so I knew it had to be coming from elsewhere, docker CLI was working just fine with ACI.
![image](https://user-images.githubusercontent.com/15258962/127412390-c88b9ec9-00c2-4410-8bef-9a176f27b8f8.png)

Doing a docker desktop update/restart fixed it for me as well.
![image](https://user-images.githubusercontent.com/15258962/127412582-c72c1934-e197-4c0c-a6a3-932fb30d7c23.png)

**Comment by bwateratmsft** [comment] 2021-08-31 18:02
At the moment I'm not able to reproduce but I'm also blocked by #2941.

**Comment by ElanShudnow** [comment] 2021-09-08 04:00
I have this issue.  I have a Mac M1 and a Windows 10 box.  Both have Docker Desktop and I have the same issue on both machines.  I've tried restarting Docker Desktop on both with VS Code running.  On both machines I can do a docker ps and see my running containers but on either machine, even after restarting Docker Desktop, VS Code will never show the running container.

**Comment by karolz-ms** [comment] 2021-09-08 16:45
@ElanShudnow do you see `Error: 14 UNAVAILABLE: No connection established` error? Or is it just that VS Code does not show any ACI containers?

If it is the latter, it is a [known issue with Docker Node.js SDK](https://github.com/docker/node-sdk/issues/67)

**Comment by ElanShudnow** [comment] 2021-09-08 17:13
@karolz-ms No error. Just no containers listed. Thanks for information.

**Comment by bwateratmsft** [comment] 2021-12-02 18:01
The others that get solved by #3263 are all put in the future bucket, so I'll do that with this one as well.

**Comment by bwateratmsft** [comment] 2022-10-14 17:38
Closing since we're doing ACA instead with #3535.

**Closed by bwateratmsft** 2022-10-14 17:38 UTC
Labels: external, Azure/ACR, blocked
