### ISSUE TITLE
Remapping of escape character not handled

### ISSUE THREAD

**Issue by paulcallen** [microsoft/vscode-docker#245] opened 2018-04-05 23:57 UTC
put this at the top of a docker file: # escape=`

and it remaps the escape character such that windows file paths can exist as `c:\foo`. Really nice feature.
Unfortunately this plug-in does not recognize this and as a result it thinks `\f` is an invalid escape sequence.

**Comment by rcjsuen** [comment] 2018-04-06 00:08
@paulcallen Hi, could you attach a screenshot and your Dockerfile to more clearly identify what the problem is?

**Comment by paulcallen** [comment] 2018-04-06 00:14
![capture](https://user-images.githubusercontent.com/16545334/38397840-69287150-392f-11e8-954e-32e919fb58eb.JPG)

looks like it is for quoted strings as I have other paths that do not show an error,

**Comment by thomashillyer** [comment] 2018-06-18 17:32
I think this is the same as issue #75

**Comment by rcjsuen** [comment] 2018-06-18 19:13
@thomashillyer I don't think that's quite the same. I feel like #75 is a parsing issue with quotes and backslashes whereas this #245 is due to the parser not being capable of reading Dockerfile's escape parser directive (understandably so in my opinion).

**Comment by thomashillyer** [comment] 2018-06-18 19:30
@rcjsuen but presumably if the Dockerfile's escape parser was read then the issue in #75 would also be solved because backslashes wouldn't be treated as escape characters

I suppose then the issue arises when someone wants to use the backslash as an escape character in a command they are running

**Comment by rcjsuen** [comment] 2018-06-18 20:19
@thomashillyer Yeah, you basically need a way to tell the grammar when you're in some `RUN` instruction or not for #75. I'm assuming that's not trivial or even possible to describe.

For this issue #245 you need a way to teach the grammar about Dockerfile escape parser directives. That sounds equally difficult and non-standard for a grammar but I could be wrong...

**Comment by StephenWeatherford** [comment] 2018-09-21 23:06
It's not clear how many people this is affecting.  Is it blocking people?

**Comment by paulcallen** [comment] 2018-09-25 22:17
not blocking for me.  It was more of an fyi for you. if it is easy to fix then go for it, if not then that is fine also,

**Comment by dcormier** [comment] 2018-09-27 04:30
I have this problem. It's definitely frustrating, but, as it doesn't not actually prevent editing the file, I wouldn't classify it as blocking for me. It just completely breaks syntax highlighting.

**Comment by StephenWeatherford** [comment] 2018-10-03 22:49
From a quick look it doesn't look like this would be very easy, but not an expert in g4. If someone wants to give it a shot, go for it!

**Comment by bwateratmsft** [comment] 2019-10-21 14:06
I filed https://github.com/microsoft/vscode/issues/82985 and will close this issue as external.

**Closed by bwateratmsft** 2019-10-21 14:06 UTC
Labels: P2, help wanted
