### ISSUE TITLE
There is no finished state in output log after executing "Build Image in Azure…" for "acr-build-helloworld-node" project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3017] opened 2021-06-18 11:34 UTC
**OS:** All 
**Build Version:** 20210615.1

**Repro Steps:**
1. Run `Build Image in Azure…` for Dockerfile in the **acr-build-helloworld-node** project.
2. Check whether there is a finished state in output log.

**Expect:**
There is a finished state in output log,
![image](https://user-images.githubusercontent.com/57662131/122553364-27562580-d06a-11eb-91cf-a0dd3cf1dc3e.png)

**Actual:**
There is no finished state in output log.
![image](https://user-images.githubusercontent.com/57662131/122553384-2de49d00-d06a-11eb-82f5-2f69277fb5f3.png)

**More Info:**
The command "Build Image in Azure…" executed successfully, a run task and a image show under the "Tasks" node.

**Comment by karolz-ms** [comment] 2021-06-18 17:43
Cannot reproduce 🤔 

![image](https://user-images.githubusercontent.com/15271049/122598144-49778580-d021-11eb-8584-cc00ef4e0208.png)

We might have an issue where we sometimes do not read the final line of the output when the stream is set to complete. Moving to 1.15 milestone to investigate.

**Comment by dbreshears** [comment] 2021-07-21 18:05
Closing due to low priority

**Closed by dbreshears** 2021-07-21 18:05 UTC
Labels: AT-CTI, P3, investigate
