### ISSUE TITLE
error on recommending Docker extension

### ISSUE THREAD

**Issue by mlzarathustra** [microsoft/vscode-docker#1010] opened 2019-06-18 22:44 UTC
Repro steps:

Not sure if I can reproduce: 
1. When I opened a Docker file, it popped a notification saying "do you want to install docker tools"
2. I clicked on "show recommendations"
3. I closed the recommendations pane( without installing anything) 

that's when I got the message. 

Action: docker.activate
Error type: Error
Error Message: command 'vscode-docker.images.selectGroupBy' already exists

Version: 0.6.3
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
d.registerCommand extensionHostProcess.js:497:447
Object.registerCommand extensionHostProcess.js:716:422
Object.module.exports.t.registerCommand extension.bundle.js:211:110531
ue extension.bundle.js:157:609314
Object.<anonymous> extension.bundle.js:157:611927
Object.<anonymous> extension.bundle.js:1:394554
module.exports.n extension.bundle.js:1:392892
module.exports.n extension.bundle.js:1:392669
Object.module.exports.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:394471
Object.module.exports.t.activateInternal extension.bundle.js:157:610822
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-06-18 22:47
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/1008

**Closed by EricJizbaMSFT** 2019-06-18 22:47 UTC
