### ISSUE TITLE
Obsolete certificates code in favor of new vscode features

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-docker#880] opened 2019-04-04 23:07 UTC
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_33.md#network-proxy-support-for-extensions

**Comment by EricJizbaMSFT** [comment] 2019-06-03 23:41
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/854

**Closed by EricJizbaMSFT** 2019-06-03 23:41 UTC
