### ISSUE TITLE
Run/Run Interactive: do not specify -rm

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-docker#1217] opened 2019-08-20 08:07 UTC
I am using the Docker extension to create a container from an image and I picked the "Run Interactive" command. To my surprise all my data was lost when the container stopped. This seems to be due to the -rm option that is passed.

I suggest to not add this.

@chrmarti cc

**Comment by xgdgsc** [comment] 2019-09-13 08:53
I lost my 2 hours of config because of this!

**Comment by bwateratmsft** [comment] 2020-02-25 20:23
This will be fixed by #1596 so I will dupe this one to that.

**Closed by bwateratmsft** 2020-02-25 20:23 UTC

**Comment by chrmarti** [comment] 2020-03-03 21:35
@bwateratmsft The change to fix #1596 seems to keep `--rm` in (https://github.com/microsoft/vscode-docker/pull/1649/files).

**Comment by bwateratmsft** [comment] 2020-03-03 21:46
@chrmarti Yes; by design. But it's trivial to customize now.
