### ISSUE TITLE
Can't add docker file to the project running on WSL

### ISSUE THREAD

**Issue by jacekplocharczyk** [microsoft/vscode-docker#1141] opened 2019-07-19 05:58 UTC
Hello,

I can't add docker file to the project running VS Code in WSL

Repro steps:

1. You need to have WSL (Ubuntu 18.04) enabled on Win10 17134.885
2. Change your home directory path to `C:\[user]\ ` - I did it like that      
    https://superuser.com/questions/1132626/changing-home-directory-of-user-on-windows-subsystem-for-linux

2. Open VS Code in WSL
2. Make sure you have Docker and  Remote Development packs installed locally 
2. Create and open `~/tmp/` dir
2. Run `Docker: Add Docker File to Workspace` - every configuration fails

Action: vscode-docker.configure
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open '\mnt\c\jacek\projects\kubernetes-up-and-running\docker-compose.yml'

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.openSync fs.js:436:3
Object.module.ELECTRON_ASAR.js:160:31
Object.writeFileSync fs.js:1168:35
extension.bundle.js:1:288233extension.bundle.js:1:288233
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-07-19 16:19
@jacekplocharczyk try adding this to your VS Code settings:
```
"remote.extensionKind": {
    "ms-azuretools.vscode-docker": "workspace"
}
```

See https://github.com/microsoft/vscode-docker/issues/954 for more info

**Comment by jacekplocharczyk** [comment] 2019-07-23 17:22
Thank @EricJizbaMSFT for your response.
I've added your lines to my `settings.json` file and it didn't change anything.

Here are my settings:

**Comment by EricJizbaMSFT** [comment] 2019-07-23 18:38
@jacekplocharczyk you have to reload VS Code for that setting to take affect. Did you do that?

To confirm, check the "Extension" view. You should _not_ see Docker in the "Local - Installed" section. Instead it should be in the wsl section above it
![Screen Shot 2019-07-23 at 11 37 28 AM](https://user-images.githubusercontent.com/11282622/61738049-4cd33b00-ad3e-11e9-8795-2b1891ec5b18.png)

**Comment by jacekplocharczyk** [comment] 2019-07-23 18:45
I didn't restart. My bad. It is working now.
Thanks!

**Comment by EricJizbaMSFT** [comment] 2019-07-23 18:48
Glad to hear it worked! We know this experience is confusing and hope to address it soon in #954. Closing for now as dupe of that issue

**Closed by EricJizbaMSFT** 2019-07-23 18:48 UTC
Labels: needs more info
