### ISSUE TITLE
Node.js docker-run task command infers image tag incorrectly

### ISSUE THREAD

**Issue by tbhanson96** [microsoft/vscode-docker#3445] opened 2022-02-25 20:07 UTC
I have the following docker-run task in my tasks.json:
```
{
	"version": "2.0.0",
	"tasks": [
	  {
		"type": "docker-run",
		"label": "start-docker",
		"platform": "node",
		"node": {
		  "enableDebugging": true
		}
	  },
	]
  }
  
  ```

and package.json file:

```
{
  "name": "docker-starter",
  "version": "1.0.0",
  "description": "Nodejs app template",
  "main": "main.js",
  "scripts": {
        "start:prod": "node main.js",
          ....
  },
  
  "author": "Tim Hanson",
  "license": "ISC",
  ...
}
```

It mostly works, but the tag ends up being incorrect:
```
 Executing task: start-docker <

> docker run -dt -P --name "dockerstarter-dev" --label "com.microsoft.created-by=visual-studio-code" -p "9229:9229" "dockerstarter:latest" npm run start:prod --debug 0.0.0.0:9229 <

Unable to find image 'dockerstarter:latest' locally
```

according to the documentation here: https://code.visualstudio.com/docs/containers/reference, the image tag should be inferred by the package.name property, which in my case is actually: **docker-starter** rather than **dockerstarter**, so it appears the hyphen is stripped out at some point.

**Comment by bwateratmsft** [comment] 2022-02-25 20:22
This is intentional in our case. If you also use a `docker-build` task, it will remove the dash in the same way, and things should work. As a workaround, you can specify a `tag` in `docker-build` tasks or `image` in `docker-run` tasks to override things and choose whatever image name you want.

There's more information [here](https://github.com/microsoft/vscode-docker/issues/3416#issuecomment-1035003390) on why we chose to remove dashes entirely. Since #3416 is basically the same as this, I'll close this one as a dupe of that one. If you feel strongly that we should support dashes, let me know and I'll reopen this. In the meantime the ability to override `tag`/`image` should help though.

You may also be interested in #2013, an item on our backlog which is related.

**Closed by bwateratmsft** 2022-02-25 20:22 UTC

**Comment by tbhanson96** [comment] 2022-02-25 20:36
@bwateratmsft understood. in a perfect world I'd like to this to work as I'm using $npm_package_name to build my docker image to make my codebase cleaner, but its a small issue.

**Comment by bwateratmsft** [comment] 2022-02-25 21:07
I don't know for sure without trying it, but I _think_ that environment variables defined according to [VSCode's environment-variables-in-tasks syntax](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables) will work (I'm assuming that `$npm_package_name` refers to an environment variable). Can you try it out and see if it does indeed work?

The `dockerRun` section would be:
```json
"dockerRun": {
    "image": "${env:npm_package_name}:latest" // Or whatever the exact tag is
}
```
