### ISSUE TITLE
cmd "Docker: Compose Up" broken again

### ISSUE THREAD

**Issue by alanwilter** [microsoft/vscode-docker#2758] opened 2021-03-08 09:56 UTC
It's really frustrating. I've seem similar issues here and it's back again.

It was working fine a week ago (I've done all the VS Docker tutorials). Then two days ago I noticed it was failing, however, if removing `~/.docker/config.json` (or removing just `"credsStore" : "osxkeychain",`), it was working but not for all commands, like attach or logs. So I upgraded Docker and it got even worse because NOTHING is working anymore inside VS Code.

Weirdly, if I open shell terminal (`@command:workbench.action.terminal.new`) or outside VS, I use ZSH BTW, all works fine.
Yes, I've read in others issues tickets (e.g. #2366).

### VS Code
```
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
macOs: 11.2.2 (20D80) 
ms-azuretools.vscode-docker, version 1.10.0
```
### Docker:
```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

I've created this rep to test as an example: https://github.com/alanwilter/flask-pytest-example

Now, if I do "cmd+shift+P" -> `Docker: Compose UP`, I get in the `Terminal`:
```
> Executing task: docker-compose -f "docker-compose.yml" up -d --build <

Building flaskpytestexample
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 346, in ensure_image_exists
  File "compose/service.py", line 1125, in build
  File "site-packages/docker/api/build.py", line 261, in build
  File "site-packages/docker/api/build.py", line 308, in _set_auth_headers
  File "site-packages/docker/auth.py", line 301, in get_all_credentials
  File "site-packages/docker/auth.py", line 287, in _get_store_instance
  File "site-packages/docker/credentials/store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-osxkeychain not installed or not available in PATH
[22585] Failed to execute script docker-compose
The terminal process "/bin/zsh '-c', 'docker-compose -f "docker-compose.yml" up -d --build'" terminated with exit code: 255.

Terminal will be reused by tasks, press any key to close it.
```
And don't ask me about "Experimental", I have no idea where/how to enable/disable that (I tried whatever I could) and my `~/.docker/config.json` always shows:
``` json
{
  "experimental" : "disabled",
  "credsStore" : "osxkeychain",
  "stackOrchestrator" : "swarm"
}
```

**Comment by bwateratmsft** [comment] 2021-03-08 15:10
Looks like yet another `PATH` issue with Big Sur:
> docker-credential-osxkeychain not installed or not available in PATH

@karolz-ms I think we need to raise this with the VSCode team. The issue is definitely not in the Docker extension, and it seems that terminals launched directly in the Terminal app aren't affected, so that leads me to believe it might not be the same bug as the decade-old one that Apple won't ack.

**Comment by karolz-ms** [comment] 2021-03-08 17:12
@bwateratmsft let's try. Can you open an issue against VSCode team? Thx!!

**Comment by bwateratmsft** [comment] 2021-03-08 17:22
@alanwilter just to double check, you don't have the setting `terminal.integrated.inheritEnv` set to `false`, right?

**Comment by alanwilter** [comment] 2021-03-08 18:08
@bwateratmsft Incredible `terminal.integrated.inheritEnv` is the culprit. It was set to `false`, I set to `true` and now EVERYTHING is working fine. Thanks for the tip. So, false alarm then? Close this ticket?

Sorry guys for not spotting this earlier.

**Comment by bwateratmsft** [comment] 2021-03-08 18:20
Good to know! I'll close this.

**Closed by bwateratmsft** 2021-03-08 18:20 UTC
Labels: external, investigate
