### ISSUE TITLE
Open an incorrect web page after deploying image Django to Azure App Service with custom location and port 8000

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3387] opened 2022-01-14 11:30 UTC
**OS:** All
**Build Version:** 20220112.2

**Repro Steps:**

1. Open the Python Django project and add Docker files for this project in VS Code.
2. Right click Dockerfile -> Build Image.
3. Right click this image in image view -> Push -> Azure -> Select a registry.
4. Right click the image in registry view -> Deploy Image to Azure App Service -> Create a new app service with a custom location -> Enter port 8000.
5. When done, click "Open Site" button in the notification.
6. Check whether opens a correct web page.

**Expect:**
Open a correct web page.

**Actual:**
Open an incorrect web page.
![image](https://user-images.githubusercontent.com/62053665/149465446-82bf26c0-f691-4e14-9575-470b84d3ccdb.png)

**Comment by karolz-ms** [comment] 2022-01-14 16:53
@v-mengwe does this also happen when you type the website URL manually into the browser? Is the new site accessible via different URL/from the Azure portal?

**Comment by v-mengwe** [comment] 2022-01-17 08:43
Yes, this also happens when you type the website URL manually into the browser. 
Please get the details from below:
![py1](https://user-images.githubusercontent.com/62053665/149734124-7ad0e7d5-db44-45fd-a0a7-0b6bfc490498.gif)

**More Info:**
This issue doesn't reproduce for other projects, e.g. mvc/myexpressapp/flask project.
![pmye](https://user-images.githubusercontent.com/62053665/149736112-159809df-4465-45dd-91dd-8ccd2b1bf7de.gif)

**Comment by bwateratmsft** [comment] 2022-01-18 14:46
I found this: https://docs.djangoproject.com/en/4.0/ref/settings/#allowed-hosts

It's a security measure from Django, it will only serve the request if it is to a host in the `ALLOWED_HOSTS` list. I assume though that Django apps work in non-Arc Azure, so I'm curious as to why it fails here.

**Comment by bwateratmsft** [comment] 2022-01-18 15:21
After some testing I've found that `ALLOWED_HOSTS` is necessary both for Arc and non-Arc deployments. Our docs [mention](https://code.visualstudio.com/docs/containers/tutorial-django-push-to-registry#_settings-for-django-apps) this, albeit in one of those buried pages that aren't on the ToC (which is its own problem we're working on addressing).

It is sufficient to add `.k4apps.io` (for Arc) / `.azurewebsites.net` (for non-Arc) to the `ALLOWED_HOSTS` setting in the settings.py file. Adding both works and is fine to do for testing:
```python
ALLOWED_HOSTS = ['.k4apps.io', '.azurewebsites.net']
```
![image](https://user-images.githubusercontent.com/36966225/149965525-11eea50f-b167-4fd6-8186-7b03e3e22ef9.png)

In real production environments, `Debug` should also be set to `False`, but that isn't necessary for testing.

I will close this as by-design/external, since this is working as intended and we have documentation coverage for it.

**Closed by bwateratmsft** 2022-01-18 15:21 UTC
Labels: AT-CTI, Python
