### ISSUE TITLE
[Suggestion] Add a "back" icon when adding docker files to workspace

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1740] opened 2020-03-09 12:08 UTC
**OS:** Windows
**Build Version**: [20200306.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15959&view=artifacts&type=publishedArtifacts)
**Regression:** Not a Regression

**Repro Steps:**
1. Create a .NET Core application  --> Open this application in VS Code.
2. F1 --> Type and select "Docker : Add Docker Files to Workspace".

**Actual:**
There is no way to back the previous step during the process.
![image](https://user-images.githubusercontent.com/34729092/76211598-e06d5500-61c3-11ea-9625-4d368b3d959f.png)

**Suggestion:**
Add a "back" icon when adding docker files to workspace.

**Comment by bwateratmsft** [comment] 2020-03-09 15:58
I'll mark this as a dupe of #1642 since that also mentions the ability to go back.

**Closed by bwateratmsft** 2020-03-09 15:58 UTC
Labels: AT-CTI, enhancement
