### ISSUE TITLE
Extension doesn't see docker running while using Podman

### ISSUE THREAD

**Issue by jamjon3** [microsoft/vscode-docker#3844] opened 2023-02-24 15:45 UTC
Type: <b>Bug</b>

When running podman with the podman-docker package (essentially creates an alias 'docker' for podman and let's users emulate the docker socket for compatibility), the IMAGES says "Failed to connect. Is Docker running?".

I suspect it 'may' be checking for the docker daemon which doesn't exist with Podman as it's using container support in the kernel. Whatever this is actually 'checking' for probably needs an exception. Looking at the Trobleshooting, 'docker ps' runs just fine and I'm able to connect to my registries as well.

Extension version: 1.24.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 6.1.12-200.fc37.x86_64
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.16GB (17.02GB free)|
|Process Argv|--unity-launch --crash-reporter-id 5c90261f-b5af-4f94-af52-1b57cc6e1bb5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30662444

```

</details>

**Comment by jamjon3** [comment] 2023-02-24 15:46
$ docker ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES

Note: I don't have any containers running so this is correct

**Comment by bwateratmsft** [comment] 2023-02-27 17:36
Fundamentally the problem is a little deeper. Beginning in Docker extension version 1.23.0, we started to use the CLI exclusively, instead of a mix of the CLI and the HTTP daemon. Podman's HTTP daemon almost exactly matches Docker's, and so either worked. The CLIs differ a little more than that, and Podman's output is not recognized by our parser. We're tracking that in #3241, so I'll close this as a dupe of that.

**Closed by bwateratmsft** 2023-02-27 17:36 UTC
