### ISSUE TITLE
Error entry: Invalid URL in Connected Registry

### ISSUE THREAD

**Issue by quangkieu** [microsoft/vscode-docker#1152] opened 2019-07-24 16:32 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I add a locahost:5000 registry to the registry list and I would be able to use it on the current session. 
But if I reopen VS Code, it would show as "Error: Invalid URL:". 
I tried to add the registry with or without credential but I still got error on next run. 
On next vscode run, I could not modify the registries list except to revert to version 6.4

Extension version: 0.7.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (3.76GB free)|
|Process Argv|C:\Users\quang\.vscode\extensions\ms-azuretools.vscode-docker-0.7.0|
|Screen Reader|no|
|VM|25%|
</details>

**Comment by EricJizbaMSFT** [comment] 2019-07-24 18:29
> I add a locahost:5000 registry to the registry list and I would be able to use it on the current session.

Try `http://localhost:5000`

> On next vscode run, I could not modify the registries list

What error did you get that blocked this? Try running "Docker Registries: Disconnect" from the command palette

**Comment by EricJizbaMSFT** [comment] 2019-07-25 18:03
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/1155

**Closed by EricJizbaMSFT** 2019-07-25 18:03 UTC

**Comment by quangkieu** [comment] 2019-07-25 18:59
Hey Eric,

Yes the registry url that I tried was `http://localhost:5000`
When I run the command, this is what I got


Repro steps:


1.The registry is not started as after a machine restart
2.Add new private registry http://localhost:5000

Action: vscode-docker.registries.disconnectRegistry
Error type: ERR_INVALID_URL
Error Message: Invalid URL: 

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
onParseError url.js:237:17
parse url.js:246:3
new URL url.js:321:5
GenericDockerV2RegistryTreeItem.get host [as host] extension.bundle.js:31:159472
GenericDockerV2RegistryTreeItem.get label [as label] extension.bundle.js:157:487343
GenericDockerV2RegistryTreeItem.get effectiveLabel [as effectiveLabel] extension.bundle.js:1:464668
ConnectedRegistriesTreeItem.compareChildrenImpl extension.bundle.js:31:100254
module.exports.loadMoreChildrenInternal.n._cachedChildren._cachedChildren.concat.sort extension.bundle.js:31:102539
ConnectedRegistriesTreeItem.<anonymous> extension.bundle.js:31:102522
o extension.bundle.js:31:98683
```

</details>
