### ISSUE TITLE
Docker Extension Error

### ISSUE THREAD

**Issue by iamstevewhite** [microsoft/vscode-docker#972] opened 2019-06-07 14:58 UTC
Repro steps:

1. Install Docker Extension
2. Click Docker symbol in left toolbar
3. Select Registries
4. Select Docker Hub

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser extension.bundle.js:1:644951
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-06-07 16:23
For now, you can right click on the "Docker Hub" node and log out. You should see a new item in the tree to log in again.

Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/935 - we should have improvements in this area coming soon

**Closed by EricJizbaMSFT** 2019-06-07 16:23 UTC
