### ISSUE TITLE
Fail to debug Python project on Linux

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1710] opened 2020-03-04 13:45 UTC
**OS:** Linux
**Build Version:** [20200304.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15718&view=results)

**Repro Steps:**
1. Open a Python project(General/Django/Flask) in VS Code.
2. F1->Docker: Add Docker Files to Workspace->Python->include docker compose files.
3. F5.

**Expect:**
Debug Python project successfully without any error.

**Actual:**
Fail to debug Python project. 
![image](https://user-images.githubusercontent.com/45614674/75885111-e5977080-5e60-11ea-91d5-67cd140bc7bb.png)

**More Info:**
This issue does not reproduce on Windows and Mac.

**Comment by bwateratmsft** [comment] 2020-03-04 14:23
@v-ruizh were any other containers running at the time that could have been holding port 5678?

**Comment by v-ruizh** [comment] 2020-03-04 14:36
@bwateratmsft I remove all running container and then debug again. There is no error in logs. But another error dialog pops up. (This issue also reproduces on Windows and Mac, but it's unstable)
![image](https://user-images.githubusercontent.com/45614674/75889776-6017be80-5e68-11ea-85a7-8b3475866dd7.png)

**Comment by haniamr** [comment] 2020-03-04 23:35
@v-ruizh do you have a repro environment that I can look at?
I couldn't repro this on an Ubuntu machine, what Linux distro are you using?

A couple of more questions:
- Is there anything printed in the debug console?
- While the container is running, can you do "docker logs {containerId}" and share if there's any output?
- While the container is running, do the following and share the output:
    - "docker exec {containerId} cat /dbglogs/ptvsd-1.log"

Thanks!

**Comment by karolz-ms** [comment] 2020-03-05 19:10
Just tried on Ubuntu 18.04 machine via Remote-SSH and it works...  😕 

BTW It is pretty cool that the server runs remotely, but my browser still can reach it via a localhost port

**Comment by bwateratmsft** [comment] 2020-03-05 19:28
@karolz-ms That had us confused for a bit until we realized that it's some VSCode magic, since we use their `openExternal` API. They're basically making a "proxy" locally.

**Comment by notpushkin** [comment] 2020-03-07 21:34
Sorry for hijacking this issue, but how can one get the nightly builds? Or the only way is to build it by hand?

**Comment by haniamr** [comment] 2020-03-11 22:47
To provide more context, this happens as the VM is not directly on the physical machine but in a nested VM, which caused the weird side effect that files created in the container in a volume were not accessible in the host.

Since @karolz-ms and @v-ruizh confirmed this is not reproducing given the VM is directly on the physical machine, I'll close the issue for now.

**Closed by haniamr** 2020-03-11 22:47 UTC
Labels: AT-CTI, needs more info
