### ISSUE TITLE
Windows with WSL can't compose up, if not connected to wsl as remote

### ISSUE THREAD

**Issue by dysondi** [microsoft/vscode-docker#3991] opened 2023-06-29 20:56 UTC
This occurs consistently

Repro steps:

1. create any docker-compose.yml file 
2. make sure that VS Code don't connected to WSL as remote window, it should be native windows
3. right click to docker-compose.yml file in explorer
4. Compose UP
    expected results-  compouse up
    actual result - next error:
error, which I got:
Executing task: docker compose -f "monitoring\docker-compose.yml" up -d --build 

stat /mnt/d/Nextcloud/GIT/BT/infrastructure/monitoring\docker-compose.yml: no such file or directory

 *  The terminal process "C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 -e docker compose -f "monitoring\docker-compose.yml" up -d --build" terminated with exit code: 14. 
 *  Terminal will be reused by tasks, press any key to close it. 

It uses wsl.exe command but path to docker-compose.yml is relative, not full
in my case it should be /mnt/d/Nextcloud/GIT/BT/infrastructure/monitoring/docker-compose.yml

I don't know why slash in "stat" command is in other side

otherwise, if I click reopen window in WSL, everything works great 

Version: 1.25.2
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.79.2
Language: en

**Comment by danegsta** [comment] 2023-07-06 17:56
@dysondi this looks to be a duplicate of #3803; we don't currently support running Docker commands directly inside a specific WSL instance without WSL remoting. We don't currently have any commands that would be executed using wsl.exe; do you have any extra WSL related extensions installed that may be overriding your vscode terminal behavior?

**Closed** 2023-07-21 05:32 UTC
Labels: duplicate, info-needed
