### ISSUE TITLE
Add Github Registry to the supported list

### ISSUE THREAD

**Issue by The224** [microsoft/vscode-docker#1525] opened 2020-01-03 17:00 UTC
Github as is own package registry, [docker.pkg.github.com](docker.pkg.github.com), that can be used as a docker registry. 

Connecting as a *Generic Docker Registry* result to `404 page not found` error. Maybe the API is different. 

[More info about Github packages](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-docker-for-use-with-github-packages)

It could be nice to add Github registry to the list of providers.

**Comment by philliphoff** [comment] 2020-01-07 06:20
@The224 It appears that the Github Package Docker Registry does not support the `_catalog` API used to list the repositories within the registry. I can't find any information about the extent to which Github supports the (V2) API for Docker registries.  It does appear to support, for example, listing tags for a given image.

@phanatic Would you be able to point me to information about Github's support for the Docker registry API?

**Comment by Phanatic** [comment] 2020-01-07 15:09
@philliphoff we don't support the `_catalog` endpoint in the GitHub Docker Registry today. 
I can open an issue to track this, which other API endpoints are necessary for this extension to work? 
I can check and create issues for any missing support from the [Docker HTTP API spec](https://docs.docker.com/registry/spec/api/)

**Comment by philliphoff** [comment] 2020-01-07 22:11
@Phanatic Our extension creates a tree view for Docker registries, listing each repository in a registry and then each tag within a repository, which means supporting *at least* the `_catalog` and `<repo>/tag/list` endpoints.  It then allows the user to pull/delete an entire repository, or to pull/untag/delete/get-digest-for individual images.  Some of those commands go through the Docker command line, while others use the HTTP API directly (via a Node.js client library), so it's somewhat tedious to identify the exhaustive list of endpoints used, but the closer GitHub can get to 100% coverage of the (V2) spec, the more likely the tools will "just work".

**Comment by dbreshears** [comment] 2020-01-17 19:09
@Phanatic,   is there an issue logged that we can track and any current status / eta on this?  This is a frequent request for a Docker extension container registry feature

**Comment by bwateratmsft** [comment] 2020-02-27 19:03
@Phanatic Do you know where we can create/track issues on the API?

**Comment by bwateratmsft** [comment] 2020-03-27 19:03
For now I'll resolve this as a dupe of #869, we are tracking GitHub support there.

**Closed by bwateratmsft** 2020-03-27 19:03 UTC
Labels: blocked, external

**Comment by jayarjo** [comment] 2020-03-28 09:00
Everybody involved in this, please proceed. @Phanatic please cooperate.
