### ISSUE TITLE
Add syntax highlighting for Dockerfile(.*)

### ISSUE THREAD

**Issue by lynncyrin** [microsoft/vscode-docker#511] opened 2018-09-25 00:13 UTC
Source issue https://github.com/Microsoft/vscode/issues/38797

**Comment by EricJizbaMSFT** [comment] 2019-05-08 17:13
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/192

**Closed by EricJizbaMSFT** 2019-05-08 17:13 UTC
Labels: P1, investigate
