### ISSUE TITLE
Environment variable in EXPOSE definition shows up as an error

### ISSUE THREAD

**Issue by otbutz** [Microsoft/vscode-docker#184] opened 2017-11-27 13:20 UTC
I'm defining the exposed port of my application via `ENV` in order to reuse it across the Dockerfile and be able to access it from within the running container. This leads to the following definition in my Dockerfile:

    EXPOSE $SERVICE_PORT

Docker has no problem with this but dockerfile-lsp shows the following error:

    Invalid containerPort: $SERVICE_PORT

I don't think that a complete validation is possible but at least a warning would be more appropriate.

**Comment by chrisdias** [comment] 2017-11-27 13:49
@rcjsuen

**Comment by chrisdias** [comment] 2017-11-27 13:51
dupe of #167

**Comment by chrisdias** [comment] 2017-11-27 13:52
which has been merged, so fix will be published hopefully this week, if not then over the weekend.

**Closed by chrisdias** 2017-11-27 13:51 UTC

**Comment by rcjsuen** [comment] 2017-11-27 22:08
Hi @otbutz, thank you for the bug report.

Could you provide your Dockerfile just so that I can verify that the problem won't affect you in the next release of the vscode-docker extension? Thanks!

**Comment by otbutz** [comment] 2017-11-28 08:42
I'm afraid that this is not possible without violating our corporate policy. But the usecase isn't that complicated:

    ENV SERVICE_PORT=8080
    # ...
    EXPOSE $SERVICE_PORT

**Comment by rcjsuen** [comment] 2017-11-28 10:35
Thank you, @otbutz. It certainly looks like the same problem as #167 then.
