### ISSUE TITLE
[Suggestion]Add a command to run 'Deploy Image to Azure App Service'

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#814] opened 2019-03-01 09:04 UTC
**OS:** All
**Build Version:** [20190228.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3669)
**Regression:** Not a Regression

**Repro Steps:**
1. F1 --> Type 'Deploy Image to Azure App Service'.
2. Check the result.

**Actual:**
Display 'No commands matching'.
![image](https://user-images.githubusercontent.com/34729092/53627624-ca46b500-3bbd-11e9-88f1-a7f1999d986b.png)

**Suggestion:**
Add a command to run 'Deploy Image to Azure App Service'.

**Comment by EricJizbaMSFT** [comment] 2019-06-04 17:03
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/551

**Closed by EricJizbaMSFT** 2019-06-04 17:03 UTC
Labels: AT-CTI, P2
