### ISSUE TITLE
Docker install in Windows failing due to wrong download URL

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-docker#2297] opened 2020-09-10 19:58 UTC
Tried to install Docker through the extension but it is failing while downloading the installed.

After checking the code, it looks like the download URL is broken: https://aka.ms/download-docker-windows-vscode

![image](https://user-images.githubusercontent.com/56176070/92795395-34b8e380-f365-11ea-85a5-c23f999fde31.png)

**Comment by bwateratmsft** [comment] 2020-09-10 19:59
I can reproduce. We'll take a look, thanks!

**Comment by bwateratmsft** [comment] 2020-09-10 20:46
Looks like the location changed from `https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe` to `https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe`, we'll need to get the forward link updated.

**Comment by bwateratmsft** [comment] 2020-09-10 21:03
@BigMorty updated the aka.ms link and I just verified it. I'll close this as fixed.

**Closed by bwateratmsft** 2020-09-10 21:03 UTC
Labels: bug, investigate
