### ISSUE TITLE
Syntax highlighting does not support here-documents

### ISSUE THREAD

**Issue by FeryET** [microsoft/vscode-docker#4189] opened 2023-12-14 16:05 UTC
Docker introduced the concept of here-documents to its Dockerfiles in dockerfile v1.4, which is about 10 months old now, and during this time, I've been using the newer features more and more. Most importantly, the here-documents:

https://docs.docker.com/engine/reference/builder/#here-documents

This is ultra-handy for me as I can remove as much as unneeded boilerplate from my dockerfile context as I like, and have the single source of truth.

But VSCode-Docker does not support this feature yet. It would be pretty awesome if this could be added in the future to this awesome extension.

**Comment by bwateratmsft** [comment] 2023-12-14 16:16
This looks like a dupe of #4188

**Closed by bwateratmsft** 2023-12-14 16:16 UTC
