### ISSUE TITLE
Docker not found when running images

### ISSUE THREAD

**Issue by gibboneto** [microsoft/vscode-docker#3328] opened 2021-11-20 16:42 UTC
Does this occur consistently? YES
Repro steps:
Trying to execute the RUN and RUN INTERACTIVE functions of the VSCODE Docker Extension on any image, I get the following error: 

```
zsh:1: command not found: docker
The terminal process "zsh '-c', 'docker run --rm -d  -p 8888:8888/tcp <image_name>'" terminated with exit code: 127.
```

NB:
All Docker CLI commands are working normally within the integrated zsh terminal.

All the other docker extensions commands are working normally on running containers.

Version: 1.18.0
OS: darwin
OS Release: 21.1.0
Product: Visual Studio Code
Product Version: 1.62.3
Language: en

**Comment by karolz-ms** [comment] 2021-11-22 17:06
Most likely a duplicate of https://github.com/microsoft/vscode-docker/issues/3281
But thanks anyway, appreciate helping us make the extension better!

**Closed by karolz-ms** 2021-11-22 17:06 UTC
Labels: duplicate
