### ISSUE TITLE
remove alpine

### ISSUE THREAD

**Issue by lavrud** [microsoft/vscode-docker#1517] opened 2019-12-29 20:25 UTC
Repro steps:

1.
2.

Action: vscode-docker.images.remove
Error type: 409
Error Message: (HTTP code 409) conflict - conflict: unable to delete e1495e4ac50d (cannot be forced) - image has dependent child images 

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546extension.bundle.js:324:440546
extension.bundle.js:324:440508extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by ravipal** [comment] 2019-12-31 18:41
Dupe of #1398

**Closed by ravipal** 2019-12-31 18:41 UTC
