### ISSUE TITLE
docker registry  delete a images

### ISSUE THREAD

**Issue by alparslanozturk** [microsoft/vscode-docker#1513] opened 2019-12-26 09:10 UTC
Repro steps:

1.
2.

Action: vscode-docker.registries.deleteImage
Error type: UNSUPPORTED
Error Message: The operation is unsupported.

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
new i extension.bundle.js:218:1478865
$.callback extension.bundle.js:218:1477708
$.e.callback.t.callback [as _callback] extension.bundle.js:218:1476756
$.t._callback.t.callback.t.callback extension.bundle.js:194:5618
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18478
$.emit events.js:200:13
IncomingMessage.<anonymous> extension.bundle.js:194:17310
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by ravipal** [comment] 2019-12-26 20:14
@alparslanozturk, Do you hit this error as soon as you select the command? or after providing all the details and while invoking the delete operation?
Also, do you hit the same error from docker view -> Images -> image -> right click -> Remove?

**Comment by alparslanozturk** [comment] 2019-12-27 06:57
![image](https://user-images.githubusercontent.com/9527118/71505685-2d14e580-288f-11ea-941e-f38566dd7c26.png)

this message and I click  "delete "

![image](https://user-images.githubusercontent.com/9527118/71505704-428a0f80-288f-11ea-8f7a-e03c4229e530.png)

**Comment by philliphoff** [comment] 2020-01-07 00:12
@alparslanozturk What kind of image registry are you trying to delete images from (e.g. Docker Hub, Azure Container Registry, other Docker-compatible registry, etc.)?  Do you have permissions to delete images (or that particular image) from that registry?

**Comment by alparslanozturk** [comment] 2020-01-13 08:04
private registry, I just create from  docker-registry image.

[image: image.png]


Phillip Hoff <notifications@github.com>, 7 Oca 2020 Sal, 03:12 tarihinde
şunu yazdı:

**Comment by dbreshears** [comment] 2020-02-14 19:23
@alparslanozturk ,  are you able to login to the registry and delete the image from the command line?   Can you provide steps that reproduce the issue?

**Comment by alparslanozturk** [comment] 2020-02-19 10:26
Does this occur consistently? 
Repro steps:


1.
2.

Action: vscode-docker.registries.deleteImage
Error type: UNSUPPORTED
Error Message: The operation is unsupported.

Version: 0.10.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
new i extension.bundle.js:317:58453
B.callback extension.bundle.js:317:57296
B.e.callback.t.callback [as _callback] extension.bundle.js:317:56344
B.t._callback.t.callback.t.callback extension.bundle.js:194:5618
B.emit events.js:200:13
B.<anonymous> extension.bundle.js:194:18478
B.emit events.js:200:13
IncomingMessage.<anonymous> extension.bundle.js:194:17310
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>



[image: image.png]


[image: image.png]




Devin Breshears <notifications@github.com>, 14 Şub 2020 Cum, 22:23
tarihinde şunu yazdı:

**Comment by bwateratmsft** [comment] 2020-02-19 14:20
@alparslanozturk are you able to delete these images from the CLI?

**Comment by bwateratmsft** [comment] 2020-03-05 17:08
Marking as a dupe of #1683

**Closed by bwateratmsft** 2020-03-05 17:08 UTC
Labels: needs more info
