### ISSUE TITLE
"docker daemon cannot be reached"

### ISSUE THREAD

**Issue by otrfirms** [microsoft/vscode-docker#2211] opened 2020-07-30 19:50 UTC
Action: vscode-docker.installDocker
Error type: ECONNRESET
Error Message: socket hang up

Version: 1.1.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
connResetException errors.js:559:14
TLSSocket.socketOnEnd _http_client.js:436:23
TLSSocket.emit events.js:205:15
TLSSocket.EventEmitter.emit domain.js:471:20
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by karolz-ms** [comment] 2020-08-03 16:40
This is a duplicate of https://github.com/microsoft/vscode-docker/issues/1913 that has been fixed since. You are using Docker extension 1.1.0; the current version is 1.4.1.

**Closed by karolz-ms** 2020-08-03 16:40 UTC
Labels: duplicate
