### ISSUE TITLE
11

### ISSUE THREAD

**Issue by liuqiugui** [microsoft/vscode-docker#1646] opened 2020-02-21 23:49 UTC
Repro steps:

1.
2.

Action: vscode-docker.networks.remove
Error type: 403
Error Message: (HTTP code 403) unexpected - none is a pre-defined network and cannot be removed 

Version: 0.8.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098
extension.bundle.js:157:703061
module.exports.m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment] 2020-02-24 14:12
Dupe of #1383

**Closed by bwateratmsft** 2020-02-24 14:12 UTC
