### ISSUE TITLE
Just editing a java project and then this problem

### ISSUE THREAD

**Issue by guillempascual** [microsoft/vscode-docker#2577] opened 2020-12-22 14:39 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-context.initialize
Error type: 127
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 127
Error: /bin/sh: docker: command not found

Version: 1.9.0
OS: darwin
OS Release: 20.1.0
Product: Visual Studio Code
Product Version: 1.52.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:95302
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:430:11
Socket.emit events.js:223:5
Pipe.<anonymous> net.js:664:12
```

</details>

**Comment by karolz-ms** [comment] 2020-12-22 16:33
I am sorry and thank you for the report. This is not really the Docker extension fault, but we should at least a workaround. I have opened https://github.com/microsoft/vscode-docker/issues/2578 to do something in the next extension release (should appear in the 1st half of January)

**Comment by karolz-ms** [comment] 2020-12-22 16:38
Duplicate of https://github.com/microsoft/vscode-docker/issues/2254

**Closed by karolz-ms** 2020-12-22 16:38 UTC
Labels: duplicate
