### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by phantomXhawk** [microsoft/vscode-docker#2905] opened 2021-04-27 08:20 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.help.openStartPage
Error type: Error
Error Message: Webview is disposed

Version: 1.12.1
OS: linux
OS Release: 5.10.0-6parrot1-amd64
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
v.assertNotDisposed extensionHostProcess.js:87:53676
v.set html [as html] extensionHostProcess.js:87:53045
StartPage.createOrShow extension.bundle.js:2:4383398
async openStartPage extension.bundle.js:2:4385088
```

</details>

**Comment by karolz-ms** [comment] 2021-04-27 15:49
@phantomXhawk thanks for reporting the issue

Duplicate of https://github.com/microsoft/vscode-docker/issues/2898

**Closed by karolz-ms** 2021-04-27 15:49 UTC
Labels: duplicate
