### ISSUE TITLE
The running container shows with ID in Container View if enabling Docker Desktop setting "Compose V2"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3159] opened 2021-08-20 09:40 UTC
**OS:** Win 10
**Build Version:** 20210816.22

**Repro Steps:**
1. Open Docker Desktop settings -> Experimental Features -> Enable "Use Docker Compose V2 release candidate".
2. Switch Docker Desktop to Linux Container.
3. Open one .NET MVC project in VS Code and add Docker support for it.
4. Right click the docker-compose.yml file and execute "Compose Up" action.
5. Check whether the running container shows with name in Container View or not.

**Expect:**
The running container shows with name.
![image](https://user-images.githubusercontent.com/45614674/130212964-081322d0-cb88-4d89-a891-e57a13d65db7.png)

**Actual:**
The running container shows with ID.
![image](https://user-images.githubusercontent.com/45614674/130212985-25bca127-17d1-4c27-b099-279f70e3751e.png)

**More Info:**
This issue does not reproduce if disabling Docker Desktop setting "Use Docker Compose V2 release candidate".

**Comment by bwateratmsft** [comment] 2021-08-20 13:59
Dupe of #3040. It is a regression from the Compose V2 CLI; they are working on fixing it.

**Closed by bwateratmsft** 2021-08-20 13:59 UTC
Labels: AT-CTI
