### ISSUE TITLE
Add port and volume options to 'Run interactive'

### ISSUE THREAD

**Issue by 1138-4EB** [microsoft/vscode-docker#1001] opened 2019-06-18 01:02 UTC
I find myself frequently writing commands as:

``` bash
$(command -v winpty) docker run --rm -itv /$(pwd)://src -p 8000:8000 image_name bash
```

or

``` bash
$(command -v winpty) docker run --rm -dv /$(pwd)://src -p 8000:8000 image_name bash -c "tail -f /dev/null"
```

in order to start a container to test/try some random project from GitHub. I then use Visual Studio Code's `Remote - Containers` extension along with this extension to attach to it, to run additional interactive sessions, and to remove the container. It would be great if this extension provided the feature to create these custom 'run' commands.

Ideally, a `Run Interactive Opts` option would be added to the context-menu of the images; which, instead of starting a session right away, would add an item to a (new) `Configurations` list below. Then, the context-menu of each item in the list would allow to add/remove volumes/ports, to start the session, and to rename/remove the item.

This would greatly improve UX thanks to the ability to select the paths graphically (taking the workspace as a reference) and to show a list of recently used paths/ports.

I know that multiple alternatives exist which use configuration files of different kinds. However, I want to precisely avoid having to type all the paths. These are just some temporal/stash configurations that the user might later want to save/export, but that will be frequently discarded.

**Comment by 1138-4EB** [comment] 2019-08-05 10:22
As a side note, when a multi-root workspace is open and a new terminal is created, a list is shown for the user to select which of the folders is to be used as the root/workdir of the terminal. The same approach can be used here.

**Comment by bwateratmsft** [comment] 2019-10-08 13:54
Since it covers the same scenario, I'm going to resolve this one as a dupe of #1321

**Closed by bwateratmsft** 2019-10-08 13:54 UTC

**Comment by 1138-4EB** [comment] 2019-10-09 22:50
@bwateratmsft, on the one hand, I tried https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10975 and https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10908 in order to test #1245 nd #1327, which are referenced in #1321, but I couldn't find how to use them. I saw that command `Docker: initialize for Docker debugging` was added. The first step requires to select a directory, and then three options are shown: Node.js, ASP.NET Core, .NET Core Console. Then, I had a look at 'Tasks' and tried to create a `tasks.json` file. However, I don't understand why would anyone write such a file instead of a docker CLI command. Therefore, I must be missing something, because I don't see how #1321 and this issue are solved.

On the other hand, although #1321 might seem a dupe of this issue, there is a very relevant difference: my request/proposal is to add a `Configurations` view/explorer, where temporal configurations/tasks are listed/edited. Editing means adding ports, volumes, envvars, etc. through the context-menu and using VSCode features for e.g. selecting folders on the host to be shared with the container. These items/tasks would be exportable to docker cli commands, and (ideally) importable from CLI commands.

**Comment by bwateratmsft** [comment] 2019-10-10 13:21
@1138-4EB That configurations you describe is going to be tasks. #1321 allows for tasks to be configured that aren't for a particular platform, namely, `docker-build` type tasks and `docker-run` type tasks. For build, a context and Dockerfile must be specified; for run, an image is the only requirement. While we don't have an import from CLI story, it will show the command run in the terminal window, which can be copy-pasted to CLI.

Here's an example of a `docker-run` task to create a Mongo container:
```
        {
            "type": "docker-run",
            "label": "Run Mongo DB",
            "dockerRun": {
                "image": "mongo:4.2"
            }
        }
```

**Comment by 1138-4EB** [comment] 2019-10-10 13:32
@bwateratmsft thanks a lot for clarifying! Would you mind pointing me to any documentation or any instructions about how to test it? I'd like to probably contribute import/export features, if that is not something on your priority list.

**Comment by bwateratmsft** [comment] 2019-10-10 13:37
@1138-4EB Unfortunately we don't have documentation yet, but it is on our list before we release the task-based debugging model: #1113, #1334, and related #766
