### ISSUE TITLE
do not create docker file??

### ISSUE THREAD

**Issue by goodking-bq** [microsoft/vscode-docker#1189] opened 2019-08-06 10:58 UTC
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open '\mnt\d\flask-sqlalchemy-graphene-example\docker-compose.yml'

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.openSync fs.js:436:3
Object.module.ELECTRON_ASAR.js:160:31
Object.writeFileSync fs.js:1168:35
extension.bundle.js:1:288233extension.bundle.js:1:288233
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-08-06 15:37
@goodking-bq It looks like you're running in WSL? In which case, closing as duplicate of https://github.com/microsoft/vscode-docker/issues/960 and https://github.com/microsoft/vscode-docker/issues/954

You can work around this by adding this to your VS Code settings:
```
"remote.extensionKind": {
    "ms-azuretools.vscode-docker": "workspace"
}
```
Make sure to reload VS Code afterwards. This will make sure the Docker extension is _also_ running in WSL.

**Closed by EricJizbaMSFT** 2019-08-06 15:37 UTC
