### ISSUE TITLE
images panel not showing correct date created

### ISSUE THREAD

**Issue by edwardchenchen** [microsoft/vscode-docker#3732] opened 2022-11-29 23:45 UTC
version 1.23

<img width="546" alt=" 2022-11-30 at 10 44 23" src="https://user-images.githubusercontent.com/6397192/204672879-7325c93a-eaaf-4d65-b057-f7dcbd3ea417.png">

version  1.22.2

<img width="541" alt=" 2022-11-30 at 10 45 26" src="https://user-images.githubusercontent.com/6397192/204672994-cecda894-9a75-4d82-a3ac-18e248718fc9.png">

**Comment by bwateratmsft** [comment] 2022-11-30 13:55
This is a duplicate of #3718. We plan to release a fix today.

**Closed by bwateratmsft** 2022-11-30 13:55 UTC
