### ISSUE TITLE
The "myapp" container's state always keeps "running" after executing "Compose Up" for the "docker-compose.debug.yml" file

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#2939] opened 2021-05-14 09:39 UTC
**OS:** All
**Build Version:** 20210513.4

**Repro Steps:**

1. Open the `myapp` python project in VS Code.
2. F1 -> Add Docker Files to Workspace -> Python: General -> myapp.py ->Yes.
3. Right click `docker-compose.debug.yml` file -> Compose Up.
4. Navigate to Docker view.
5. Check whether the "myapp" container's state is "stop" under the "CONTAINERS" tree view.

**Expect:**
The "myapp" container's state is "stop" under the "CONTAINERS" tree view.

**Actual:**
The "myapp" container's state always keeps "running" under the "CONTAINERS" tree view.
![image](https://user-images.githubusercontent.com/57662131/118242518-041ae200-b4d0-11eb-8c69-cea39b19a35e.png)

**Comment by karolz-ms** [comment] 2021-05-14 15:46
This must be some misunderstanding--after "compose up" action the containers are supposed to be in running state. Even if waiting for debugger to attach.

Feel free to contact me via email if clarification is needed. I am going to close this one for now.

**Comment by v-xinda** [comment] 2021-05-15 14:25
@karolz-ms The "myapp" container's state is "stop" under the "CONTAINERS" tree view after composing up `docker-compose.yml` file. The result is inconsistent after executing "Compose Up" for the `docker-compose.yml` and `docker-compose.debug.yml` files.

**Comment by v-mengwe** [comment] 2021-06-18 12:41
Verified on the latest build 20210615.1, this issue still reproduces for now. The result is inconsistent after executing "Compose Up" for the **`docker-compose.yml`** and **`docker-compose.debug.yml`** files.

Right click **`docker-compose.yml`** file -> Compose Up -> There is a stopped container.
![image](https://user-images.githubusercontent.com/62053665/122561353-596c8500-d074-11eb-9c78-2c82e10e9e67.png)

Right click **`docker-compose.debug.yml`** file -> Compose Up -> There is a running container.
![image](https://user-images.githubusercontent.com/62053665/122561676-b9632b80-d074-11eb-98a1-e92078c83e96.png)

**Comment by karolz-ms** [comment] 2021-06-18 20:12
I cannot reproduce, but without "myapp" sources it is hard to be certain there is no issue. @v-mengwe could you share the sources?

I tried a Flask app with the following files (choosing "Python: Flask" during scaffolding) and it all works when doing `compose up` both on the "normal" version, as well as "debug" version

*app.py*
```python
from flask import Flask
import os
import signal

app = Flask(__name__)

@app.route("/")
def hello():
    html = """
    <!doctype html>
    <html>
      <head>
        <title>Amazing Flask app</title>
      </head>
      <body>
        <h3>Hello, World!</h3>
      </body>
    </html>
    """
    return html

@app.route('/shutdown', methods=['POST'])
def shutdown():
  # Send TERM signal to master process (request handlers are running in a worker process)
  os.kill(os.getppid(), signal.SIGTERM)
  return ('Shutting down...', 202)

@app.route('/failfast', methods=['POST'])
def failfast():
  # For this to work properly with Docker you need to use Docker init process (--init parameter to 'docker run')
  os.kill(os.getppid(), signal.SIGKILL)
  return ('', 204)

if __name__ == "__main__":
  app.run(host='0.0.0.0', port=31117)
```

*requirements.txt*
```python
# To ensure app dependencies are ported from your virtual environment/host machine into your container, run 'pip freeze > requirements.txt' in the terminal to overwrite this file
flask==1.1.2
gunicorn==20.0.4

```

**Comment by v-mengwe** [comment] 2021-06-21 08:24
The `myapp` python project: select "Python: General" application platform to it.
![image](https://user-images.githubusercontent.com/62053665/122730422-c5d1c900-d2ac-11eb-97a1-3ad33eec6dfc.png)

**Comment by karolz-ms** [comment] 2021-06-21 16:04
@v-mengwe thanks, makes sense now. The observed behavior is expected. When debug Compose file is used, it will run the program under the debugger, and the debugger will wait for VS Code to attach before actually starting the main program. That is why the container does not exit.

**Closed by karolz-ms** 2021-06-21 16:04 UTC
Labels: AT-CTI, needs more info

**Comment by v-mengwe** [comment] 2021-06-22 01:28
@karolz-ms Got it, thanks for your sharing.
