### ISSUE TITLE
There is no suggestions of docker image or any syntax when I am writing a docker compose file

### ISSUE THREAD

**Issue by yankeexe** [microsoft/vscode-docker#426] opened 2018-08-29 04:23 UTC

**Comment by StephenWeatherford** [comment] 2018-08-29 20:51
What's the name of your docker compose file?

**Comment by yankeexe** [comment] 2018-08-30 00:30
@StephenWeatherford it is docker-compose.yml

**Comment by Abhinav1217** [comment] 2019-01-21 16:04
I too can not get intellisense or help when writing docker-compose.yml file. Only option is using ctrl+space. I saw #128 which is closed, It said this is tracked by #243 which is also closed. This is only open issue regarding this.

**Comment by EricJizbaMSFT** [comment] 2019-05-08 17:27
#243 is still open - closing as a duplicate of that. It also has a workaround listed here: https://github.com/microsoft/vscode-docker/issues/243#issuecomment-489879233

**Closed by EricJizbaMSFT** 2019-05-08 17:27 UTC
Labels: P2, investigate
