### ISSUE TITLE
'Add docker files to workspace' should check for dependency

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#1475] opened 2019-12-09 19:06 UTC
Repro steps:

1. Open an empty folder and launch terminal
2. Create a mvc app ('dotnet new mvc')
3. Didn't wait for the prompt to add dotnet debugging tasks.
4. 'Docker: Add docker files to workspace'. 
5. F5 shows this error.
![image](https://user-images.githubusercontent.com/1775825/70464436-ba74cf00-1a73-11ea-81dd-0385bceecc76.png)

**Comment by philliphoff** [comment] 2019-12-10 18:00
Closing as dupe of #1423.

**Closed by philliphoff** 2019-12-10 18:00 UTC
